# syntax=docker/dockerfile:1.7
FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
EXPOSE 8003
CMD ["pnpm", "docs:dev", "--host", "0.0.0.0", "--port", "8003"]
