/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ExecuteFlinkSqlPreview400,
  ExecuteFlinkSqlPreview500,
  FlinkSqlPreviewRequest,
  FlinkSqlPreviewResponse,
  FlinkSqlValidateRequest,
  FlinkSqlValidateResponse,
  ValidateFlinkSql400,
  ValidateFlinkSql500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





export const getValidateFlinkSqlUrl = () => {




  return `/api/flink/sql:validate`
}

/**
 * @summary 校验 Flink SQL
 */
export const validateFlinkSql = async (flinkSqlValidateRequest: FlinkSqlValidateRequest, options?: RequestInit): Promise<FlinkSqlValidateResponse> => {

  return customFetch<FlinkSqlValidateResponse>(getValidateFlinkSqlUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkSqlValidateRequest)
  }
);}





export const getValidateFlinkSqlMutationOptions = <TError = ValidateFlinkSql400 | ValidateFlinkSql500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateFlinkSql>>, TError,{data: FlinkSqlValidateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof validateFlinkSql>>, TError,{data: FlinkSqlValidateRequest}, TContext> => {

const mutationKey = ['validateFlinkSql'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateFlinkSql>>, {data: FlinkSqlValidateRequest}> = (props) => {
          const {data} = props ?? {};

          return  validateFlinkSql(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ValidateFlinkSqlMutationResult = NonNullable<Awaited<ReturnType<typeof validateFlinkSql>>>
    export type ValidateFlinkSqlMutationBody = FlinkSqlValidateRequest
    export type ValidateFlinkSqlMutationError = ValidateFlinkSql400 | ValidateFlinkSql500

    /**
 * @summary 校验 Flink SQL
 */
export const useValidateFlinkSql = <TError = ValidateFlinkSql400 | ValidateFlinkSql500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateFlinkSql>>, TError,{data: FlinkSqlValidateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateFlinkSql>>,
        TError,
        {data: FlinkSqlValidateRequest},
        TContext
      > => {
      return useMutation(getValidateFlinkSqlMutationOptions(options), queryClient);
    }
    export const getExecuteFlinkSqlPreviewUrl = () => {




  return `/api/flink/sql:preview`
}

/**
 * @summary 提交 SQL 调试预览
 */
export const executeFlinkSqlPreview = async (flinkSqlPreviewRequest: FlinkSqlPreviewRequest, options?: RequestInit): Promise<FlinkSqlPreviewResponse> => {

  return customFetch<FlinkSqlPreviewResponse>(getExecuteFlinkSqlPreviewUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkSqlPreviewRequest)
  }
);}





export const getExecuteFlinkSqlPreviewMutationOptions = <TError = ExecuteFlinkSqlPreview400 | ExecuteFlinkSqlPreview500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeFlinkSqlPreview>>, TError,{data: FlinkSqlPreviewRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof executeFlinkSqlPreview>>, TError,{data: FlinkSqlPreviewRequest}, TContext> => {

const mutationKey = ['executeFlinkSqlPreview'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeFlinkSqlPreview>>, {data: FlinkSqlPreviewRequest}> = (props) => {
          const {data} = props ?? {};

          return  executeFlinkSqlPreview(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteFlinkSqlPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof executeFlinkSqlPreview>>>
    export type ExecuteFlinkSqlPreviewMutationBody = FlinkSqlPreviewRequest
    export type ExecuteFlinkSqlPreviewMutationError = ExecuteFlinkSqlPreview400 | ExecuteFlinkSqlPreview500

    /**
 * @summary 提交 SQL 调试预览
 */
export const useExecuteFlinkSqlPreview = <TError = ExecuteFlinkSqlPreview400 | ExecuteFlinkSqlPreview500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeFlinkSqlPreview>>, TError,{data: FlinkSqlPreviewRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeFlinkSqlPreview>>,
        TError,
        {data: FlinkSqlPreviewRequest},
        TContext
      > => {
      return useMutation(getExecuteFlinkSqlPreviewMutationOptions(options), queryClient);
    }
