/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelFlinkJob200,
  CancelFlinkJob400,
  CancelFlinkJob500,
  CreateFlinkJob400,
  CreateFlinkJob500,
  DebugFlinkJob400,
  DebugFlinkJob500,
  DeleteFlinkJob200,
  DeleteFlinkJob400,
  DeleteFlinkJob500,
  FlinkCheckpointResponse,
  FlinkJobExecutionResponse,
  FlinkJobRequest,
  FlinkJobResponse,
  FlinkJobVersionRequest,
  FlinkJobVersionResponse,
  FlinkSavepointRecordResponse,
  FlinkSavepointResponse,
  GetFlinkCheckpoints400,
  GetFlinkCheckpoints500,
  GetFlinkJob400,
  GetFlinkJob500,
  ListFlinkJobExecutions400,
  ListFlinkJobExecutions500,
  ListFlinkJobVersions400,
  ListFlinkJobVersions500,
  ListFlinkJobs400,
  ListFlinkJobs500,
  ListFlinkJobsParams,
  ListFlinkSavepoints400,
  ListFlinkSavepoints500,
  PageResponseFlinkJobResponse,
  PublishFlinkJob400,
  PublishFlinkJob500,
  SavepointRequest,
  StartFlinkJob400,
  StartFlinkJob500,
  TriggerFlinkSavepoint400,
  TriggerFlinkSavepoint500,
  UpdateFlinkJob200,
  UpdateFlinkJob400,
  UpdateFlinkJob500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}`
}

/**
 * @summary 获取作业详情
 */
export const getFlinkJob = async (id: number, options?: RequestInit): Promise<FlinkJobResponse> => {

  return customFetch<FlinkJobResponse>(getGetFlinkJobUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlinkJobQueryKey = (id: number,) => {
    return [
    `/api/flink/jobs/${id}`
    ] as const;
    }


export const getGetFlinkJobQueryOptions = <TData = Awaited<ReturnType<typeof getFlinkJob>>, TError = GetFlinkJob400 | GetFlinkJob500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlinkJobQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlinkJob>>> = ({ signal }) => getFlinkJob(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlinkJobQueryResult = NonNullable<Awaited<ReturnType<typeof getFlinkJob>>>
export type GetFlinkJobQueryError = GetFlinkJob400 | GetFlinkJob500


export function useGetFlinkJob<TData = Awaited<ReturnType<typeof getFlinkJob>>, TError = GetFlinkJob400 | GetFlinkJob500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkJob>>,
          TError,
          Awaited<ReturnType<typeof getFlinkJob>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkJob<TData = Awaited<ReturnType<typeof getFlinkJob>>, TError = GetFlinkJob400 | GetFlinkJob500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkJob>>,
          TError,
          Awaited<ReturnType<typeof getFlinkJob>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkJob<TData = Awaited<ReturnType<typeof getFlinkJob>>, TError = GetFlinkJob400 | GetFlinkJob500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取作业详情
 */

export function useGetFlinkJob<TData = Awaited<ReturnType<typeof getFlinkJob>>, TError = GetFlinkJob400 | GetFlinkJob500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJob>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlinkJobQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}`
}

/**
 * @summary 更新作业
 */
export const updateFlinkJob = async (id: number,
    flinkJobRequest: FlinkJobRequest, options?: RequestInit): Promise<UpdateFlinkJob200> => {

  return customFetch<UpdateFlinkJob200>(getUpdateFlinkJobUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkJobRequest)
  }
);}





export const getUpdateFlinkJobMutationOptions = <TError = UpdateFlinkJob400 | UpdateFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJob>>, TError,{id: number;data: FlinkJobRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJob>>, TError,{id: number;data: FlinkJobRequest}, TContext> => {

const mutationKey = ['updateFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlinkJob>>, {id: number;data: FlinkJobRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlinkJob(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlinkJob>>>
    export type UpdateFlinkJobMutationBody = FlinkJobRequest
    export type UpdateFlinkJobMutationError = UpdateFlinkJob400 | UpdateFlinkJob500

    /**
 * @summary 更新作业
 */
export const useUpdateFlinkJob = <TError = UpdateFlinkJob400 | UpdateFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJob>>, TError,{id: number;data: FlinkJobRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlinkJob>>,
        TError,
        {id: number;data: FlinkJobRequest},
        TContext
      > => {
      return useMutation(getUpdateFlinkJobMutationOptions(options), queryClient);
    }
    export const getDeleteFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}`
}

/**
 * @summary 删除作业
 */
export const deleteFlinkJob = async (id: number, options?: RequestInit): Promise<DeleteFlinkJob200> => {

  return customFetch<DeleteFlinkJob200>(getDeleteFlinkJobUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFlinkJobMutationOptions = <TError = DeleteFlinkJob400 | DeleteFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJob>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlinkJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFlinkJob(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlinkJob>>>

    export type DeleteFlinkJobMutationError = DeleteFlinkJob400 | DeleteFlinkJob500

    /**
 * @summary 删除作业
 */
export const useDeleteFlinkJob = <TError = DeleteFlinkJob400 | DeleteFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJob>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlinkJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFlinkJobMutationOptions(options), queryClient);
    }
    export const getListFlinkJobsUrl = (params?: ListFlinkJobsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/flink/jobs?${stringifiedParams}` : `/api/flink/jobs`
}

/**
 * @summary 分页查询作业列表
 */
export const listFlinkJobs = async (params?: ListFlinkJobsParams, options?: RequestInit): Promise<PageResponseFlinkJobResponse> => {

  return customFetch<PageResponseFlinkJobResponse>(getListFlinkJobsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkJobsQueryKey = (params?: ListFlinkJobsParams,) => {
    return [
    `/api/flink/jobs`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFlinkJobsQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkJobs>>, TError = ListFlinkJobs400 | ListFlinkJobs500>(params?: ListFlinkJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkJobsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkJobs>>> = ({ signal }) => listFlinkJobs(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkJobs>>>
export type ListFlinkJobsQueryError = ListFlinkJobs400 | ListFlinkJobs500


export function useListFlinkJobs<TData = Awaited<ReturnType<typeof listFlinkJobs>>, TError = ListFlinkJobs400 | ListFlinkJobs500>(
 params: undefined |  ListFlinkJobsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobs>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobs<TData = Awaited<ReturnType<typeof listFlinkJobs>>, TError = ListFlinkJobs400 | ListFlinkJobs500>(
 params?: ListFlinkJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobs>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobs<TData = Awaited<ReturnType<typeof listFlinkJobs>>, TError = ListFlinkJobs400 | ListFlinkJobs500>(
 params?: ListFlinkJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 分页查询作业列表
 */

export function useListFlinkJobs<TData = Awaited<ReturnType<typeof listFlinkJobs>>, TError = ListFlinkJobs400 | ListFlinkJobs500>(
 params?: ListFlinkJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkJobsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateFlinkJobUrl = () => {




  return `/api/flink/jobs`
}

/**
 * @summary 创建作业
 */
export const createFlinkJob = async (flinkJobRequest: FlinkJobRequest, options?: RequestInit): Promise<FlinkJobResponse> => {

  return customFetch<FlinkJobResponse>(getCreateFlinkJobUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkJobRequest)
  }
);}





export const getCreateFlinkJobMutationOptions = <TError = CreateFlinkJob400 | CreateFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkJob>>, TError,{data: FlinkJobRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFlinkJob>>, TError,{data: FlinkJobRequest}, TContext> => {

const mutationKey = ['createFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlinkJob>>, {data: FlinkJobRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFlinkJob(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof createFlinkJob>>>
    export type CreateFlinkJobMutationBody = FlinkJobRequest
    export type CreateFlinkJobMutationError = CreateFlinkJob400 | CreateFlinkJob500

    /**
 * @summary 创建作业
 */
export const useCreateFlinkJob = <TError = CreateFlinkJob400 | CreateFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkJob>>, TError,{data: FlinkJobRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlinkJob>>,
        TError,
        {data: FlinkJobRequest},
        TContext
      > => {
      return useMutation(getCreateFlinkJobMutationOptions(options), queryClient);
    }
    export const getTriggerFlinkSavepointUrl = (id: number,) => {




  return `/api/flink/jobs/${id}:triggerSavepoint`
}

/**
 * @summary 触发 Savepoint
 */
export const triggerFlinkSavepoint = async (id: number,
    savepointRequest: SavepointRequest, options?: RequestInit): Promise<FlinkSavepointResponse> => {

  return customFetch<FlinkSavepointResponse>(getTriggerFlinkSavepointUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(savepointRequest)
  }
);}





export const getTriggerFlinkSavepointMutationOptions = <TError = TriggerFlinkSavepoint400 | TriggerFlinkSavepoint500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerFlinkSavepoint>>, TError,{id: number;data: SavepointRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof triggerFlinkSavepoint>>, TError,{id: number;data: SavepointRequest}, TContext> => {

const mutationKey = ['triggerFlinkSavepoint'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerFlinkSavepoint>>, {id: number;data: SavepointRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  triggerFlinkSavepoint(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerFlinkSavepointMutationResult = NonNullable<Awaited<ReturnType<typeof triggerFlinkSavepoint>>>
    export type TriggerFlinkSavepointMutationBody = SavepointRequest
    export type TriggerFlinkSavepointMutationError = TriggerFlinkSavepoint400 | TriggerFlinkSavepoint500

    /**
 * @summary 触发 Savepoint
 */
export const useTriggerFlinkSavepoint = <TError = TriggerFlinkSavepoint400 | TriggerFlinkSavepoint500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerFlinkSavepoint>>, TError,{id: number;data: SavepointRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerFlinkSavepoint>>,
        TError,
        {id: number;data: SavepointRequest},
        TContext
      > => {
      return useMutation(getTriggerFlinkSavepointMutationOptions(options), queryClient);
    }
    export const getStartFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}:start`
}

/**
 * @summary 启动作业
 */
export const startFlinkJob = async (id: number, options?: RequestInit): Promise<FlinkJobResponse> => {

  return customFetch<FlinkJobResponse>(getStartFlinkJobUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getStartFlinkJobMutationOptions = <TError = StartFlinkJob400 | StartFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startFlinkJob>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startFlinkJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['startFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startFlinkJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  startFlinkJob(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof startFlinkJob>>>

    export type StartFlinkJobMutationError = StartFlinkJob400 | StartFlinkJob500

    /**
 * @summary 启动作业
 */
export const useStartFlinkJob = <TError = StartFlinkJob400 | StartFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startFlinkJob>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startFlinkJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getStartFlinkJobMutationOptions(options), queryClient);
    }
    export const getPublishFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}:publish`
}

/**
 * @summary 发布作业版本
 */
export const publishFlinkJob = async (id: number,
    flinkJobVersionRequest?: FlinkJobVersionRequest, options?: RequestInit): Promise<FlinkJobVersionResponse> => {

  return customFetch<FlinkJobVersionResponse>(getPublishFlinkJobUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkJobVersionRequest)
  }
);}





export const getPublishFlinkJobMutationOptions = <TError = PublishFlinkJob400 | PublishFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishFlinkJob>>, TError,{id: number;data?: FlinkJobVersionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publishFlinkJob>>, TError,{id: number;data?: FlinkJobVersionRequest}, TContext> => {

const mutationKey = ['publishFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishFlinkJob>>, {id: number;data?: FlinkJobVersionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  publishFlinkJob(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof publishFlinkJob>>>
    export type PublishFlinkJobMutationBody = FlinkJobVersionRequest | undefined
    export type PublishFlinkJobMutationError = PublishFlinkJob400 | PublishFlinkJob500

    /**
 * @summary 发布作业版本
 */
export const usePublishFlinkJob = <TError = PublishFlinkJob400 | PublishFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishFlinkJob>>, TError,{id: number;data?: FlinkJobVersionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishFlinkJob>>,
        TError,
        {id: number;data?: FlinkJobVersionRequest},
        TContext
      > => {
      return useMutation(getPublishFlinkJobMutationOptions(options), queryClient);
    }
    export const getDebugFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}:debug`
}

/**
 * @summary 调试作业草稿
 */
export const debugFlinkJob = async (id: number, options?: RequestInit): Promise<FlinkJobResponse> => {

  return customFetch<FlinkJobResponse>(getDebugFlinkJobUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDebugFlinkJobMutationOptions = <TError = DebugFlinkJob400 | DebugFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof debugFlinkJob>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof debugFlinkJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['debugFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof debugFlinkJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  debugFlinkJob(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DebugFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof debugFlinkJob>>>

    export type DebugFlinkJobMutationError = DebugFlinkJob400 | DebugFlinkJob500

    /**
 * @summary 调试作业草稿
 */
export const useDebugFlinkJob = <TError = DebugFlinkJob400 | DebugFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof debugFlinkJob>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof debugFlinkJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDebugFlinkJobMutationOptions(options), queryClient);
    }
    export const getCancelFlinkJobUrl = (id: number,) => {




  return `/api/flink/jobs/${id}:cancel`
}

/**
 * @summary 取消作业
 */
export const cancelFlinkJob = async (id: number, options?: RequestInit): Promise<CancelFlinkJob200> => {

  return customFetch<CancelFlinkJob200>(getCancelFlinkJobUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCancelFlinkJobMutationOptions = <TError = CancelFlinkJob400 | CancelFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelFlinkJob>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelFlinkJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['cancelFlinkJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelFlinkJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  cancelFlinkJob(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelFlinkJobMutationResult = NonNullable<Awaited<ReturnType<typeof cancelFlinkJob>>>

    export type CancelFlinkJobMutationError = CancelFlinkJob400 | CancelFlinkJob500

    /**
 * @summary 取消作业
 */
export const useCancelFlinkJob = <TError = CancelFlinkJob400 | CancelFlinkJob500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelFlinkJob>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelFlinkJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCancelFlinkJobMutationOptions(options), queryClient);
    }
    export const getListFlinkJobVersionsUrl = (id: number,) => {




  return `/api/flink/jobs/${id}/versions`
}

/**
 * @summary 查询作业版本列表
 */
export const listFlinkJobVersions = async (id: number, options?: RequestInit): Promise<FlinkJobVersionResponse[]> => {

  return customFetch<FlinkJobVersionResponse[]>(getListFlinkJobVersionsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkJobVersionsQueryKey = (id: number,) => {
    return [
    `/api/flink/jobs/${id}/versions`
    ] as const;
    }


export const getListFlinkJobVersionsQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkJobVersions>>, TError = ListFlinkJobVersions400 | ListFlinkJobVersions500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkJobVersionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkJobVersions>>> = ({ signal }) => listFlinkJobVersions(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkJobVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkJobVersions>>>
export type ListFlinkJobVersionsQueryError = ListFlinkJobVersions400 | ListFlinkJobVersions500


export function useListFlinkJobVersions<TData = Awaited<ReturnType<typeof listFlinkJobVersions>>, TError = ListFlinkJobVersions400 | ListFlinkJobVersions500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobVersions>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobVersions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobVersions<TData = Awaited<ReturnType<typeof listFlinkJobVersions>>, TError = ListFlinkJobVersions400 | ListFlinkJobVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobVersions>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobVersions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobVersions<TData = Awaited<ReturnType<typeof listFlinkJobVersions>>, TError = ListFlinkJobVersions400 | ListFlinkJobVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询作业版本列表
 */

export function useListFlinkJobVersions<TData = Awaited<ReturnType<typeof listFlinkJobVersions>>, TError = ListFlinkJobVersions400 | ListFlinkJobVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobVersions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkJobVersionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListFlinkSavepointsUrl = (id: number,) => {




  return `/api/flink/jobs/${id}/savepoints`
}

/**
 * @summary 查询作业 Savepoint 列表
 */
export const listFlinkSavepoints = async (id: number, options?: RequestInit): Promise<FlinkSavepointRecordResponse[]> => {

  return customFetch<FlinkSavepointRecordResponse[]>(getListFlinkSavepointsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkSavepointsQueryKey = (id: number,) => {
    return [
    `/api/flink/jobs/${id}/savepoints`
    ] as const;
    }


export const getListFlinkSavepointsQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkSavepoints>>, TError = ListFlinkSavepoints400 | ListFlinkSavepoints500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkSavepointsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkSavepoints>>> = ({ signal }) => listFlinkSavepoints(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkSavepointsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkSavepoints>>>
export type ListFlinkSavepointsQueryError = ListFlinkSavepoints400 | ListFlinkSavepoints500


export function useListFlinkSavepoints<TData = Awaited<ReturnType<typeof listFlinkSavepoints>>, TError = ListFlinkSavepoints400 | ListFlinkSavepoints500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkSavepoints>>,
          TError,
          Awaited<ReturnType<typeof listFlinkSavepoints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkSavepoints<TData = Awaited<ReturnType<typeof listFlinkSavepoints>>, TError = ListFlinkSavepoints400 | ListFlinkSavepoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkSavepoints>>,
          TError,
          Awaited<ReturnType<typeof listFlinkSavepoints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkSavepoints<TData = Awaited<ReturnType<typeof listFlinkSavepoints>>, TError = ListFlinkSavepoints400 | ListFlinkSavepoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询作业 Savepoint 列表
 */

export function useListFlinkSavepoints<TData = Awaited<ReturnType<typeof listFlinkSavepoints>>, TError = ListFlinkSavepoints400 | ListFlinkSavepoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkSavepoints>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkSavepointsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListFlinkJobExecutionsUrl = (id: number,) => {




  return `/api/flink/jobs/${id}/executions`
}

/**
 * @summary 查询作业执行历史
 */
export const listFlinkJobExecutions = async (id: number, options?: RequestInit): Promise<FlinkJobExecutionResponse[]> => {

  return customFetch<FlinkJobExecutionResponse[]>(getListFlinkJobExecutionsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkJobExecutionsQueryKey = (id: number,) => {
    return [
    `/api/flink/jobs/${id}/executions`
    ] as const;
    }


export const getListFlinkJobExecutionsQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkJobExecutionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkJobExecutions>>> = ({ signal }) => listFlinkJobExecutions(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkJobExecutionsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkJobExecutions>>>
export type ListFlinkJobExecutionsQueryError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500


export function useListFlinkJobExecutions<TData = Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobExecutions>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobExecutions<TData = Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJobExecutions>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJobExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJobExecutions<TData = Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询作业执行历史
 */

export function useListFlinkJobExecutions<TData = Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError = ListFlinkJobExecutions400 | ListFlinkJobExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJobExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkJobExecutionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetFlinkCheckpointsUrl = (id: number,) => {




  return `/api/flink/jobs/${id}/checkpoints`
}

/**
 * @summary 查询作业 Checkpoint 状态
 */
export const getFlinkCheckpoints = async (id: number, options?: RequestInit): Promise<FlinkCheckpointResponse> => {

  return customFetch<FlinkCheckpointResponse>(getGetFlinkCheckpointsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlinkCheckpointsQueryKey = (id: number,) => {
    return [
    `/api/flink/jobs/${id}/checkpoints`
    ] as const;
    }


export const getGetFlinkCheckpointsQueryOptions = <TData = Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlinkCheckpointsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlinkCheckpoints>>> = ({ signal }) => getFlinkCheckpoints(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlinkCheckpointsQueryResult = NonNullable<Awaited<ReturnType<typeof getFlinkCheckpoints>>>
export type GetFlinkCheckpointsQueryError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500


export function useGetFlinkCheckpoints<TData = Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkCheckpoints>>,
          TError,
          Awaited<ReturnType<typeof getFlinkCheckpoints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkCheckpoints<TData = Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkCheckpoints>>,
          TError,
          Awaited<ReturnType<typeof getFlinkCheckpoints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkCheckpoints<TData = Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询作业 Checkpoint 状态
 */

export function useGetFlinkCheckpoints<TData = Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError = GetFlinkCheckpoints400 | GetFlinkCheckpoints500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkCheckpoints>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlinkCheckpointsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






