/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckFlinkRuntime400,
  CheckFlinkRuntime500,
  CreateFlinkRuntime200,
  CreateFlinkRuntime400,
  CreateFlinkRuntime500,
  DeleteFlinkRuntime200,
  DeleteFlinkRuntime400,
  DeleteFlinkRuntime500,
  FlinkRuntimeCheckResponse,
  FlinkRuntimeRequest,
  FlinkRuntimeResponse,
  GetFlinkRuntime400,
  GetFlinkRuntime500,
  ListFlinkRuntimes400,
  ListFlinkRuntimes500,
  ListFlinkRuntimesParams,
  PageResponseFlinkRuntimeResponse,
  UpdateFlinkRuntime200,
  UpdateFlinkRuntime400,
  UpdateFlinkRuntime500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetFlinkRuntimeUrl = (id: number,) => {




  return `/api/flink/runtimes/${id}`
}

/**
 * @summary 获取运行时详情
 */
export const getFlinkRuntime = async (id: number, options?: RequestInit): Promise<FlinkRuntimeResponse> => {

  return customFetch<FlinkRuntimeResponse>(getGetFlinkRuntimeUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlinkRuntimeQueryKey = (id: number,) => {
    return [
    `/api/flink/runtimes/${id}`
    ] as const;
    }


export const getGetFlinkRuntimeQueryOptions = <TData = Awaited<ReturnType<typeof getFlinkRuntime>>, TError = GetFlinkRuntime400 | GetFlinkRuntime500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlinkRuntimeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlinkRuntime>>> = ({ signal }) => getFlinkRuntime(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlinkRuntimeQueryResult = NonNullable<Awaited<ReturnType<typeof getFlinkRuntime>>>
export type GetFlinkRuntimeQueryError = GetFlinkRuntime400 | GetFlinkRuntime500


export function useGetFlinkRuntime<TData = Awaited<ReturnType<typeof getFlinkRuntime>>, TError = GetFlinkRuntime400 | GetFlinkRuntime500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkRuntime>>,
          TError,
          Awaited<ReturnType<typeof getFlinkRuntime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkRuntime<TData = Awaited<ReturnType<typeof getFlinkRuntime>>, TError = GetFlinkRuntime400 | GetFlinkRuntime500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkRuntime>>,
          TError,
          Awaited<ReturnType<typeof getFlinkRuntime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkRuntime<TData = Awaited<ReturnType<typeof getFlinkRuntime>>, TError = GetFlinkRuntime400 | GetFlinkRuntime500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取运行时详情
 */

export function useGetFlinkRuntime<TData = Awaited<ReturnType<typeof getFlinkRuntime>>, TError = GetFlinkRuntime400 | GetFlinkRuntime500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkRuntime>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlinkRuntimeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateFlinkRuntimeUrl = (id: number,) => {




  return `/api/flink/runtimes/${id}`
}

/**
 * @summary 更新运行时
 */
export const updateFlinkRuntime = async (id: number,
    flinkRuntimeRequest: FlinkRuntimeRequest, options?: RequestInit): Promise<UpdateFlinkRuntime200> => {

  return customFetch<UpdateFlinkRuntime200>(getUpdateFlinkRuntimeUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkRuntimeRequest)
  }
);}





export const getUpdateFlinkRuntimeMutationOptions = <TError = UpdateFlinkRuntime400 | UpdateFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkRuntime>>, TError,{id: number;data: FlinkRuntimeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFlinkRuntime>>, TError,{id: number;data: FlinkRuntimeRequest}, TContext> => {

const mutationKey = ['updateFlinkRuntime'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlinkRuntime>>, {id: number;data: FlinkRuntimeRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlinkRuntime(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlinkRuntimeMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlinkRuntime>>>
    export type UpdateFlinkRuntimeMutationBody = FlinkRuntimeRequest
    export type UpdateFlinkRuntimeMutationError = UpdateFlinkRuntime400 | UpdateFlinkRuntime500

    /**
 * @summary 更新运行时
 */
export const useUpdateFlinkRuntime = <TError = UpdateFlinkRuntime400 | UpdateFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkRuntime>>, TError,{id: number;data: FlinkRuntimeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlinkRuntime>>,
        TError,
        {id: number;data: FlinkRuntimeRequest},
        TContext
      > => {
      return useMutation(getUpdateFlinkRuntimeMutationOptions(options), queryClient);
    }
    export const getDeleteFlinkRuntimeUrl = (id: number,) => {




  return `/api/flink/runtimes/${id}`
}

/**
 * @summary 删除运行时
 */
export const deleteFlinkRuntime = async (id: number, options?: RequestInit): Promise<DeleteFlinkRuntime200> => {

  return customFetch<DeleteFlinkRuntime200>(getDeleteFlinkRuntimeUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFlinkRuntimeMutationOptions = <TError = DeleteFlinkRuntime400 | DeleteFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkRuntime>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkRuntime>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFlinkRuntime'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlinkRuntime>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFlinkRuntime(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlinkRuntimeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlinkRuntime>>>

    export type DeleteFlinkRuntimeMutationError = DeleteFlinkRuntime400 | DeleteFlinkRuntime500

    /**
 * @summary 删除运行时
 */
export const useDeleteFlinkRuntime = <TError = DeleteFlinkRuntime400 | DeleteFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkRuntime>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlinkRuntime>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFlinkRuntimeMutationOptions(options), queryClient);
    }
    export const getListFlinkRuntimesUrl = (params?: ListFlinkRuntimesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/flink/runtimes?${stringifiedParams}` : `/api/flink/runtimes`
}

/**
 * @summary 获取运行时列表
 */
export const listFlinkRuntimes = async (params?: ListFlinkRuntimesParams, options?: RequestInit): Promise<PageResponseFlinkRuntimeResponse> => {

  return customFetch<PageResponseFlinkRuntimeResponse>(getListFlinkRuntimesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkRuntimesQueryKey = (params?: ListFlinkRuntimesParams,) => {
    return [
    `/api/flink/runtimes`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFlinkRuntimesQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkRuntimes>>, TError = ListFlinkRuntimes400 | ListFlinkRuntimes500>(params?: ListFlinkRuntimesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkRuntimesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkRuntimes>>> = ({ signal }) => listFlinkRuntimes(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkRuntimesQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkRuntimes>>>
export type ListFlinkRuntimesQueryError = ListFlinkRuntimes400 | ListFlinkRuntimes500


export function useListFlinkRuntimes<TData = Awaited<ReturnType<typeof listFlinkRuntimes>>, TError = ListFlinkRuntimes400 | ListFlinkRuntimes500>(
 params: undefined |  ListFlinkRuntimesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkRuntimes>>,
          TError,
          Awaited<ReturnType<typeof listFlinkRuntimes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkRuntimes<TData = Awaited<ReturnType<typeof listFlinkRuntimes>>, TError = ListFlinkRuntimes400 | ListFlinkRuntimes500>(
 params?: ListFlinkRuntimesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkRuntimes>>,
          TError,
          Awaited<ReturnType<typeof listFlinkRuntimes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkRuntimes<TData = Awaited<ReturnType<typeof listFlinkRuntimes>>, TError = ListFlinkRuntimes400 | ListFlinkRuntimes500>(
 params?: ListFlinkRuntimesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取运行时列表
 */

export function useListFlinkRuntimes<TData = Awaited<ReturnType<typeof listFlinkRuntimes>>, TError = ListFlinkRuntimes400 | ListFlinkRuntimes500>(
 params?: ListFlinkRuntimesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkRuntimes>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkRuntimesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateFlinkRuntimeUrl = () => {




  return `/api/flink/runtimes`
}

/**
 * @summary 添加运行时
 */
export const createFlinkRuntime = async (flinkRuntimeRequest: FlinkRuntimeRequest, options?: RequestInit): Promise<CreateFlinkRuntime200> => {

  return customFetch<CreateFlinkRuntime200>(getCreateFlinkRuntimeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkRuntimeRequest)
  }
);}





export const getCreateFlinkRuntimeMutationOptions = <TError = CreateFlinkRuntime400 | CreateFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkRuntime>>, TError,{data: FlinkRuntimeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFlinkRuntime>>, TError,{data: FlinkRuntimeRequest}, TContext> => {

const mutationKey = ['createFlinkRuntime'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlinkRuntime>>, {data: FlinkRuntimeRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFlinkRuntime(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlinkRuntimeMutationResult = NonNullable<Awaited<ReturnType<typeof createFlinkRuntime>>>
    export type CreateFlinkRuntimeMutationBody = FlinkRuntimeRequest
    export type CreateFlinkRuntimeMutationError = CreateFlinkRuntime400 | CreateFlinkRuntime500

    /**
 * @summary 添加运行时
 */
export const useCreateFlinkRuntime = <TError = CreateFlinkRuntime400 | CreateFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkRuntime>>, TError,{data: FlinkRuntimeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlinkRuntime>>,
        TError,
        {data: FlinkRuntimeRequest},
        TContext
      > => {
      return useMutation(getCreateFlinkRuntimeMutationOptions(options), queryClient);
    }
    export const getCheckFlinkRuntimeUrl = (id: number,) => {




  return `/api/flink/runtimes/${id}:check`
}

/**
 * @summary 检查运行时连通性
 */
export const checkFlinkRuntime = async (id: number, options?: RequestInit): Promise<FlinkRuntimeCheckResponse> => {

  return customFetch<FlinkRuntimeCheckResponse>(getCheckFlinkRuntimeUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCheckFlinkRuntimeMutationOptions = <TError = CheckFlinkRuntime400 | CheckFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkFlinkRuntime>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkFlinkRuntime>>, TError,{id: number}, TContext> => {

const mutationKey = ['checkFlinkRuntime'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkFlinkRuntime>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  checkFlinkRuntime(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckFlinkRuntimeMutationResult = NonNullable<Awaited<ReturnType<typeof checkFlinkRuntime>>>

    export type CheckFlinkRuntimeMutationError = CheckFlinkRuntime400 | CheckFlinkRuntime500

    /**
 * @summary 检查运行时连通性
 */
export const useCheckFlinkRuntime = <TError = CheckFlinkRuntime400 | CheckFlinkRuntime500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkFlinkRuntime>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkFlinkRuntime>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCheckFlinkRuntimeMutationOptions(options), queryClient);
    }
