/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFlinkJarResource200,
  CreateFlinkJarResource400,
  CreateFlinkJarResource500,
  DeleteFlinkJarResource200,
  DeleteFlinkJarResource400,
  DeleteFlinkJarResource500,
  FlinkJarResourceRequest,
  FlinkJarResourceResponse,
  GetFlinkJarResource400,
  GetFlinkJarResource500,
  ListFlinkJarResources400,
  ListFlinkJarResources500,
  ListFlinkJarResourcesParams,
  PageResponseFlinkJarResourceResponse,
  UpdateFlinkJarResource200,
  UpdateFlinkJarResource400,
  UpdateFlinkJarResource500,
  UploadFlinkJarResource400,
  UploadFlinkJarResource500,
  UploadFlinkJarResourceBody,
  UploadFlinkJarResourceParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetFlinkJarResourceUrl = (id: number,) => {




  return `/api/flink/jar-resources/${id}`
}

/**
 * @summary 获取 Flink JAR 资源详情
 */
export const getFlinkJarResource = async (id: number, options?: RequestInit): Promise<FlinkJarResourceResponse> => {

  return customFetch<FlinkJarResourceResponse>(getGetFlinkJarResourceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlinkJarResourceQueryKey = (id: number,) => {
    return [
    `/api/flink/jar-resources/${id}`
    ] as const;
    }


export const getGetFlinkJarResourceQueryOptions = <TData = Awaited<ReturnType<typeof getFlinkJarResource>>, TError = GetFlinkJarResource400 | GetFlinkJarResource500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlinkJarResourceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlinkJarResource>>> = ({ signal }) => getFlinkJarResource(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlinkJarResourceQueryResult = NonNullable<Awaited<ReturnType<typeof getFlinkJarResource>>>
export type GetFlinkJarResourceQueryError = GetFlinkJarResource400 | GetFlinkJarResource500


export function useGetFlinkJarResource<TData = Awaited<ReturnType<typeof getFlinkJarResource>>, TError = GetFlinkJarResource400 | GetFlinkJarResource500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkJarResource>>,
          TError,
          Awaited<ReturnType<typeof getFlinkJarResource>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkJarResource<TData = Awaited<ReturnType<typeof getFlinkJarResource>>, TError = GetFlinkJarResource400 | GetFlinkJarResource500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlinkJarResource>>,
          TError,
          Awaited<ReturnType<typeof getFlinkJarResource>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlinkJarResource<TData = Awaited<ReturnType<typeof getFlinkJarResource>>, TError = GetFlinkJarResource400 | GetFlinkJarResource500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Flink JAR 资源详情
 */

export function useGetFlinkJarResource<TData = Awaited<ReturnType<typeof getFlinkJarResource>>, TError = GetFlinkJarResource400 | GetFlinkJarResource500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlinkJarResource>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlinkJarResourceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateFlinkJarResourceUrl = (id: number,) => {




  return `/api/flink/jar-resources/${id}`
}

/**
 * @summary 更新 Flink JAR 资源
 */
export const updateFlinkJarResource = async (id: number,
    flinkJarResourceRequest: FlinkJarResourceRequest, options?: RequestInit): Promise<UpdateFlinkJarResource200> => {

  return customFetch<UpdateFlinkJarResource200>(getUpdateFlinkJarResourceUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkJarResourceRequest)
  }
);}





export const getUpdateFlinkJarResourceMutationOptions = <TError = UpdateFlinkJarResource400 | UpdateFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJarResource>>, TError,{id: number;data: FlinkJarResourceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJarResource>>, TError,{id: number;data: FlinkJarResourceRequest}, TContext> => {

const mutationKey = ['updateFlinkJarResource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlinkJarResource>>, {id: number;data: FlinkJarResourceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlinkJarResource(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlinkJarResourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlinkJarResource>>>
    export type UpdateFlinkJarResourceMutationBody = FlinkJarResourceRequest
    export type UpdateFlinkJarResourceMutationError = UpdateFlinkJarResource400 | UpdateFlinkJarResource500

    /**
 * @summary 更新 Flink JAR 资源
 */
export const useUpdateFlinkJarResource = <TError = UpdateFlinkJarResource400 | UpdateFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlinkJarResource>>, TError,{id: number;data: FlinkJarResourceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlinkJarResource>>,
        TError,
        {id: number;data: FlinkJarResourceRequest},
        TContext
      > => {
      return useMutation(getUpdateFlinkJarResourceMutationOptions(options), queryClient);
    }
    export const getDeleteFlinkJarResourceUrl = (id: number,) => {




  return `/api/flink/jar-resources/${id}`
}

/**
 * @summary 删除 Flink JAR 资源
 */
export const deleteFlinkJarResource = async (id: number, options?: RequestInit): Promise<DeleteFlinkJarResource200> => {

  return customFetch<DeleteFlinkJarResource200>(getDeleteFlinkJarResourceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFlinkJarResourceMutationOptions = <TError = DeleteFlinkJarResource400 | DeleteFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJarResource>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJarResource>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFlinkJarResource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlinkJarResource>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFlinkJarResource(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlinkJarResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlinkJarResource>>>

    export type DeleteFlinkJarResourceMutationError = DeleteFlinkJarResource400 | DeleteFlinkJarResource500

    /**
 * @summary 删除 Flink JAR 资源
 */
export const useDeleteFlinkJarResource = <TError = DeleteFlinkJarResource400 | DeleteFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlinkJarResource>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlinkJarResource>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFlinkJarResourceMutationOptions(options), queryClient);
    }
    export const getListFlinkJarResourcesUrl = (params?: ListFlinkJarResourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/flink/jar-resources?${stringifiedParams}` : `/api/flink/jar-resources`
}

/**
 * @summary 获取 Flink JAR 资源列表
 */
export const listFlinkJarResources = async (params?: ListFlinkJarResourcesParams, options?: RequestInit): Promise<PageResponseFlinkJarResourceResponse> => {

  return customFetch<PageResponseFlinkJarResourceResponse>(getListFlinkJarResourcesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlinkJarResourcesQueryKey = (params?: ListFlinkJarResourcesParams,) => {
    return [
    `/api/flink/jar-resources`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFlinkJarResourcesQueryOptions = <TData = Awaited<ReturnType<typeof listFlinkJarResources>>, TError = ListFlinkJarResources400 | ListFlinkJarResources500>(params?: ListFlinkJarResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlinkJarResourcesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlinkJarResources>>> = ({ signal }) => listFlinkJarResources(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlinkJarResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listFlinkJarResources>>>
export type ListFlinkJarResourcesQueryError = ListFlinkJarResources400 | ListFlinkJarResources500


export function useListFlinkJarResources<TData = Awaited<ReturnType<typeof listFlinkJarResources>>, TError = ListFlinkJarResources400 | ListFlinkJarResources500>(
 params: undefined |  ListFlinkJarResourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJarResources>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJarResources>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJarResources<TData = Awaited<ReturnType<typeof listFlinkJarResources>>, TError = ListFlinkJarResources400 | ListFlinkJarResources500>(
 params?: ListFlinkJarResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlinkJarResources>>,
          TError,
          Awaited<ReturnType<typeof listFlinkJarResources>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlinkJarResources<TData = Awaited<ReturnType<typeof listFlinkJarResources>>, TError = ListFlinkJarResources400 | ListFlinkJarResources500>(
 params?: ListFlinkJarResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Flink JAR 资源列表
 */

export function useListFlinkJarResources<TData = Awaited<ReturnType<typeof listFlinkJarResources>>, TError = ListFlinkJarResources400 | ListFlinkJarResources500>(
 params?: ListFlinkJarResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlinkJarResources>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlinkJarResourcesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateFlinkJarResourceUrl = () => {




  return `/api/flink/jar-resources`
}

/**
 * @summary 创建 Flink JAR 资源
 */
export const createFlinkJarResource = async (flinkJarResourceRequest: FlinkJarResourceRequest, options?: RequestInit): Promise<CreateFlinkJarResource200> => {

  return customFetch<CreateFlinkJarResource200>(getCreateFlinkJarResourceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flinkJarResourceRequest)
  }
);}





export const getCreateFlinkJarResourceMutationOptions = <TError = CreateFlinkJarResource400 | CreateFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkJarResource>>, TError,{data: FlinkJarResourceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFlinkJarResource>>, TError,{data: FlinkJarResourceRequest}, TContext> => {

const mutationKey = ['createFlinkJarResource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlinkJarResource>>, {data: FlinkJarResourceRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFlinkJarResource(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlinkJarResourceMutationResult = NonNullable<Awaited<ReturnType<typeof createFlinkJarResource>>>
    export type CreateFlinkJarResourceMutationBody = FlinkJarResourceRequest
    export type CreateFlinkJarResourceMutationError = CreateFlinkJarResource400 | CreateFlinkJarResource500

    /**
 * @summary 创建 Flink JAR 资源
 */
export const useCreateFlinkJarResource = <TError = CreateFlinkJarResource400 | CreateFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlinkJarResource>>, TError,{data: FlinkJarResourceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlinkJarResource>>,
        TError,
        {data: FlinkJarResourceRequest},
        TContext
      > => {
      return useMutation(getCreateFlinkJarResourceMutationOptions(options), queryClient);
    }
    export const getUploadFlinkJarResourceUrl = (params?: UploadFlinkJarResourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/flink/jar-resources/upload?${stringifiedParams}` : `/api/flink/jar-resources/upload`
}

/**
 * @summary 上传 Flink JAR 资源
 */
export const uploadFlinkJarResource = async (uploadFlinkJarResourceBody?: UploadFlinkJarResourceBody,
    params?: UploadFlinkJarResourceParams, options?: RequestInit): Promise<FlinkJarResourceResponse> => {
    const formData = new FormData();
if(uploadFlinkJarResourceBody?.file !== undefined) {
 formData.append(`file`, uploadFlinkJarResourceBody.file);
 }

  return customFetch<FlinkJarResourceResponse>(getUploadFlinkJarResourceUrl(params),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getUploadFlinkJarResourceMutationOptions = <TError = UploadFlinkJarResource400 | UploadFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFlinkJarResource>>, TError,{data?: UploadFlinkJarResourceBody;params?: UploadFlinkJarResourceParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadFlinkJarResource>>, TError,{data?: UploadFlinkJarResourceBody;params?: UploadFlinkJarResourceParams}, TContext> => {

const mutationKey = ['uploadFlinkJarResource'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadFlinkJarResource>>, {data?: UploadFlinkJarResourceBody;params?: UploadFlinkJarResourceParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadFlinkJarResource(data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadFlinkJarResourceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFlinkJarResource>>>
    export type UploadFlinkJarResourceMutationBody = UploadFlinkJarResourceBody | undefined
    export type UploadFlinkJarResourceMutationError = UploadFlinkJarResource400 | UploadFlinkJarResource500

    /**
 * @summary 上传 Flink JAR 资源
 */
export const useUploadFlinkJarResource = <TError = UploadFlinkJarResource400 | UploadFlinkJarResource500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadFlinkJarResource>>, TError,{data?: UploadFlinkJarResourceBody;params?: UploadFlinkJarResourceParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadFlinkJarResource>>,
        TError,
        {data?: UploadFlinkJarResourceBody;params?: UploadFlinkJarResourceParams},
        TContext
      > => {
      return useMutation(getUploadFlinkJarResourceMutationOptions(options), queryClient);
    }
