/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFlussTopic200,
  CreateFlussTopic400,
  CreateFlussTopic500,
  DeleteFlussTopic200,
  DeleteFlussTopic400,
  DeleteFlussTopic500,
  FlussTopicRequest,
  FlussTopicResponse,
  GetFlussTopic400,
  GetFlussTopic500,
  ListFlussTopics400,
  ListFlussTopics500,
  ListFlussTopicsParams,
  PageResponseFlussTopicResponse,
  UpdateFlussTopic200,
  UpdateFlussTopic400,
  UpdateFlussTopic500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetFlussTopicUrl = (id: number,) => {




  return `/api/fluss/topics/${id}`
}

/**
 * @summary 获取 Topic 详情
 */
export const getFlussTopic = async (id: number, options?: RequestInit): Promise<FlussTopicResponse> => {

  return customFetch<FlussTopicResponse>(getGetFlussTopicUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlussTopicQueryKey = (id: number,) => {
    return [
    `/api/fluss/topics/${id}`
    ] as const;
    }


export const getGetFlussTopicQueryOptions = <TData = Awaited<ReturnType<typeof getFlussTopic>>, TError = GetFlussTopic400 | GetFlussTopic500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlussTopicQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlussTopic>>> = ({ signal }) => getFlussTopic(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlussTopicQueryResult = NonNullable<Awaited<ReturnType<typeof getFlussTopic>>>
export type GetFlussTopicQueryError = GetFlussTopic400 | GetFlussTopic500


export function useGetFlussTopic<TData = Awaited<ReturnType<typeof getFlussTopic>>, TError = GetFlussTopic400 | GetFlussTopic500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlussTopic>>,
          TError,
          Awaited<ReturnType<typeof getFlussTopic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlussTopic<TData = Awaited<ReturnType<typeof getFlussTopic>>, TError = GetFlussTopic400 | GetFlussTopic500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlussTopic>>,
          TError,
          Awaited<ReturnType<typeof getFlussTopic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlussTopic<TData = Awaited<ReturnType<typeof getFlussTopic>>, TError = GetFlussTopic400 | GetFlussTopic500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Topic 详情
 */

export function useGetFlussTopic<TData = Awaited<ReturnType<typeof getFlussTopic>>, TError = GetFlussTopic400 | GetFlussTopic500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussTopic>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlussTopicQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateFlussTopicUrl = (id: number,) => {




  return `/api/fluss/topics/${id}`
}

/**
 * @summary 更新 Topic
 */
export const updateFlussTopic = async (id: number,
    flussTopicRequest: FlussTopicRequest, options?: RequestInit): Promise<UpdateFlussTopic200> => {

  return customFetch<UpdateFlussTopic200>(getUpdateFlussTopicUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flussTopicRequest)
  }
);}





export const getUpdateFlussTopicMutationOptions = <TError = UpdateFlussTopic400 | UpdateFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlussTopic>>, TError,{id: number;data: FlussTopicRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFlussTopic>>, TError,{id: number;data: FlussTopicRequest}, TContext> => {

const mutationKey = ['updateFlussTopic'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlussTopic>>, {id: number;data: FlussTopicRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlussTopic(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlussTopicMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlussTopic>>>
    export type UpdateFlussTopicMutationBody = FlussTopicRequest
    export type UpdateFlussTopicMutationError = UpdateFlussTopic400 | UpdateFlussTopic500

    /**
 * @summary 更新 Topic
 */
export const useUpdateFlussTopic = <TError = UpdateFlussTopic400 | UpdateFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlussTopic>>, TError,{id: number;data: FlussTopicRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlussTopic>>,
        TError,
        {id: number;data: FlussTopicRequest},
        TContext
      > => {
      return useMutation(getUpdateFlussTopicMutationOptions(options), queryClient);
    }
    export const getDeleteFlussTopicUrl = (id: number,) => {




  return `/api/fluss/topics/${id}`
}

/**
 * @summary 删除 Topic
 */
export const deleteFlussTopic = async (id: number, options?: RequestInit): Promise<DeleteFlussTopic200> => {

  return customFetch<DeleteFlussTopic200>(getDeleteFlussTopicUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFlussTopicMutationOptions = <TError = DeleteFlussTopic400 | DeleteFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlussTopic>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlussTopic>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFlussTopic'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlussTopic>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFlussTopic(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlussTopicMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlussTopic>>>

    export type DeleteFlussTopicMutationError = DeleteFlussTopic400 | DeleteFlussTopic500

    /**
 * @summary 删除 Topic
 */
export const useDeleteFlussTopic = <TError = DeleteFlussTopic400 | DeleteFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlussTopic>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlussTopic>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFlussTopicMutationOptions(options), queryClient);
    }
    export const getListFlussTopicsUrl = (params?: ListFlussTopicsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/fluss/topics?${stringifiedParams}` : `/api/fluss/topics`
}

/**
 * @summary 获取 Topic 列表
 */
export const listFlussTopics = async (params?: ListFlussTopicsParams, options?: RequestInit): Promise<PageResponseFlussTopicResponse> => {

  return customFetch<PageResponseFlussTopicResponse>(getListFlussTopicsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlussTopicsQueryKey = (params?: ListFlussTopicsParams,) => {
    return [
    `/api/fluss/topics`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFlussTopicsQueryOptions = <TData = Awaited<ReturnType<typeof listFlussTopics>>, TError = ListFlussTopics400 | ListFlussTopics500>(params?: ListFlussTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlussTopicsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlussTopics>>> = ({ signal }) => listFlussTopics(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlussTopicsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlussTopics>>>
export type ListFlussTopicsQueryError = ListFlussTopics400 | ListFlussTopics500


export function useListFlussTopics<TData = Awaited<ReturnType<typeof listFlussTopics>>, TError = ListFlussTopics400 | ListFlussTopics500>(
 params: undefined |  ListFlussTopicsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlussTopics>>,
          TError,
          Awaited<ReturnType<typeof listFlussTopics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlussTopics<TData = Awaited<ReturnType<typeof listFlussTopics>>, TError = ListFlussTopics400 | ListFlussTopics500>(
 params?: ListFlussTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlussTopics>>,
          TError,
          Awaited<ReturnType<typeof listFlussTopics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlussTopics<TData = Awaited<ReturnType<typeof listFlussTopics>>, TError = ListFlussTopics400 | ListFlussTopics500>(
 params?: ListFlussTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Topic 列表
 */

export function useListFlussTopics<TData = Awaited<ReturnType<typeof listFlussTopics>>, TError = ListFlussTopics400 | ListFlussTopics500>(
 params?: ListFlussTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussTopics>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlussTopicsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateFlussTopicUrl = () => {




  return `/api/fluss/topics`
}

/**
 * @summary 创建 Topic
 */
export const createFlussTopic = async (flussTopicRequest: FlussTopicRequest, options?: RequestInit): Promise<CreateFlussTopic200> => {

  return customFetch<CreateFlussTopic200>(getCreateFlussTopicUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flussTopicRequest)
  }
);}





export const getCreateFlussTopicMutationOptions = <TError = CreateFlussTopic400 | CreateFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlussTopic>>, TError,{data: FlussTopicRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFlussTopic>>, TError,{data: FlussTopicRequest}, TContext> => {

const mutationKey = ['createFlussTopic'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlussTopic>>, {data: FlussTopicRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFlussTopic(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlussTopicMutationResult = NonNullable<Awaited<ReturnType<typeof createFlussTopic>>>
    export type CreateFlussTopicMutationBody = FlussTopicRequest
    export type CreateFlussTopicMutationError = CreateFlussTopic400 | CreateFlussTopic500

    /**
 * @summary 创建 Topic
 */
export const useCreateFlussTopic = <TError = CreateFlussTopic400 | CreateFlussTopic500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlussTopic>>, TError,{data: FlussTopicRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlussTopic>>,
        TError,
        {data: FlussTopicRequest},
        TContext
      > => {
      return useMutation(getCreateFlussTopicMutationOptions(options), queryClient);
    }
