/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckFlussCluster400,
  CheckFlussCluster500,
  CreateFlussCluster200,
  CreateFlussCluster400,
  CreateFlussCluster500,
  DeleteFlussCluster200,
  DeleteFlussCluster400,
  DeleteFlussCluster500,
  FlussClusterRequest,
  FlussClusterResponse,
  GetFlussCluster400,
  GetFlussCluster500,
  ListFlussClusters400,
  ListFlussClusters500,
  ListFlussClustersParams,
  PageResponseFlussClusterResponse,
  UpdateFlussCluster200,
  UpdateFlussCluster400,
  UpdateFlussCluster500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetFlussClusterUrl = (id: number,) => {




  return `/api/fluss/clusters/${id}`
}

/**
 * @summary 获取 Fluss 集群详情
 */
export const getFlussCluster = async (id: number, options?: RequestInit): Promise<FlussClusterResponse> => {

  return customFetch<FlussClusterResponse>(getGetFlussClusterUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFlussClusterQueryKey = (id: number,) => {
    return [
    `/api/fluss/clusters/${id}`
    ] as const;
    }


export const getGetFlussClusterQueryOptions = <TData = Awaited<ReturnType<typeof getFlussCluster>>, TError = GetFlussCluster400 | GetFlussCluster500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlussClusterQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlussCluster>>> = ({ signal }) => getFlussCluster(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlussClusterQueryResult = NonNullable<Awaited<ReturnType<typeof getFlussCluster>>>
export type GetFlussClusterQueryError = GetFlussCluster400 | GetFlussCluster500


export function useGetFlussCluster<TData = Awaited<ReturnType<typeof getFlussCluster>>, TError = GetFlussCluster400 | GetFlussCluster500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlussCluster>>,
          TError,
          Awaited<ReturnType<typeof getFlussCluster>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlussCluster<TData = Awaited<ReturnType<typeof getFlussCluster>>, TError = GetFlussCluster400 | GetFlussCluster500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlussCluster>>,
          TError,
          Awaited<ReturnType<typeof getFlussCluster>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlussCluster<TData = Awaited<ReturnType<typeof getFlussCluster>>, TError = GetFlussCluster400 | GetFlussCluster500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Fluss 集群详情
 */

export function useGetFlussCluster<TData = Awaited<ReturnType<typeof getFlussCluster>>, TError = GetFlussCluster400 | GetFlussCluster500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlussCluster>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlussClusterQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateFlussClusterUrl = (id: number,) => {




  return `/api/fluss/clusters/${id}`
}

/**
 * @summary 更新 Fluss 集群
 */
export const updateFlussCluster = async (id: number,
    flussClusterRequest: FlussClusterRequest, options?: RequestInit): Promise<UpdateFlussCluster200> => {

  return customFetch<UpdateFlussCluster200>(getUpdateFlussClusterUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flussClusterRequest)
  }
);}





export const getUpdateFlussClusterMutationOptions = <TError = UpdateFlussCluster400 | UpdateFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlussCluster>>, TError,{id: number;data: FlussClusterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFlussCluster>>, TError,{id: number;data: FlussClusterRequest}, TContext> => {

const mutationKey = ['updateFlussCluster'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlussCluster>>, {id: number;data: FlussClusterRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlussCluster(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlussClusterMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlussCluster>>>
    export type UpdateFlussClusterMutationBody = FlussClusterRequest
    export type UpdateFlussClusterMutationError = UpdateFlussCluster400 | UpdateFlussCluster500

    /**
 * @summary 更新 Fluss 集群
 */
export const useUpdateFlussCluster = <TError = UpdateFlussCluster400 | UpdateFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlussCluster>>, TError,{id: number;data: FlussClusterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlussCluster>>,
        TError,
        {id: number;data: FlussClusterRequest},
        TContext
      > => {
      return useMutation(getUpdateFlussClusterMutationOptions(options), queryClient);
    }
    export const getDeleteFlussClusterUrl = (id: number,) => {




  return `/api/fluss/clusters/${id}`
}

/**
 * @summary 删除 Fluss 集群
 */
export const deleteFlussCluster = async (id: number, options?: RequestInit): Promise<DeleteFlussCluster200> => {

  return customFetch<DeleteFlussCluster200>(getDeleteFlussClusterUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFlussClusterMutationOptions = <TError = DeleteFlussCluster400 | DeleteFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlussCluster>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlussCluster>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteFlussCluster'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlussCluster>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteFlussCluster(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlussClusterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlussCluster>>>

    export type DeleteFlussClusterMutationError = DeleteFlussCluster400 | DeleteFlussCluster500

    /**
 * @summary 删除 Fluss 集群
 */
export const useDeleteFlussCluster = <TError = DeleteFlussCluster400 | DeleteFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlussCluster>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlussCluster>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteFlussClusterMutationOptions(options), queryClient);
    }
    export const getListFlussClustersUrl = (params?: ListFlussClustersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/fluss/clusters?${stringifiedParams}` : `/api/fluss/clusters`
}

/**
 * @summary 获取 Fluss 集群列表
 */
export const listFlussClusters = async (params?: ListFlussClustersParams, options?: RequestInit): Promise<PageResponseFlussClusterResponse> => {

  return customFetch<PageResponseFlussClusterResponse>(getListFlussClustersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFlussClustersQueryKey = (params?: ListFlussClustersParams,) => {
    return [
    `/api/fluss/clusters`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFlussClustersQueryOptions = <TData = Awaited<ReturnType<typeof listFlussClusters>>, TError = ListFlussClusters400 | ListFlussClusters500>(params?: ListFlussClustersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlussClustersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlussClusters>>> = ({ signal }) => listFlussClusters(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlussClustersQueryResult = NonNullable<Awaited<ReturnType<typeof listFlussClusters>>>
export type ListFlussClustersQueryError = ListFlussClusters400 | ListFlussClusters500


export function useListFlussClusters<TData = Awaited<ReturnType<typeof listFlussClusters>>, TError = ListFlussClusters400 | ListFlussClusters500>(
 params: undefined |  ListFlussClustersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlussClusters>>,
          TError,
          Awaited<ReturnType<typeof listFlussClusters>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlussClusters<TData = Awaited<ReturnType<typeof listFlussClusters>>, TError = ListFlussClusters400 | ListFlussClusters500>(
 params?: ListFlussClustersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlussClusters>>,
          TError,
          Awaited<ReturnType<typeof listFlussClusters>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlussClusters<TData = Awaited<ReturnType<typeof listFlussClusters>>, TError = ListFlussClusters400 | ListFlussClusters500>(
 params?: ListFlussClustersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Fluss 集群列表
 */

export function useListFlussClusters<TData = Awaited<ReturnType<typeof listFlussClusters>>, TError = ListFlussClusters400 | ListFlussClusters500>(
 params?: ListFlussClustersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlussClusters>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlussClustersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateFlussClusterUrl = () => {




  return `/api/fluss/clusters`
}

/**
 * @summary 创建 Fluss 集群
 */
export const createFlussCluster = async (flussClusterRequest: FlussClusterRequest, options?: RequestInit): Promise<CreateFlussCluster200> => {

  return customFetch<CreateFlussCluster200>(getCreateFlussClusterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(flussClusterRequest)
  }
);}





export const getCreateFlussClusterMutationOptions = <TError = CreateFlussCluster400 | CreateFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlussCluster>>, TError,{data: FlussClusterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFlussCluster>>, TError,{data: FlussClusterRequest}, TContext> => {

const mutationKey = ['createFlussCluster'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlussCluster>>, {data: FlussClusterRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFlussCluster(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlussClusterMutationResult = NonNullable<Awaited<ReturnType<typeof createFlussCluster>>>
    export type CreateFlussClusterMutationBody = FlussClusterRequest
    export type CreateFlussClusterMutationError = CreateFlussCluster400 | CreateFlussCluster500

    /**
 * @summary 创建 Fluss 集群
 */
export const useCreateFlussCluster = <TError = CreateFlussCluster400 | CreateFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlussCluster>>, TError,{data: FlussClusterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlussCluster>>,
        TError,
        {data: FlussClusterRequest},
        TContext
      > => {
      return useMutation(getCreateFlussClusterMutationOptions(options), queryClient);
    }
    export const getCheckFlussClusterUrl = (id: number,) => {




  return `/api/fluss/clusters/${id}:check`
}

/**
 * @summary 检查 Fluss 集群连通性
 */
export const checkFlussCluster = async (id: number, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getCheckFlussClusterUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCheckFlussClusterMutationOptions = <TError = CheckFlussCluster400 | CheckFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkFlussCluster>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkFlussCluster>>, TError,{id: number}, TContext> => {

const mutationKey = ['checkFlussCluster'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkFlussCluster>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  checkFlussCluster(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckFlussClusterMutationResult = NonNullable<Awaited<ReturnType<typeof checkFlussCluster>>>

    export type CheckFlussClusterMutationError = CheckFlussCluster400 | CheckFlussCluster500

    /**
 * @summary 检查 Fluss 集群连通性
 */
export const useCheckFlussCluster = <TError = CheckFlussCluster400 | CheckFlussCluster500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkFlussCluster>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkFlussCluster>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCheckFlussClusterMutationOptions(options), queryClient);
    }
