/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetImageRegistryConfig400,
  GetImageRegistryConfig500,
  ImageRegistryConfigRequest,
  ImageRegistryConfigResponse,
  TestImageRegistryConfig400,
  TestImageRegistryConfig500,
  UpdateImageRegistryConfig400,
  UpdateImageRegistryConfig500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetImageRegistryConfigUrl = () => {




  return `/api/image-registry`
}

/**
 * @summary 获取当前组织镜像仓库配置
 */
export const getImageRegistryConfig = async ( options?: RequestInit): Promise<ImageRegistryConfigResponse> => {

  return customFetch<ImageRegistryConfigResponse>(getGetImageRegistryConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetImageRegistryConfigQueryKey = () => {
    return [
    `/api/image-registry`
    ] as const;
    }


export const getGetImageRegistryConfigQueryOptions = <TData = Awaited<ReturnType<typeof getImageRegistryConfig>>, TError = GetImageRegistryConfig400 | GetImageRegistryConfig500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetImageRegistryConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImageRegistryConfig>>> = ({ signal }) => getImageRegistryConfig({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetImageRegistryConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getImageRegistryConfig>>>
export type GetImageRegistryConfigQueryError = GetImageRegistryConfig400 | GetImageRegistryConfig500


export function useGetImageRegistryConfig<TData = Awaited<ReturnType<typeof getImageRegistryConfig>>, TError = GetImageRegistryConfig400 | GetImageRegistryConfig500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImageRegistryConfig>>,
          TError,
          Awaited<ReturnType<typeof getImageRegistryConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImageRegistryConfig<TData = Awaited<ReturnType<typeof getImageRegistryConfig>>, TError = GetImageRegistryConfig400 | GetImageRegistryConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImageRegistryConfig>>,
          TError,
          Awaited<ReturnType<typeof getImageRegistryConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImageRegistryConfig<TData = Awaited<ReturnType<typeof getImageRegistryConfig>>, TError = GetImageRegistryConfig400 | GetImageRegistryConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前组织镜像仓库配置
 */

export function useGetImageRegistryConfig<TData = Awaited<ReturnType<typeof getImageRegistryConfig>>, TError = GetImageRegistryConfig400 | GetImageRegistryConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageRegistryConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetImageRegistryConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateImageRegistryConfigUrl = () => {




  return `/api/image-registry`
}

/**
 * @summary 保存当前组织镜像仓库配置
 */
export const updateImageRegistryConfig = async (imageRegistryConfigRequest: ImageRegistryConfigRequest, options?: RequestInit): Promise<ImageRegistryConfigResponse> => {

  return customFetch<ImageRegistryConfigResponse>(getUpdateImageRegistryConfigUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(imageRegistryConfigRequest)
  }
);}





export const getUpdateImageRegistryConfigMutationOptions = <TError = UpdateImageRegistryConfig400 | UpdateImageRegistryConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext> => {

const mutationKey = ['updateImageRegistryConfig'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateImageRegistryConfig>>, {data: ImageRegistryConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateImageRegistryConfig(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateImageRegistryConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateImageRegistryConfig>>>
    export type UpdateImageRegistryConfigMutationBody = ImageRegistryConfigRequest
    export type UpdateImageRegistryConfigMutationError = UpdateImageRegistryConfig400 | UpdateImageRegistryConfig500

    /**
 * @summary 保存当前组织镜像仓库配置
 */
export const useUpdateImageRegistryConfig = <TError = UpdateImageRegistryConfig400 | UpdateImageRegistryConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateImageRegistryConfig>>,
        TError,
        {data: ImageRegistryConfigRequest},
        TContext
      > => {
      return useMutation(getUpdateImageRegistryConfigMutationOptions(options), queryClient);
    }
    export const getTestImageRegistryConfigUrl = () => {




  return `/api/image-registry/test`
}

/**
 * @summary 测试镜像仓库配置
 */
export const testImageRegistryConfig = async (imageRegistryConfigRequest: ImageRegistryConfigRequest, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getTestImageRegistryConfigUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(imageRegistryConfigRequest)
  }
);}





export const getTestImageRegistryConfigMutationOptions = <TError = TestImageRegistryConfig400 | TestImageRegistryConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof testImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext> => {

const mutationKey = ['testImageRegistryConfig'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testImageRegistryConfig>>, {data: ImageRegistryConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  testImageRegistryConfig(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestImageRegistryConfigMutationResult = NonNullable<Awaited<ReturnType<typeof testImageRegistryConfig>>>
    export type TestImageRegistryConfigMutationBody = ImageRegistryConfigRequest
    export type TestImageRegistryConfigMutationError = TestImageRegistryConfig400 | TestImageRegistryConfig500

    /**
 * @summary 测试镜像仓库配置
 */
export const useTestImageRegistryConfig = <TError = TestImageRegistryConfig400 | TestImageRegistryConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testImageRegistryConfig>>, TError,{data: ImageRegistryConfigRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testImageRegistryConfig>>,
        TError,
        {data: ImageRegistryConfigRequest},
        TContext
      > => {
      return useMutation(getTestImageRegistryConfigMutationOptions(options), queryClient);
    }
