/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetModelProviderConfig400,
  GetModelProviderConfig500,
  ModelProviderConfigRequest,
  ModelProviderConfigResponse,
  TestModelProviderConfig400,
  TestModelProviderConfig500,
  UpdateModelProviderConfig400,
  UpdateModelProviderConfig500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetModelProviderConfigUrl = () => {




  return `/api/model-provider`
}

/**
 * @summary 获取当前组织模型提供商配置
 */
export const getModelProviderConfig = async ( options?: RequestInit): Promise<ModelProviderConfigResponse> => {

  return customFetch<ModelProviderConfigResponse>(getGetModelProviderConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModelProviderConfigQueryKey = () => {
    return [
    `/api/model-provider`
    ] as const;
    }


export const getGetModelProviderConfigQueryOptions = <TData = Awaited<ReturnType<typeof getModelProviderConfig>>, TError = GetModelProviderConfig400 | GetModelProviderConfig500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelProviderConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelProviderConfig>>> = ({ signal }) => getModelProviderConfig({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelProviderConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getModelProviderConfig>>>
export type GetModelProviderConfigQueryError = GetModelProviderConfig400 | GetModelProviderConfig500


export function useGetModelProviderConfig<TData = Awaited<ReturnType<typeof getModelProviderConfig>>, TError = GetModelProviderConfig400 | GetModelProviderConfig500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelProviderConfig>>,
          TError,
          Awaited<ReturnType<typeof getModelProviderConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelProviderConfig<TData = Awaited<ReturnType<typeof getModelProviderConfig>>, TError = GetModelProviderConfig400 | GetModelProviderConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelProviderConfig>>,
          TError,
          Awaited<ReturnType<typeof getModelProviderConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelProviderConfig<TData = Awaited<ReturnType<typeof getModelProviderConfig>>, TError = GetModelProviderConfig400 | GetModelProviderConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前组织模型提供商配置
 */

export function useGetModelProviderConfig<TData = Awaited<ReturnType<typeof getModelProviderConfig>>, TError = GetModelProviderConfig400 | GetModelProviderConfig500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelProviderConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelProviderConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateModelProviderConfigUrl = () => {




  return `/api/model-provider`
}

/**
 * @summary 保存当前组织模型提供商配置
 */
export const updateModelProviderConfig = async (modelProviderConfigRequest: ModelProviderConfigRequest, options?: RequestInit): Promise<ModelProviderConfigResponse> => {

  return customFetch<ModelProviderConfigResponse>(getUpdateModelProviderConfigUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modelProviderConfigRequest)
  }
);}





export const getUpdateModelProviderConfigMutationOptions = <TError = UpdateModelProviderConfig400 | UpdateModelProviderConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext> => {

const mutationKey = ['updateModelProviderConfig'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateModelProviderConfig>>, {data: ModelProviderConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateModelProviderConfig(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateModelProviderConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateModelProviderConfig>>>
    export type UpdateModelProviderConfigMutationBody = ModelProviderConfigRequest
    export type UpdateModelProviderConfigMutationError = UpdateModelProviderConfig400 | UpdateModelProviderConfig500

    /**
 * @summary 保存当前组织模型提供商配置
 */
export const useUpdateModelProviderConfig = <TError = UpdateModelProviderConfig400 | UpdateModelProviderConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateModelProviderConfig>>,
        TError,
        {data: ModelProviderConfigRequest},
        TContext
      > => {
      return useMutation(getUpdateModelProviderConfigMutationOptions(options), queryClient);
    }
    export const getTestModelProviderConfigUrl = () => {




  return `/api/model-provider/test`
}

/**
 * @summary 测试模型提供商配置
 */
export const testModelProviderConfig = async (modelProviderConfigRequest: ModelProviderConfigRequest, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getTestModelProviderConfigUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modelProviderConfigRequest)
  }
);}





export const getTestModelProviderConfigMutationOptions = <TError = TestModelProviderConfig400 | TestModelProviderConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof testModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext> => {

const mutationKey = ['testModelProviderConfig'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testModelProviderConfig>>, {data: ModelProviderConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  testModelProviderConfig(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestModelProviderConfigMutationResult = NonNullable<Awaited<ReturnType<typeof testModelProviderConfig>>>
    export type TestModelProviderConfigMutationBody = ModelProviderConfigRequest
    export type TestModelProviderConfigMutationError = TestModelProviderConfig400 | TestModelProviderConfig500

    /**
 * @summary 测试模型提供商配置
 */
export const useTestModelProviderConfig = <TError = TestModelProviderConfig400 | TestModelProviderConfig500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testModelProviderConfig>>, TError,{data: ModelProviderConfigRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testModelProviderConfig>>,
        TError,
        {data: ModelProviderConfigRequest},
        TContext
      > => {
      return useMutation(getTestModelProviderConfigMutationOptions(options), queryClient);
    }
