/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateNotificationChannel400,
  CreateNotificationChannel500,
  DeleteNotificationChannel200,
  DeleteNotificationChannel400,
  DeleteNotificationChannel500,
  ListNotificationChannels400,
  ListNotificationChannels500,
  ListNotificationChannelsParams,
  NotificationChannelRequest,
  NotificationChannelResponse,
  PageResponseNotificationChannelResponse,
  TestNotificationChannel400,
  TestNotificationChannel500,
  UpdateNotificationChannel400,
  UpdateNotificationChannel500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getUpdateNotificationChannelUrl = (id: number,) => {




  return `/api/notification-channels/${id}`
}

/**
 * @summary 更新告警渠道
 */
export const updateNotificationChannel = async (id: number,
    notificationChannelRequest: NotificationChannelRequest, options?: RequestInit): Promise<NotificationChannelResponse> => {

  return customFetch<NotificationChannelResponse>(getUpdateNotificationChannelUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(notificationChannelRequest)
  }
);}





export const getUpdateNotificationChannelMutationOptions = <TError = UpdateNotificationChannel400 | UpdateNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationChannel>>, TError,{id: number;data: NotificationChannelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateNotificationChannel>>, TError,{id: number;data: NotificationChannelRequest}, TContext> => {

const mutationKey = ['updateNotificationChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotificationChannel>>, {id: number;data: NotificationChannelRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateNotificationChannel(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateNotificationChannelMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotificationChannel>>>
    export type UpdateNotificationChannelMutationBody = NotificationChannelRequest
    export type UpdateNotificationChannelMutationError = UpdateNotificationChannel400 | UpdateNotificationChannel500

    /**
 * @summary 更新告警渠道
 */
export const useUpdateNotificationChannel = <TError = UpdateNotificationChannel400 | UpdateNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationChannel>>, TError,{id: number;data: NotificationChannelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNotificationChannel>>,
        TError,
        {id: number;data: NotificationChannelRequest},
        TContext
      > => {
      return useMutation(getUpdateNotificationChannelMutationOptions(options), queryClient);
    }
    export const getDeleteNotificationChannelUrl = (id: number,) => {




  return `/api/notification-channels/${id}`
}

/**
 * @summary 删除告警渠道
 */
export const deleteNotificationChannel = async (id: number, options?: RequestInit): Promise<DeleteNotificationChannel200> => {

  return customFetch<DeleteNotificationChannel200>(getDeleteNotificationChannelUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteNotificationChannelMutationOptions = <TError = DeleteNotificationChannel400 | DeleteNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotificationChannel>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotificationChannel>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteNotificationChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotificationChannel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteNotificationChannel(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNotificationChannelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotificationChannel>>>

    export type DeleteNotificationChannelMutationError = DeleteNotificationChannel400 | DeleteNotificationChannel500

    /**
 * @summary 删除告警渠道
 */
export const useDeleteNotificationChannel = <TError = DeleteNotificationChannel400 | DeleteNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotificationChannel>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNotificationChannel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteNotificationChannelMutationOptions(options), queryClient);
    }
    export const getListNotificationChannelsUrl = (params?: ListNotificationChannelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/notification-channels?${stringifiedParams}` : `/api/notification-channels`
}

/**
 * @summary 获取当前组织告警渠道列表
 */
export const listNotificationChannels = async (params?: ListNotificationChannelsParams, options?: RequestInit): Promise<PageResponseNotificationChannelResponse> => {

  return customFetch<PageResponseNotificationChannelResponse>(getListNotificationChannelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListNotificationChannelsQueryKey = (params?: ListNotificationChannelsParams,) => {
    return [
    `/api/notification-channels`, ...(params ? [params] : [])
    ] as const;
    }


export const getListNotificationChannelsQueryOptions = <TData = Awaited<ReturnType<typeof listNotificationChannels>>, TError = ListNotificationChannels400 | ListNotificationChannels500>(params?: ListNotificationChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationChannelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotificationChannels>>> = ({ signal }) => listNotificationChannels(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNotificationChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof listNotificationChannels>>>
export type ListNotificationChannelsQueryError = ListNotificationChannels400 | ListNotificationChannels500


export function useListNotificationChannels<TData = Awaited<ReturnType<typeof listNotificationChannels>>, TError = ListNotificationChannels400 | ListNotificationChannels500>(
 params: undefined |  ListNotificationChannelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNotificationChannels>>,
          TError,
          Awaited<ReturnType<typeof listNotificationChannels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationChannels<TData = Awaited<ReturnType<typeof listNotificationChannels>>, TError = ListNotificationChannels400 | ListNotificationChannels500>(
 params?: ListNotificationChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNotificationChannels>>,
          TError,
          Awaited<ReturnType<typeof listNotificationChannels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationChannels<TData = Awaited<ReturnType<typeof listNotificationChannels>>, TError = ListNotificationChannels400 | ListNotificationChannels500>(
 params?: ListNotificationChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前组织告警渠道列表
 */

export function useListNotificationChannels<TData = Awaited<ReturnType<typeof listNotificationChannels>>, TError = ListNotificationChannels400 | ListNotificationChannels500>(
 params?: ListNotificationChannelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotificationChannels>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListNotificationChannelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateNotificationChannelUrl = () => {




  return `/api/notification-channels`
}

/**
 * @summary 创建告警渠道
 */
export const createNotificationChannel = async (notificationChannelRequest: NotificationChannelRequest, options?: RequestInit): Promise<NotificationChannelResponse> => {

  return customFetch<NotificationChannelResponse>(getCreateNotificationChannelUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(notificationChannelRequest)
  }
);}





export const getCreateNotificationChannelMutationOptions = <TError = CreateNotificationChannel400 | CreateNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotificationChannel>>, TError,{data: NotificationChannelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNotificationChannel>>, TError,{data: NotificationChannelRequest}, TContext> => {

const mutationKey = ['createNotificationChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNotificationChannel>>, {data: NotificationChannelRequest}> = (props) => {
          const {data} = props ?? {};

          return  createNotificationChannel(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateNotificationChannelMutationResult = NonNullable<Awaited<ReturnType<typeof createNotificationChannel>>>
    export type CreateNotificationChannelMutationBody = NotificationChannelRequest
    export type CreateNotificationChannelMutationError = CreateNotificationChannel400 | CreateNotificationChannel500

    /**
 * @summary 创建告警渠道
 */
export const useCreateNotificationChannel = <TError = CreateNotificationChannel400 | CreateNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotificationChannel>>, TError,{data: NotificationChannelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNotificationChannel>>,
        TError,
        {data: NotificationChannelRequest},
        TContext
      > => {
      return useMutation(getCreateNotificationChannelMutationOptions(options), queryClient);
    }
    export const getTestNotificationChannelUrl = (id: number,) => {




  return `/api/notification-channels/${id}:test`
}

/**
 * @summary 发送测试告警
 */
export const testNotificationChannel = async (id: number, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getTestNotificationChannelUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTestNotificationChannelMutationOptions = <TError = TestNotificationChannel400 | TestNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testNotificationChannel>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof testNotificationChannel>>, TError,{id: number}, TContext> => {

const mutationKey = ['testNotificationChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testNotificationChannel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  testNotificationChannel(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestNotificationChannelMutationResult = NonNullable<Awaited<ReturnType<typeof testNotificationChannel>>>

    export type TestNotificationChannelMutationError = TestNotificationChannel400 | TestNotificationChannel500

    /**
 * @summary 发送测试告警
 */
export const useTestNotificationChannel = <TError = TestNotificationChannel400 | TestNotificationChannel500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testNotificationChannel>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testNotificationChannel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getTestNotificationChannelMutationOptions(options), queryClient);
    }
