/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckPaimonCatalog400,
  CheckPaimonCatalog500,
  CreatePaimonCatalog200,
  CreatePaimonCatalog400,
  CreatePaimonCatalog500,
  DeletePaimonCatalog200,
  DeletePaimonCatalog400,
  DeletePaimonCatalog500,
  GetPaimonCatalog400,
  GetPaimonCatalog500,
  GetPaimonTableDefinition400,
  GetPaimonTableDefinition500,
  GetPaimonTableDefinitionParams,
  GetPaimonTableFileContent400,
  GetPaimonTableFileContent500,
  GetPaimonTableFileContentParams,
  GetPaimonTableSchema400,
  GetPaimonTableSchema500,
  GetPaimonTableSchemaParams,
  ListPaimonCatalogs400,
  ListPaimonCatalogs500,
  ListPaimonCatalogsParams,
  ListPaimonDatabases400,
  ListPaimonDatabases500,
  ListPaimonDatabasesParams,
  ListPaimonTableFiles400,
  ListPaimonTableFiles500,
  ListPaimonTableFilesParams,
  ListPaimonTableSnapshots400,
  ListPaimonTableSnapshots500,
  ListPaimonTables400,
  ListPaimonTables500,
  ListPaimonTablesParams,
  PageResponsePaimonCatalogResponse,
  PaimonCatalogDetailResponse,
  PaimonCatalogRequest,
  PaimonDatabaseResponse,
  PaimonTableDefinitionResponse,
  PaimonTableFileContentResponse,
  PaimonTableFilesResponse,
  PaimonTablePreviewResponse,
  PaimonTableResponse,
  PaimonTableSchemaResponse,
  PaimonTableSnapshotsResponse,
  PreviewPaimonTable400,
  PreviewPaimonTable500,
  PreviewPaimonTableParams,
  UpdatePaimonCatalog200,
  UpdatePaimonCatalog400,
  UpdatePaimonCatalog500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPaimonCatalogUrl = (id: number,) => {




  return `/api/paimon/catalogs/${id}`
}

/**
 * @summary 获取 Catalog 详情
 */
export const getPaimonCatalog = async (id: number, options?: RequestInit): Promise<PaimonCatalogDetailResponse> => {

  return customFetch<PaimonCatalogDetailResponse>(getGetPaimonCatalogUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPaimonCatalogQueryKey = (id: number,) => {
    return [
    `/api/paimon/catalogs/${id}`
    ] as const;
    }


export const getGetPaimonCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getPaimonCatalog>>, TError = GetPaimonCatalog400 | GetPaimonCatalog500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaimonCatalogQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaimonCatalog>>> = ({ signal }) => getPaimonCatalog(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaimonCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getPaimonCatalog>>>
export type GetPaimonCatalogQueryError = GetPaimonCatalog400 | GetPaimonCatalog500


export function useGetPaimonCatalog<TData = Awaited<ReturnType<typeof getPaimonCatalog>>, TError = GetPaimonCatalog400 | GetPaimonCatalog500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPaimonCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonCatalog<TData = Awaited<ReturnType<typeof getPaimonCatalog>>, TError = GetPaimonCatalog400 | GetPaimonCatalog500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPaimonCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonCatalog<TData = Awaited<ReturnType<typeof getPaimonCatalog>>, TError = GetPaimonCatalog400 | GetPaimonCatalog500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Catalog 详情
 */

export function useGetPaimonCatalog<TData = Awaited<ReturnType<typeof getPaimonCatalog>>, TError = GetPaimonCatalog400 | GetPaimonCatalog500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaimonCatalogQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdatePaimonCatalogUrl = (id: number,) => {




  return `/api/paimon/catalogs/${id}`
}

/**
 * @summary 更新 Catalog
 */
export const updatePaimonCatalog = async (id: number,
    paimonCatalogRequest: PaimonCatalogRequest, options?: RequestInit): Promise<UpdatePaimonCatalog200> => {

  return customFetch<UpdatePaimonCatalog200>(getUpdatePaimonCatalogUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(paimonCatalogRequest)
  }
);}





export const getUpdatePaimonCatalogMutationOptions = <TError = UpdatePaimonCatalog400 | UpdatePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePaimonCatalog>>, TError,{id: number;data: PaimonCatalogRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePaimonCatalog>>, TError,{id: number;data: PaimonCatalogRequest}, TContext> => {

const mutationKey = ['updatePaimonCatalog'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePaimonCatalog>>, {id: number;data: PaimonCatalogRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePaimonCatalog(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePaimonCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof updatePaimonCatalog>>>
    export type UpdatePaimonCatalogMutationBody = PaimonCatalogRequest
    export type UpdatePaimonCatalogMutationError = UpdatePaimonCatalog400 | UpdatePaimonCatalog500

    /**
 * @summary 更新 Catalog
 */
export const useUpdatePaimonCatalog = <TError = UpdatePaimonCatalog400 | UpdatePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePaimonCatalog>>, TError,{id: number;data: PaimonCatalogRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePaimonCatalog>>,
        TError,
        {id: number;data: PaimonCatalogRequest},
        TContext
      > => {
      return useMutation(getUpdatePaimonCatalogMutationOptions(options), queryClient);
    }
    export const getDeletePaimonCatalogUrl = (id: number,) => {




  return `/api/paimon/catalogs/${id}`
}

/**
 * @summary 删除 Catalog
 */
export const deletePaimonCatalog = async (id: number, options?: RequestInit): Promise<DeletePaimonCatalog200> => {

  return customFetch<DeletePaimonCatalog200>(getDeletePaimonCatalogUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePaimonCatalogMutationOptions = <TError = DeletePaimonCatalog400 | DeletePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePaimonCatalog>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePaimonCatalog>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePaimonCatalog'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePaimonCatalog>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePaimonCatalog(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePaimonCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof deletePaimonCatalog>>>

    export type DeletePaimonCatalogMutationError = DeletePaimonCatalog400 | DeletePaimonCatalog500

    /**
 * @summary 删除 Catalog
 */
export const useDeletePaimonCatalog = <TError = DeletePaimonCatalog400 | DeletePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePaimonCatalog>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePaimonCatalog>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePaimonCatalogMutationOptions(options), queryClient);
    }
    export const getListPaimonCatalogsUrl = (params?: ListPaimonCatalogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs?${stringifiedParams}` : `/api/paimon/catalogs`
}

/**
 * @summary 获取 Catalog 列表
 */
export const listPaimonCatalogs = async (params?: ListPaimonCatalogsParams, options?: RequestInit): Promise<PageResponsePaimonCatalogResponse> => {

  return customFetch<PageResponsePaimonCatalogResponse>(getListPaimonCatalogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPaimonCatalogsQueryKey = (params?: ListPaimonCatalogsParams,) => {
    return [
    `/api/paimon/catalogs`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPaimonCatalogsQueryOptions = <TData = Awaited<ReturnType<typeof listPaimonCatalogs>>, TError = ListPaimonCatalogs400 | ListPaimonCatalogs500>(params?: ListPaimonCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaimonCatalogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaimonCatalogs>>> = ({ signal }) => listPaimonCatalogs(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaimonCatalogsQueryResult = NonNullable<Awaited<ReturnType<typeof listPaimonCatalogs>>>
export type ListPaimonCatalogsQueryError = ListPaimonCatalogs400 | ListPaimonCatalogs500


export function useListPaimonCatalogs<TData = Awaited<ReturnType<typeof listPaimonCatalogs>>, TError = ListPaimonCatalogs400 | ListPaimonCatalogs500>(
 params: undefined |  ListPaimonCatalogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonCatalogs>>,
          TError,
          Awaited<ReturnType<typeof listPaimonCatalogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonCatalogs<TData = Awaited<ReturnType<typeof listPaimonCatalogs>>, TError = ListPaimonCatalogs400 | ListPaimonCatalogs500>(
 params?: ListPaimonCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonCatalogs>>,
          TError,
          Awaited<ReturnType<typeof listPaimonCatalogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonCatalogs<TData = Awaited<ReturnType<typeof listPaimonCatalogs>>, TError = ListPaimonCatalogs400 | ListPaimonCatalogs500>(
 params?: ListPaimonCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 Catalog 列表
 */

export function useListPaimonCatalogs<TData = Awaited<ReturnType<typeof listPaimonCatalogs>>, TError = ListPaimonCatalogs400 | ListPaimonCatalogs500>(
 params?: ListPaimonCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonCatalogs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaimonCatalogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreatePaimonCatalogUrl = () => {




  return `/api/paimon/catalogs`
}

/**
 * @summary 创建 Catalog
 */
export const createPaimonCatalog = async (paimonCatalogRequest: PaimonCatalogRequest, options?: RequestInit): Promise<CreatePaimonCatalog200> => {

  return customFetch<CreatePaimonCatalog200>(getCreatePaimonCatalogUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(paimonCatalogRequest)
  }
);}





export const getCreatePaimonCatalogMutationOptions = <TError = CreatePaimonCatalog400 | CreatePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaimonCatalog>>, TError,{data: PaimonCatalogRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPaimonCatalog>>, TError,{data: PaimonCatalogRequest}, TContext> => {

const mutationKey = ['createPaimonCatalog'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPaimonCatalog>>, {data: PaimonCatalogRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPaimonCatalog(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePaimonCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof createPaimonCatalog>>>
    export type CreatePaimonCatalogMutationBody = PaimonCatalogRequest
    export type CreatePaimonCatalogMutationError = CreatePaimonCatalog400 | CreatePaimonCatalog500

    /**
 * @summary 创建 Catalog
 */
export const useCreatePaimonCatalog = <TError = CreatePaimonCatalog400 | CreatePaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaimonCatalog>>, TError,{data: PaimonCatalogRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPaimonCatalog>>,
        TError,
        {data: PaimonCatalogRequest},
        TContext
      > => {
      return useMutation(getCreatePaimonCatalogMutationOptions(options), queryClient);
    }
    export const getCheckPaimonCatalogUrl = (id: number,) => {




  return `/api/paimon/catalogs/${id}:check`
}

/**
 * @summary 检查 Catalog 连通性
 */
export const checkPaimonCatalog = async (id: number, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getCheckPaimonCatalogUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCheckPaimonCatalogMutationOptions = <TError = CheckPaimonCatalog400 | CheckPaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkPaimonCatalog>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkPaimonCatalog>>, TError,{id: number}, TContext> => {

const mutationKey = ['checkPaimonCatalog'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkPaimonCatalog>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  checkPaimonCatalog(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckPaimonCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof checkPaimonCatalog>>>

    export type CheckPaimonCatalogMutationError = CheckPaimonCatalog400 | CheckPaimonCatalog500

    /**
 * @summary 检查 Catalog 连通性
 */
export const useCheckPaimonCatalog = <TError = CheckPaimonCatalog400 | CheckPaimonCatalog500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkPaimonCatalog>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkPaimonCatalog>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCheckPaimonCatalogMutationOptions(options), queryClient);
    }
    export const getListPaimonDatabasesUrl = (id: number,
    params?: ListPaimonDatabasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases`
}

/**
 * @summary 浏览 Paimon Database 列表
 */
export const listPaimonDatabases = async (id: number,
    params?: ListPaimonDatabasesParams, options?: RequestInit): Promise<PaimonDatabaseResponse[]> => {

  return customFetch<PaimonDatabaseResponse[]>(getListPaimonDatabasesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPaimonDatabasesQueryKey = (id: number,
    params?: ListPaimonDatabasesParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPaimonDatabasesQueryOptions = <TData = Awaited<ReturnType<typeof listPaimonDatabases>>, TError = ListPaimonDatabases400 | ListPaimonDatabases500>(id: number,
    params?: ListPaimonDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaimonDatabasesQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaimonDatabases>>> = ({ signal }) => listPaimonDatabases(id,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaimonDatabasesQueryResult = NonNullable<Awaited<ReturnType<typeof listPaimonDatabases>>>
export type ListPaimonDatabasesQueryError = ListPaimonDatabases400 | ListPaimonDatabases500


export function useListPaimonDatabases<TData = Awaited<ReturnType<typeof listPaimonDatabases>>, TError = ListPaimonDatabases400 | ListPaimonDatabases500>(
 id: number,
    params: undefined |  ListPaimonDatabasesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonDatabases>>,
          TError,
          Awaited<ReturnType<typeof listPaimonDatabases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonDatabases<TData = Awaited<ReturnType<typeof listPaimonDatabases>>, TError = ListPaimonDatabases400 | ListPaimonDatabases500>(
 id: number,
    params?: ListPaimonDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonDatabases>>,
          TError,
          Awaited<ReturnType<typeof listPaimonDatabases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonDatabases<TData = Awaited<ReturnType<typeof listPaimonDatabases>>, TError = ListPaimonDatabases400 | ListPaimonDatabases500>(
 id: number,
    params?: ListPaimonDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Database 列表
 */

export function useListPaimonDatabases<TData = Awaited<ReturnType<typeof listPaimonDatabases>>, TError = ListPaimonDatabases400 | ListPaimonDatabases500>(
 id: number,
    params?: ListPaimonDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonDatabases>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaimonDatabasesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListPaimonTablesUrl = (id: number,
    databaseName: string,
    params?: ListPaimonTablesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables`
}

/**
 * @summary 浏览 Paimon Table 列表
 */
export const listPaimonTables = async (id: number,
    databaseName: string,
    params?: ListPaimonTablesParams, options?: RequestInit): Promise<PaimonTableResponse[]> => {

  return customFetch<PaimonTableResponse[]>(getListPaimonTablesUrl(id,databaseName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPaimonTablesQueryKey = (id: number,
    databaseName: string,
    params?: ListPaimonTablesParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPaimonTablesQueryOptions = <TData = Awaited<ReturnType<typeof listPaimonTables>>, TError = ListPaimonTables400 | ListPaimonTables500>(id: number,
    databaseName: string,
    params?: ListPaimonTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaimonTablesQueryKey(id,databaseName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaimonTables>>> = ({ signal }) => listPaimonTables(id,databaseName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaimonTablesQueryResult = NonNullable<Awaited<ReturnType<typeof listPaimonTables>>>
export type ListPaimonTablesQueryError = ListPaimonTables400 | ListPaimonTables500


export function useListPaimonTables<TData = Awaited<ReturnType<typeof listPaimonTables>>, TError = ListPaimonTables400 | ListPaimonTables500>(
 id: number,
    databaseName: string,
    params: undefined |  ListPaimonTablesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTables>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTables<TData = Awaited<ReturnType<typeof listPaimonTables>>, TError = ListPaimonTables400 | ListPaimonTables500>(
 id: number,
    databaseName: string,
    params?: ListPaimonTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTables>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTables<TData = Awaited<ReturnType<typeof listPaimonTables>>, TError = ListPaimonTables400 | ListPaimonTables500>(
 id: number,
    databaseName: string,
    params?: ListPaimonTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Table 列表
 */

export function useListPaimonTables<TData = Awaited<ReturnType<typeof listPaimonTables>>, TError = ListPaimonTables400 | ListPaimonTables500>(
 id: number,
    databaseName: string,
    params?: ListPaimonTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTables>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaimonTablesQueryOptions(id,databaseName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListPaimonTableSnapshotsUrl = (id: number,
    databaseName: string,
    tableName: string,) => {




  return `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/snapshots`
}

/**
 * @summary 浏览 Paimon Table Snapshot 列表
 */
export const listPaimonTableSnapshots = async (id: number,
    databaseName: string,
    tableName: string, options?: RequestInit): Promise<PaimonTableSnapshotsResponse> => {

  return customFetch<PaimonTableSnapshotsResponse>(getListPaimonTableSnapshotsUrl(id,databaseName,tableName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPaimonTableSnapshotsQueryKey = (id: number,
    databaseName: string,
    tableName: string,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/snapshots`
    ] as const;
    }


export const getListPaimonTableSnapshotsQueryOptions = <TData = Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500>(id: number,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaimonTableSnapshotsQueryKey(id,databaseName,tableName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaimonTableSnapshots>>> = ({ signal }) => listPaimonTableSnapshots(id,databaseName,tableName, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaimonTableSnapshotsQueryResult = NonNullable<Awaited<ReturnType<typeof listPaimonTableSnapshots>>>
export type ListPaimonTableSnapshotsQueryError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500


export function useListPaimonTableSnapshots<TData = Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500>(
 id: number,
    databaseName: string,
    tableName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTableSnapshots>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTableSnapshots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTableSnapshots<TData = Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500>(
 id: number,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTableSnapshots>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTableSnapshots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTableSnapshots<TData = Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500>(
 id: number,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Table Snapshot 列表
 */

export function useListPaimonTableSnapshots<TData = Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError = ListPaimonTableSnapshots400 | ListPaimonTableSnapshots500>(
 id: number,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableSnapshots>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaimonTableSnapshotsQueryOptions(id,databaseName,tableName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetPaimonTableSchemaUrl = (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/schema?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/schema`
}

/**
 * @summary 浏览 Paimon Table Schema
 */
export const getPaimonTableSchema = async (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams, options?: RequestInit): Promise<PaimonTableSchemaResponse> => {

  return customFetch<PaimonTableSchemaResponse>(getGetPaimonTableSchemaUrl(id,databaseName,tableName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPaimonTableSchemaQueryKey = (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/schema`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPaimonTableSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getPaimonTableSchema>>, TError = GetPaimonTableSchema400 | GetPaimonTableSchema500>(id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaimonTableSchemaQueryKey(id,databaseName,tableName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaimonTableSchema>>> = ({ signal }) => getPaimonTableSchema(id,databaseName,tableName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaimonTableSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getPaimonTableSchema>>>
export type GetPaimonTableSchemaQueryError = GetPaimonTableSchema400 | GetPaimonTableSchema500


export function useGetPaimonTableSchema<TData = Awaited<ReturnType<typeof getPaimonTableSchema>>, TError = GetPaimonTableSchema400 | GetPaimonTableSchema500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: undefined |  GetPaimonTableSchemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableSchema>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableSchema<TData = Awaited<ReturnType<typeof getPaimonTableSchema>>, TError = GetPaimonTableSchema400 | GetPaimonTableSchema500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableSchema>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableSchema<TData = Awaited<ReturnType<typeof getPaimonTableSchema>>, TError = GetPaimonTableSchema400 | GetPaimonTableSchema500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Table Schema
 */

export function useGetPaimonTableSchema<TData = Awaited<ReturnType<typeof getPaimonTableSchema>>, TError = GetPaimonTableSchema400 | GetPaimonTableSchema500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaimonTableSchemaQueryOptions(id,databaseName,tableName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPreviewPaimonTableUrl = (id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/preview?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/preview`
}

/**
 * @summary 预览 Paimon Table 数据
 */
export const previewPaimonTable = async (id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams, options?: RequestInit): Promise<PaimonTablePreviewResponse> => {

  return customFetch<PaimonTablePreviewResponse>(getPreviewPaimonTableUrl(id,databaseName,tableName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPreviewPaimonTableQueryKey = (id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getPreviewPaimonTableQueryOptions = <TData = Awaited<ReturnType<typeof previewPaimonTable>>, TError = PreviewPaimonTable400 | PreviewPaimonTable500>(id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewPaimonTableQueryKey(id,databaseName,tableName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewPaimonTable>>> = ({ signal }) => previewPaimonTable(id,databaseName,tableName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewPaimonTableQueryResult = NonNullable<Awaited<ReturnType<typeof previewPaimonTable>>>
export type PreviewPaimonTableQueryError = PreviewPaimonTable400 | PreviewPaimonTable500


export function usePreviewPaimonTable<TData = Awaited<ReturnType<typeof previewPaimonTable>>, TError = PreviewPaimonTable400 | PreviewPaimonTable500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: undefined |  PreviewPaimonTableParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewPaimonTable>>,
          TError,
          Awaited<ReturnType<typeof previewPaimonTable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewPaimonTable<TData = Awaited<ReturnType<typeof previewPaimonTable>>, TError = PreviewPaimonTable400 | PreviewPaimonTable500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewPaimonTable>>,
          TError,
          Awaited<ReturnType<typeof previewPaimonTable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewPaimonTable<TData = Awaited<ReturnType<typeof previewPaimonTable>>, TError = PreviewPaimonTable400 | PreviewPaimonTable500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 预览 Paimon Table 数据
 */

export function usePreviewPaimonTable<TData = Awaited<ReturnType<typeof previewPaimonTable>>, TError = PreviewPaimonTable400 | PreviewPaimonTable500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: PreviewPaimonTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewPaimonTable>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewPaimonTableQueryOptions(id,databaseName,tableName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListPaimonTableFilesUrl = (id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files`
}

/**
 * @summary 浏览 Paimon Table 文件目录
 */
export const listPaimonTableFiles = async (id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams, options?: RequestInit): Promise<PaimonTableFilesResponse> => {

  return customFetch<PaimonTableFilesResponse>(getListPaimonTableFilesUrl(id,databaseName,tableName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPaimonTableFilesQueryKey = (id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPaimonTableFilesQueryOptions = <TData = Awaited<ReturnType<typeof listPaimonTableFiles>>, TError = ListPaimonTableFiles400 | ListPaimonTableFiles500>(id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaimonTableFilesQueryKey(id,databaseName,tableName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaimonTableFiles>>> = ({ signal }) => listPaimonTableFiles(id,databaseName,tableName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaimonTableFilesQueryResult = NonNullable<Awaited<ReturnType<typeof listPaimonTableFiles>>>
export type ListPaimonTableFilesQueryError = ListPaimonTableFiles400 | ListPaimonTableFiles500


export function useListPaimonTableFiles<TData = Awaited<ReturnType<typeof listPaimonTableFiles>>, TError = ListPaimonTableFiles400 | ListPaimonTableFiles500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: undefined |  ListPaimonTableFilesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTableFiles>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTableFiles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTableFiles<TData = Awaited<ReturnType<typeof listPaimonTableFiles>>, TError = ListPaimonTableFiles400 | ListPaimonTableFiles500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaimonTableFiles>>,
          TError,
          Awaited<ReturnType<typeof listPaimonTableFiles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaimonTableFiles<TData = Awaited<ReturnType<typeof listPaimonTableFiles>>, TError = ListPaimonTableFiles400 | ListPaimonTableFiles500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Table 文件目录
 */

export function useListPaimonTableFiles<TData = Awaited<ReturnType<typeof listPaimonTableFiles>>, TError = ListPaimonTableFiles400 | ListPaimonTableFiles500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: ListPaimonTableFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaimonTableFiles>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaimonTableFilesQueryOptions(id,databaseName,tableName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetPaimonTableFileContentUrl = (id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files/content?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files/content`
}

/**
 * @summary 预览 Paimon Table 文件内容
 */
export const getPaimonTableFileContent = async (id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options?: RequestInit): Promise<PaimonTableFileContentResponse> => {

  return customFetch<PaimonTableFileContentResponse>(getGetPaimonTableFileContentUrl(id,databaseName,tableName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPaimonTableFileContentQueryKey = (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableFileContentParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/files/content`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPaimonTableFileContentQueryOptions = <TData = Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500>(id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaimonTableFileContentQueryKey(id,databaseName,tableName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaimonTableFileContent>>> = ({ signal }) => getPaimonTableFileContent(id,databaseName,tableName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaimonTableFileContentQueryResult = NonNullable<Awaited<ReturnType<typeof getPaimonTableFileContent>>>
export type GetPaimonTableFileContentQueryError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500


export function useGetPaimonTableFileContent<TData = Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableFileContent>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableFileContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableFileContent<TData = Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableFileContent>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableFileContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableFileContent<TData = Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 预览 Paimon Table 文件内容
 */

export function useGetPaimonTableFileContent<TData = Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError = GetPaimonTableFileContent400 | GetPaimonTableFileContent500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: GetPaimonTableFileContentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableFileContent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaimonTableFileContentQueryOptions(id,databaseName,tableName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetPaimonTableDefinitionUrl = (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/definition?${stringifiedParams}` : `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/definition`
}

/**
 * @summary 浏览 Paimon Table 定义
 */
export const getPaimonTableDefinition = async (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams, options?: RequestInit): Promise<PaimonTableDefinitionResponse> => {

  return customFetch<PaimonTableDefinitionResponse>(getGetPaimonTableDefinitionUrl(id,databaseName,tableName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPaimonTableDefinitionQueryKey = (id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams,) => {
    return [
    `/api/paimon/catalogs/${id}/databases/${databaseName}/tables/${tableName}/definition`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPaimonTableDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500>(id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaimonTableDefinitionQueryKey(id,databaseName,tableName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaimonTableDefinition>>> = ({ signal }) => getPaimonTableDefinition(id,databaseName,tableName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && tableName !== null && tableName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaimonTableDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof getPaimonTableDefinition>>>
export type GetPaimonTableDefinitionQueryError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500


export function useGetPaimonTableDefinition<TData = Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500>(
 id: number,
    databaseName: string,
    tableName: string,
    params: undefined |  GetPaimonTableDefinitionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableDefinition>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableDefinition<TData = Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaimonTableDefinition>>,
          TError,
          Awaited<ReturnType<typeof getPaimonTableDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaimonTableDefinition<TData = Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 Paimon Table 定义
 */

export function useGetPaimonTableDefinition<TData = Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError = GetPaimonTableDefinition400 | GetPaimonTableDefinition500>(
 id: number,
    databaseName: string,
    tableName: string,
    params?: GetPaimonTableDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaimonTableDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaimonTableDefinitionQueryOptions(id,databaseName,tableName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






