/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPlatformSystemInfo400,
  GetPlatformSystemInfo500,
  SystemInfoResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPlatformSystemInfoUrl = () => {




  return `/api/platform/system-info`
}

/**
 * @summary 获取平台系统信息
 */
export const getPlatformSystemInfo = async ( options?: RequestInit): Promise<SystemInfoResponse> => {

  return customFetch<SystemInfoResponse>(getGetPlatformSystemInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlatformSystemInfoQueryKey = () => {
    return [
    `/api/platform/system-info`
    ] as const;
    }


export const getGetPlatformSystemInfoQueryOptions = <TData = Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlatformSystemInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlatformSystemInfo>>> = ({ signal }) => getPlatformSystemInfo({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlatformSystemInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getPlatformSystemInfo>>>
export type GetPlatformSystemInfoQueryError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500


export function useGetPlatformSystemInfo<TData = Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlatformSystemInfo>>,
          TError,
          Awaited<ReturnType<typeof getPlatformSystemInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlatformSystemInfo<TData = Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlatformSystemInfo>>,
          TError,
          Awaited<ReturnType<typeof getPlatformSystemInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlatformSystemInfo<TData = Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取平台系统信息
 */

export function useGetPlatformSystemInfo<TData = Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError = GetPlatformSystemInfo400 | GetPlatformSystemInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSystemInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlatformSystemInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






