/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePlatformTenant400,
  CreatePlatformTenant500,
  DeletePlatformTenant200,
  DeletePlatformTenant400,
  DeletePlatformTenant500,
  ListPlatformTenants400,
  ListPlatformTenants500,
  ListPlatformTenantsParams,
  PageResponseTenantResponse,
  TenantRequest,
  TenantResponse,
  UpdatePlatformTenant400,
  UpdatePlatformTenant500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getUpdatePlatformTenantUrl = (id: number,) => {




  return `/api/platform/tenants/${id}`
}

/**
 * @summary 更新平台组织
 */
export const updatePlatformTenant = async (id: number,
    tenantRequest: TenantRequest, options?: RequestInit): Promise<TenantResponse> => {

  return customFetch<TenantResponse>(getUpdatePlatformTenantUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tenantRequest)
  }
);}





export const getUpdatePlatformTenantMutationOptions = <TError = UpdatePlatformTenant400 | UpdatePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformTenant>>, TError,{id: number;data: TenantRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePlatformTenant>>, TError,{id: number;data: TenantRequest}, TContext> => {

const mutationKey = ['updatePlatformTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlatformTenant>>, {id: number;data: TenantRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlatformTenant(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlatformTenantMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlatformTenant>>>
    export type UpdatePlatformTenantMutationBody = TenantRequest
    export type UpdatePlatformTenantMutationError = UpdatePlatformTenant400 | UpdatePlatformTenant500

    /**
 * @summary 更新平台组织
 */
export const useUpdatePlatformTenant = <TError = UpdatePlatformTenant400 | UpdatePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformTenant>>, TError,{id: number;data: TenantRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlatformTenant>>,
        TError,
        {id: number;data: TenantRequest},
        TContext
      > => {
      return useMutation(getUpdatePlatformTenantMutationOptions(options), queryClient);
    }
    export const getDeletePlatformTenantUrl = (id: number,) => {




  return `/api/platform/tenants/${id}`
}

/**
 * @summary 删除平台组织
 */
export const deletePlatformTenant = async (id: number, options?: RequestInit): Promise<DeletePlatformTenant200> => {

  return customFetch<DeletePlatformTenant200>(getDeletePlatformTenantUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePlatformTenantMutationOptions = <TError = DeletePlatformTenant400 | DeletePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlatformTenant>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePlatformTenant>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePlatformTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlatformTenant>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePlatformTenant(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePlatformTenantMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlatformTenant>>>

    export type DeletePlatformTenantMutationError = DeletePlatformTenant400 | DeletePlatformTenant500

    /**
 * @summary 删除平台组织
 */
export const useDeletePlatformTenant = <TError = DeletePlatformTenant400 | DeletePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlatformTenant>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlatformTenant>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePlatformTenantMutationOptions(options), queryClient);
    }
    export const getListPlatformTenantsUrl = (params?: ListPlatformTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/platform/tenants?${stringifiedParams}` : `/api/platform/tenants`
}

/**
 * @summary 获取平台组织列表
 */
export const listPlatformTenants = async (params?: ListPlatformTenantsParams, options?: RequestInit): Promise<PageResponseTenantResponse> => {

  return customFetch<PageResponseTenantResponse>(getListPlatformTenantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPlatformTenantsQueryKey = (params?: ListPlatformTenantsParams,) => {
    return [
    `/api/platform/tenants`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPlatformTenantsQueryOptions = <TData = Awaited<ReturnType<typeof listPlatformTenants>>, TError = ListPlatformTenants400 | ListPlatformTenants500>(params?: ListPlatformTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlatformTenantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlatformTenants>>> = ({ signal }) => listPlatformTenants(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPlatformTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof listPlatformTenants>>>
export type ListPlatformTenantsQueryError = ListPlatformTenants400 | ListPlatformTenants500


export function useListPlatformTenants<TData = Awaited<ReturnType<typeof listPlatformTenants>>, TError = ListPlatformTenants400 | ListPlatformTenants500>(
 params: undefined |  ListPlatformTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlatformTenants>>,
          TError,
          Awaited<ReturnType<typeof listPlatformTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlatformTenants<TData = Awaited<ReturnType<typeof listPlatformTenants>>, TError = ListPlatformTenants400 | ListPlatformTenants500>(
 params?: ListPlatformTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlatformTenants>>,
          TError,
          Awaited<ReturnType<typeof listPlatformTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlatformTenants<TData = Awaited<ReturnType<typeof listPlatformTenants>>, TError = ListPlatformTenants400 | ListPlatformTenants500>(
 params?: ListPlatformTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取平台组织列表
 */

export function useListPlatformTenants<TData = Awaited<ReturnType<typeof listPlatformTenants>>, TError = ListPlatformTenants400 | ListPlatformTenants500>(
 params?: ListPlatformTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPlatformTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreatePlatformTenantUrl = () => {




  return `/api/platform/tenants`
}

/**
 * @summary 创建平台组织
 */
export const createPlatformTenant = async (tenantRequest: TenantRequest, options?: RequestInit): Promise<TenantResponse> => {

  return customFetch<TenantResponse>(getCreatePlatformTenantUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tenantRequest)
  }
);}





export const getCreatePlatformTenantMutationOptions = <TError = CreatePlatformTenant400 | CreatePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlatformTenant>>, TError,{data: TenantRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlatformTenant>>, TError,{data: TenantRequest}, TContext> => {

const mutationKey = ['createPlatformTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlatformTenant>>, {data: TenantRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPlatformTenant(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePlatformTenantMutationResult = NonNullable<Awaited<ReturnType<typeof createPlatformTenant>>>
    export type CreatePlatformTenantMutationBody = TenantRequest
    export type CreatePlatformTenantMutationError = CreatePlatformTenant400 | CreatePlatformTenant500

    /**
 * @summary 创建平台组织
 */
export const useCreatePlatformTenant = <TError = CreatePlatformTenant400 | CreatePlatformTenant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlatformTenant>>, TError,{data: TenantRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlatformTenant>>,
        TError,
        {data: TenantRequest},
        TContext
      > => {
      return useMutation(getCreatePlatformTenantMutationOptions(options), queryClient);
    }
