/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelSchedulerExecution400,
  CancelSchedulerExecution500,
  CreateSchedulerWorkflow400,
  CreateSchedulerWorkflow500,
  DeleteSchedulerWorkflow200,
  DeleteSchedulerWorkflow400,
  DeleteSchedulerWorkflow500,
  GetSchedulerWorkflow400,
  GetSchedulerWorkflow500,
  GetSchedulerWorkflowDefinition400,
  GetSchedulerWorkflowDefinition500,
  ListSchedulerExecutionLogs400,
  ListSchedulerExecutionLogs500,
  ListSchedulerExecutions400,
  ListSchedulerExecutions500,
  ListSchedulerExecutionsParams,
  ListSchedulerNodeExecutions400,
  ListSchedulerNodeExecutions500,
  ListSchedulerWorkflowVersions400,
  ListSchedulerWorkflowVersions500,
  ListSchedulerWorkflows400,
  ListSchedulerWorkflows500,
  ListSchedulerWorkflowsParams,
  PageResponseSchedulerExecutionResponse,
  PageResponseSchedulerWorkflowResponse,
  PublishSchedulerWorkflow400,
  PublishSchedulerWorkflow500,
  RunSchedulerWorkflow400,
  RunSchedulerWorkflow500,
  SchedulerDefinitionRequest,
  SchedulerDefinitionResponse,
  SchedulerExecutionLogResponse,
  SchedulerExecutionResponse,
  SchedulerNodeExecutionResponse,
  SchedulerValidationResponse,
  SchedulerVersionRequest,
  SchedulerVersionResponse,
  SchedulerWorkflowRequest,
  SchedulerWorkflowResponse,
  UpdateSchedulerWorkflow400,
  UpdateSchedulerWorkflow500,
  UpdateSchedulerWorkflowDefinition400,
  UpdateSchedulerWorkflowDefinition500,
  ValidateSchedulerWorkflow400,
  ValidateSchedulerWorkflow500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}`
}

/**
 * @summary 获取调度工作流详情
 */
export const getSchedulerWorkflow = async (id: number, options?: RequestInit): Promise<SchedulerWorkflowResponse> => {

  return customFetch<SchedulerWorkflowResponse>(getGetSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSchedulerWorkflowQueryKey = (id: number,) => {
    return [
    `/api/scheduler/workflows/${id}`
    ] as const;
    }


export const getGetSchedulerWorkflowQueryOptions = <TData = Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchedulerWorkflowQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulerWorkflow>>> = ({ signal }) => getSchedulerWorkflow(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSchedulerWorkflowQueryResult = NonNullable<Awaited<ReturnType<typeof getSchedulerWorkflow>>>
export type GetSchedulerWorkflowQueryError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500


export function useGetSchedulerWorkflow<TData = Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulerWorkflow>>,
          TError,
          Awaited<ReturnType<typeof getSchedulerWorkflow>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchedulerWorkflow<TData = Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulerWorkflow>>,
          TError,
          Awaited<ReturnType<typeof getSchedulerWorkflow>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchedulerWorkflow<TData = Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取调度工作流详情
 */

export function useGetSchedulerWorkflow<TData = Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError = GetSchedulerWorkflow400 | GetSchedulerWorkflow500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflow>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSchedulerWorkflowQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}`
}

/**
 * @summary 更新调度工作流
 */
export const updateSchedulerWorkflow = async (id: number,
    schedulerWorkflowRequest: SchedulerWorkflowRequest, options?: RequestInit): Promise<SchedulerWorkflowResponse> => {

  return customFetch<SchedulerWorkflowResponse>(getUpdateSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(schedulerWorkflowRequest)
  }
);}





export const getUpdateSchedulerWorkflowMutationOptions = <TError = UpdateSchedulerWorkflow400 | UpdateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflow>>, TError,{id: number;data: SchedulerWorkflowRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflow>>, TError,{id: number;data: SchedulerWorkflowRequest}, TContext> => {

const mutationKey = ['updateSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSchedulerWorkflow>>, {id: number;data: SchedulerWorkflowRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSchedulerWorkflow(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof updateSchedulerWorkflow>>>
    export type UpdateSchedulerWorkflowMutationBody = SchedulerWorkflowRequest
    export type UpdateSchedulerWorkflowMutationError = UpdateSchedulerWorkflow400 | UpdateSchedulerWorkflow500

    /**
 * @summary 更新调度工作流
 */
export const useUpdateSchedulerWorkflow = <TError = UpdateSchedulerWorkflow400 | UpdateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflow>>, TError,{id: number;data: SchedulerWorkflowRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSchedulerWorkflow>>,
        TError,
        {id: number;data: SchedulerWorkflowRequest},
        TContext
      > => {
      return useMutation(getUpdateSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getDeleteSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}`
}

/**
 * @summary 删除调度工作流
 */
export const deleteSchedulerWorkflow = async (id: number, options?: RequestInit): Promise<DeleteSchedulerWorkflow200> => {

  return customFetch<DeleteSchedulerWorkflow200>(getDeleteSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSchedulerWorkflowMutationOptions = <TError = DeleteSchedulerWorkflow400 | DeleteSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSchedulerWorkflow>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSchedulerWorkflow>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSchedulerWorkflow>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteSchedulerWorkflow(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSchedulerWorkflow>>>

    export type DeleteSchedulerWorkflowMutationError = DeleteSchedulerWorkflow400 | DeleteSchedulerWorkflow500

    /**
 * @summary 删除调度工作流
 */
export const useDeleteSchedulerWorkflow = <TError = DeleteSchedulerWorkflow400 | DeleteSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSchedulerWorkflow>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSchedulerWorkflow>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getGetSchedulerWorkflowDefinitionUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}/definition`
}

/**
 * @summary 获取调度工作流编排定义
 */
export const getSchedulerWorkflowDefinition = async (id: number, options?: RequestInit): Promise<SchedulerDefinitionResponse> => {

  return customFetch<SchedulerDefinitionResponse>(getGetSchedulerWorkflowDefinitionUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSchedulerWorkflowDefinitionQueryKey = (id: number,) => {
    return [
    `/api/scheduler/workflows/${id}/definition`
    ] as const;
    }


export const getGetSchedulerWorkflowDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchedulerWorkflowDefinitionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>> = ({ signal }) => getSchedulerWorkflowDefinition(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSchedulerWorkflowDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>>
export type GetSchedulerWorkflowDefinitionQueryError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500


export function useGetSchedulerWorkflowDefinition<TData = Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>,
          TError,
          Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchedulerWorkflowDefinition<TData = Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>,
          TError,
          Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSchedulerWorkflowDefinition<TData = Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取调度工作流编排定义
 */

export function useGetSchedulerWorkflowDefinition<TData = Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError = GetSchedulerWorkflowDefinition400 | GetSchedulerWorkflowDefinition500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulerWorkflowDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSchedulerWorkflowDefinitionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateSchedulerWorkflowDefinitionUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}/definition`
}

/**
 * @summary 保存调度工作流编排定义
 */
export const updateSchedulerWorkflowDefinition = async (id: number,
    schedulerDefinitionRequest: SchedulerDefinitionRequest, options?: RequestInit): Promise<SchedulerDefinitionResponse> => {

  return customFetch<SchedulerDefinitionResponse>(getUpdateSchedulerWorkflowDefinitionUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(schedulerDefinitionRequest)
  }
);}





export const getUpdateSchedulerWorkflowDefinitionMutationOptions = <TError = UpdateSchedulerWorkflowDefinition400 | UpdateSchedulerWorkflowDefinition500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>, TError,{id: number;data: SchedulerDefinitionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>, TError,{id: number;data: SchedulerDefinitionRequest}, TContext> => {

const mutationKey = ['updateSchedulerWorkflowDefinition'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>, {id: number;data: SchedulerDefinitionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSchedulerWorkflowDefinition(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSchedulerWorkflowDefinitionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>>
    export type UpdateSchedulerWorkflowDefinitionMutationBody = SchedulerDefinitionRequest
    export type UpdateSchedulerWorkflowDefinitionMutationError = UpdateSchedulerWorkflowDefinition400 | UpdateSchedulerWorkflowDefinition500

    /**
 * @summary 保存调度工作流编排定义
 */
export const useUpdateSchedulerWorkflowDefinition = <TError = UpdateSchedulerWorkflowDefinition400 | UpdateSchedulerWorkflowDefinition500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>, TError,{id: number;data: SchedulerDefinitionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSchedulerWorkflowDefinition>>,
        TError,
        {id: number;data: SchedulerDefinitionRequest},
        TContext
      > => {
      return useMutation(getUpdateSchedulerWorkflowDefinitionMutationOptions(options), queryClient);
    }
    export const getListSchedulerWorkflowsUrl = (params?: ListSchedulerWorkflowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/scheduler/workflows?${stringifiedParams}` : `/api/scheduler/workflows`
}

/**
 * @summary 查询调度工作流列表
 */
export const listSchedulerWorkflows = async (params?: ListSchedulerWorkflowsParams, options?: RequestInit): Promise<PageResponseSchedulerWorkflowResponse> => {

  return customFetch<PageResponseSchedulerWorkflowResponse>(getListSchedulerWorkflowsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSchedulerWorkflowsQueryKey = (params?: ListSchedulerWorkflowsParams,) => {
    return [
    `/api/scheduler/workflows`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSchedulerWorkflowsQueryOptions = <TData = Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500>(params?: ListSchedulerWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSchedulerWorkflowsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchedulerWorkflows>>> = ({ signal }) => listSchedulerWorkflows(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSchedulerWorkflowsQueryResult = NonNullable<Awaited<ReturnType<typeof listSchedulerWorkflows>>>
export type ListSchedulerWorkflowsQueryError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500


export function useListSchedulerWorkflows<TData = Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500>(
 params: undefined |  ListSchedulerWorkflowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerWorkflows>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerWorkflows<TData = Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500>(
 params?: ListSchedulerWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerWorkflows>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerWorkflows<TData = Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500>(
 params?: ListSchedulerWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询调度工作流列表
 */

export function useListSchedulerWorkflows<TData = Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError = ListSchedulerWorkflows400 | ListSchedulerWorkflows500>(
 params?: ListSchedulerWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSchedulerWorkflowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateSchedulerWorkflowUrl = () => {




  return `/api/scheduler/workflows`
}

/**
 * @summary 创建调度工作流
 */
export const createSchedulerWorkflow = async (schedulerWorkflowRequest: SchedulerWorkflowRequest, options?: RequestInit): Promise<SchedulerWorkflowResponse> => {

  return customFetch<SchedulerWorkflowResponse>(getCreateSchedulerWorkflowUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(schedulerWorkflowRequest)
  }
);}





export const getCreateSchedulerWorkflowMutationOptions = <TError = CreateSchedulerWorkflow400 | CreateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSchedulerWorkflow>>, TError,{data: SchedulerWorkflowRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSchedulerWorkflow>>, TError,{data: SchedulerWorkflowRequest}, TContext> => {

const mutationKey = ['createSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSchedulerWorkflow>>, {data: SchedulerWorkflowRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSchedulerWorkflow(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof createSchedulerWorkflow>>>
    export type CreateSchedulerWorkflowMutationBody = SchedulerWorkflowRequest
    export type CreateSchedulerWorkflowMutationError = CreateSchedulerWorkflow400 | CreateSchedulerWorkflow500

    /**
 * @summary 创建调度工作流
 */
export const useCreateSchedulerWorkflow = <TError = CreateSchedulerWorkflow400 | CreateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSchedulerWorkflow>>, TError,{data: SchedulerWorkflowRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSchedulerWorkflow>>,
        TError,
        {data: SchedulerWorkflowRequest},
        TContext
      > => {
      return useMutation(getCreateSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getValidateSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}:validate`
}

/**
 * @summary 校验调度工作流编排定义
 */
export const validateSchedulerWorkflow = async (id: number, options?: RequestInit): Promise<SchedulerValidationResponse> => {

  return customFetch<SchedulerValidationResponse>(getValidateSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getValidateSchedulerWorkflowMutationOptions = <TError = ValidateSchedulerWorkflow400 | ValidateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateSchedulerWorkflow>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof validateSchedulerWorkflow>>, TError,{id: number}, TContext> => {

const mutationKey = ['validateSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateSchedulerWorkflow>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  validateSchedulerWorkflow(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ValidateSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof validateSchedulerWorkflow>>>

    export type ValidateSchedulerWorkflowMutationError = ValidateSchedulerWorkflow400 | ValidateSchedulerWorkflow500

    /**
 * @summary 校验调度工作流编排定义
 */
export const useValidateSchedulerWorkflow = <TError = ValidateSchedulerWorkflow400 | ValidateSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateSchedulerWorkflow>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateSchedulerWorkflow>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getValidateSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getRunSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}:run`
}

/**
 * @summary 手动运行调度工作流
 */
export const runSchedulerWorkflow = async (id: number, options?: RequestInit): Promise<SchedulerExecutionResponse> => {

  return customFetch<SchedulerExecutionResponse>(getRunSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRunSchedulerWorkflowMutationOptions = <TError = RunSchedulerWorkflow400 | RunSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSchedulerWorkflow>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof runSchedulerWorkflow>>, TError,{id: number}, TContext> => {

const mutationKey = ['runSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runSchedulerWorkflow>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  runSchedulerWorkflow(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof runSchedulerWorkflow>>>

    export type RunSchedulerWorkflowMutationError = RunSchedulerWorkflow400 | RunSchedulerWorkflow500

    /**
 * @summary 手动运行调度工作流
 */
export const useRunSchedulerWorkflow = <TError = RunSchedulerWorkflow400 | RunSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSchedulerWorkflow>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runSchedulerWorkflow>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getRunSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getPublishSchedulerWorkflowUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}:publish`
}

/**
 * @summary 发布调度工作流版本
 */
export const publishSchedulerWorkflow = async (id: number,
    schedulerVersionRequest?: SchedulerVersionRequest, options?: RequestInit): Promise<SchedulerVersionResponse> => {

  return customFetch<SchedulerVersionResponse>(getPublishSchedulerWorkflowUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(schedulerVersionRequest)
  }
);}





export const getPublishSchedulerWorkflowMutationOptions = <TError = PublishSchedulerWorkflow400 | PublishSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishSchedulerWorkflow>>, TError,{id: number;data?: SchedulerVersionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publishSchedulerWorkflow>>, TError,{id: number;data?: SchedulerVersionRequest}, TContext> => {

const mutationKey = ['publishSchedulerWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishSchedulerWorkflow>>, {id: number;data?: SchedulerVersionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  publishSchedulerWorkflow(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishSchedulerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof publishSchedulerWorkflow>>>
    export type PublishSchedulerWorkflowMutationBody = SchedulerVersionRequest | undefined
    export type PublishSchedulerWorkflowMutationError = PublishSchedulerWorkflow400 | PublishSchedulerWorkflow500

    /**
 * @summary 发布调度工作流版本
 */
export const usePublishSchedulerWorkflow = <TError = PublishSchedulerWorkflow400 | PublishSchedulerWorkflow500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishSchedulerWorkflow>>, TError,{id: number;data?: SchedulerVersionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishSchedulerWorkflow>>,
        TError,
        {id: number;data?: SchedulerVersionRequest},
        TContext
      > => {
      return useMutation(getPublishSchedulerWorkflowMutationOptions(options), queryClient);
    }
    export const getCancelSchedulerExecutionUrl = (id: number,) => {




  return `/api/scheduler/executions/${id}:cancel`
}

/**
 * @summary 取消调度运行实例
 */
export const cancelSchedulerExecution = async (id: number, options?: RequestInit): Promise<SchedulerExecutionResponse> => {

  return customFetch<SchedulerExecutionResponse>(getCancelSchedulerExecutionUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCancelSchedulerExecutionMutationOptions = <TError = CancelSchedulerExecution400 | CancelSchedulerExecution500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSchedulerExecution>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelSchedulerExecution>>, TError,{id: number}, TContext> => {

const mutationKey = ['cancelSchedulerExecution'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSchedulerExecution>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  cancelSchedulerExecution(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelSchedulerExecutionMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSchedulerExecution>>>

    export type CancelSchedulerExecutionMutationError = CancelSchedulerExecution400 | CancelSchedulerExecution500

    /**
 * @summary 取消调度运行实例
 */
export const useCancelSchedulerExecution = <TError = CancelSchedulerExecution400 | CancelSchedulerExecution500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSchedulerExecution>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelSchedulerExecution>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCancelSchedulerExecutionMutationOptions(options), queryClient);
    }
    export const getListSchedulerWorkflowVersionsUrl = (id: number,) => {




  return `/api/scheduler/workflows/${id}/versions`
}

/**
 * @summary 查询调度工作流版本列表
 */
export const listSchedulerWorkflowVersions = async (id: number, options?: RequestInit): Promise<SchedulerVersionResponse[]> => {

  return customFetch<SchedulerVersionResponse[]>(getListSchedulerWorkflowVersionsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSchedulerWorkflowVersionsQueryKey = (id: number,) => {
    return [
    `/api/scheduler/workflows/${id}/versions`
    ] as const;
    }


export const getListSchedulerWorkflowVersionsQueryOptions = <TData = Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSchedulerWorkflowVersionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>> = ({ signal }) => listSchedulerWorkflowVersions(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSchedulerWorkflowVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>>
export type ListSchedulerWorkflowVersionsQueryError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500


export function useListSchedulerWorkflowVersions<TData = Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerWorkflowVersions<TData = Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerWorkflowVersions<TData = Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询调度工作流版本列表
 */

export function useListSchedulerWorkflowVersions<TData = Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError = ListSchedulerWorkflowVersions400 | ListSchedulerWorkflowVersions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerWorkflowVersions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSchedulerWorkflowVersionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListSchedulerExecutionsUrl = (params?: ListSchedulerExecutionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/scheduler/executions?${stringifiedParams}` : `/api/scheduler/executions`
}

/**
 * @summary 查询调度运行实例
 */
export const listSchedulerExecutions = async (params?: ListSchedulerExecutionsParams, options?: RequestInit): Promise<PageResponseSchedulerExecutionResponse> => {

  return customFetch<PageResponseSchedulerExecutionResponse>(getListSchedulerExecutionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSchedulerExecutionsQueryKey = (params?: ListSchedulerExecutionsParams,) => {
    return [
    `/api/scheduler/executions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSchedulerExecutionsQueryOptions = <TData = Awaited<ReturnType<typeof listSchedulerExecutions>>, TError = ListSchedulerExecutions400 | ListSchedulerExecutions500>(params?: ListSchedulerExecutionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSchedulerExecutionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchedulerExecutions>>> = ({ signal }) => listSchedulerExecutions(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSchedulerExecutionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSchedulerExecutions>>>
export type ListSchedulerExecutionsQueryError = ListSchedulerExecutions400 | ListSchedulerExecutions500


export function useListSchedulerExecutions<TData = Awaited<ReturnType<typeof listSchedulerExecutions>>, TError = ListSchedulerExecutions400 | ListSchedulerExecutions500>(
 params: undefined |  ListSchedulerExecutionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerExecutions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerExecutions<TData = Awaited<ReturnType<typeof listSchedulerExecutions>>, TError = ListSchedulerExecutions400 | ListSchedulerExecutions500>(
 params?: ListSchedulerExecutionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerExecutions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerExecutions<TData = Awaited<ReturnType<typeof listSchedulerExecutions>>, TError = ListSchedulerExecutions400 | ListSchedulerExecutions500>(
 params?: ListSchedulerExecutionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询调度运行实例
 */

export function useListSchedulerExecutions<TData = Awaited<ReturnType<typeof listSchedulerExecutions>>, TError = ListSchedulerExecutions400 | ListSchedulerExecutions500>(
 params?: ListSchedulerExecutionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSchedulerExecutionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListSchedulerNodeExecutionsUrl = (id: number,) => {




  return `/api/scheduler/executions/${id}/nodes`
}

/**
 * @summary 查询调度节点运行明细
 */
export const listSchedulerNodeExecutions = async (id: number, options?: RequestInit): Promise<SchedulerNodeExecutionResponse[]> => {

  return customFetch<SchedulerNodeExecutionResponse[]>(getListSchedulerNodeExecutionsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSchedulerNodeExecutionsQueryKey = (id: number,) => {
    return [
    `/api/scheduler/executions/${id}/nodes`
    ] as const;
    }


export const getListSchedulerNodeExecutionsQueryOptions = <TData = Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSchedulerNodeExecutionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>> = ({ signal }) => listSchedulerNodeExecutions(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSchedulerNodeExecutionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>>
export type ListSchedulerNodeExecutionsQueryError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500


export function useListSchedulerNodeExecutions<TData = Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerNodeExecutions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerNodeExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerNodeExecutions<TData = Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerNodeExecutions>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerNodeExecutions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerNodeExecutions<TData = Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询调度节点运行明细
 */

export function useListSchedulerNodeExecutions<TData = Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError = ListSchedulerNodeExecutions400 | ListSchedulerNodeExecutions500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerNodeExecutions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSchedulerNodeExecutionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListSchedulerExecutionLogsUrl = (id: number,) => {




  return `/api/scheduler/executions/${id}/logs`
}

/**
 * @summary 查询调度运行日志
 */
export const listSchedulerExecutionLogs = async (id: number, options?: RequestInit): Promise<SchedulerExecutionLogResponse[]> => {

  return customFetch<SchedulerExecutionLogResponse[]>(getListSchedulerExecutionLogsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSchedulerExecutionLogsQueryKey = (id: number,) => {
    return [
    `/api/scheduler/executions/${id}/logs`
    ] as const;
    }


export const getListSchedulerExecutionLogsQueryOptions = <TData = Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSchedulerExecutionLogsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>> = ({ signal }) => listSchedulerExecutionLogs(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSchedulerExecutionLogsQueryResult = NonNullable<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>>
export type ListSchedulerExecutionLogsQueryError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500


export function useListSchedulerExecutionLogs<TData = Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerExecutionLogs>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerExecutionLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerExecutionLogs<TData = Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSchedulerExecutionLogs>>,
          TError,
          Awaited<ReturnType<typeof listSchedulerExecutionLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSchedulerExecutionLogs<TData = Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询调度运行日志
 */

export function useListSchedulerExecutionLogs<TData = Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError = ListSchedulerExecutionLogs400 | ListSchedulerExecutionLogs500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSchedulerExecutionLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSchedulerExecutionLogsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






