/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
export interface VariableRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  variableName: string;
  variableValue?: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  description?: string;
}

export interface VariableResponse {
  id?: number;
  variableName?: string;
  variableValue?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface UserUpdateRequest {
  /**
     * @minLength 8
     * @maxLength 128
     */
  password?: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  nickname?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  email?: string;
  /** @pattern ADMIN|MEMBER */
  role?: string;
  status?: number;
}

export interface SystemDefaultsRequest {
  /**
     * @minimum 1
     * @maximum 1024
     */
  defaultParallelism?: number;
  /**
     * @minimum 1
     * @maximum 1000
     */
  savepointRetention?: number;
  /**
     * @minimum 1
     * @maximum 1000
     */
  jobVersionRetention?: number;
  /**
     * @minimum 1
     * @maximum 5000
     */
  jobExecutionRetention?: number;
  failureAlertEnabled?: boolean;
}

export interface SystemDefaultsResponse {
  defaultParallelism?: number;
  savepointRetention?: number;
  jobVersionRetention?: number;
  jobExecutionRetention?: number;
  failureAlertEnabled?: boolean;
}

export interface StarRocksConnectionRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  connectionName: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  feAddress: string;
  /**
     * @minimum 1
     * @maximum 65535
     */
  queryPort?: number;
  /**
     * @minLength 0
     * @maxLength 128
     */
  username: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  password?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  defaultDatabase?: string;
  /** @pattern ACTIVE|INACTIVE */
  status?: string;
  description?: string;
}

export interface SchedulerWorkflowRequest {
  /**
     * @minLength 0
     * @maxLength 256
     */
  workflowName: string;
  description?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  cron?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  period?: string;
  timezone?: string;
  /** @pattern ACTIVE|PAUSED */
  status?: string;
  /** @pattern TOPOLOGY|SERIAL_QUEUE */
  executionMode?: string;
  /** @pattern BLOCK_ALL|CONTINUE_NEXT */
  failureStrategy?: string;
  /** @pattern SERIAL_RUNS|CONCURRENT */
  concurrentPolicy?: string;
  alertChannelId?: number;
}

export interface SchedulerWorkflowResponse {
  id?: number;
  workflowName?: string;
  description?: string;
  cron?: string;
  period?: string;
  timezone?: string;
  status?: string;
  executionMode?: string;
  failureStrategy?: string;
  concurrentPolicy?: string;
  alertChannelId?: number;
  nodeCount?: number;
  latestVersion?: string;
  latestExecutionStatus?: string;
  lastRunTime?: string;
  nextRunTime?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface SchedulerNodeRequest {
  /**
     * @minLength 0
     * @maxLength 64
     */
  nodeKey: string;
  flinkJobId: number;
  /** @minimum 0 */
  maxRetries?: number;
  /** @minimum 1 */
  retryInterval?: number;
  /** @minimum 0 */
  timeoutMinutes?: number;
  /** @pattern ALARM_ONLY|KILL_AND_ALARM */
  onTimeout?: string;
  /** @minimum 0 */
  positionX?: number;
  /** @minimum 0 */
  positionY?: number;
}

export interface SchedulerEdgeRequest {
  /**
     * @minLength 0
     * @maxLength 64
     */
  fromNodeKey: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  toNodeKey: string;
  /** @pattern WAIT_SUCCESS|WAIT_ENDED|WAIT_FAILED */
  strategy?: string;
}

export interface SchedulerVariableRequest {
  /**
     * @minLength 0
     * @maxLength 128
     * @pattern [A-Za-z_][A-Za-z0-9_\-]*
     */
  variableKey: string;
  variableValue?: string;
}

export interface SchedulerDefinitionRequest {
  nodes?: SchedulerNodeRequest[];
  edges?: SchedulerEdgeRequest[];
  variables?: SchedulerVariableRequest[];
}

export interface SchedulerNodeResponse {
  id?: number;
  nodeKey?: string;
  flinkJobId?: number;
  jobName?: string;
  jobType?: string;
  maxRetries?: number;
  retryInterval?: number;
  timeoutMinutes?: number;
  onTimeout?: string;
  positionX?: number;
  positionY?: number;
}

export interface SchedulerEdgeResponse {
  id?: number;
  fromNodeKey?: string;
  toNodeKey?: string;
  strategy?: string;
}

export interface SchedulerVariableResponse {
  id?: number;
  variableKey?: string;
  variableValue?: string;
}

export interface SchedulerDefinitionResponse {
  workflow?: SchedulerWorkflowResponse;
  nodes?: SchedulerNodeResponse[];
  edges?: SchedulerEdgeResponse[];
  variables?: SchedulerVariableResponse[];
}

export interface TenantRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  tenantName: string;
  /** @pattern [a-z0-9][a-z0-9-]{1,62} */
  tenantSlug: string;
  /** @pattern ACTIVE|INACTIVE */
  status?: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  description?: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  adminUsername?: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  adminPassword?: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  adminNickname?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  adminEmail?: string;
}

export interface TenantResponse {
  id?: number;
  tenantName?: string;
  tenantSlug?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PaimonCatalogRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  catalogName: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  warehouse: string;
  /** @pattern filesystem|hive|jdbc|rest */
  metastoreType?: string;
  options?: string;
  /** @pattern ACTIVE|INACTIVE */
  status?: string;
  description?: string;
}

export type NotificationChannelRequestConfig = {[key: string]: string};

export interface NotificationChannelRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  name: string;
  /** @pattern feishu|webhook|dingtalk|wecom|inapp */
  type: string;
  config?: NotificationChannelRequestConfig;
  enabled?: boolean;
}

export type NotificationChannelResponseConfig = {[key: string]: string};

export interface NotificationChannelResponse {
  id?: number;
  name?: string;
  type?: string;
  config?: NotificationChannelResponseConfig;
  enabled?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ModelProviderConfigRequest {
  /** @pattern openai_compatible */
  provider: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  baseUrl: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  apiKey?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  defaultModel: string;
  models?: string;
  enabled?: boolean;
}

export interface ModelProviderConfigResponse {
  id?: number;
  provider?: string;
  baseUrl?: string;
  apiKey?: string;
  defaultModel?: string;
  models?: string;
  enabled?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface FlussTopicRequest {
  clusterId: number;
  /**
     * @minLength 0
     * @maxLength 256
     */
  topicName: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  namespaceName?: string;
  /**
     * @minimum 1
     * @maximum 4096
     */
  bucketCount?: number;
  /**
     * @minimum 1
     * @maximum 9
     */
  replicationFactor?: number;
  /** @pattern CREATED|ACTIVE|INACTIVE */
  status?: string;
  description?: string;
}

export interface FlussClusterRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  clusterName: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  bootstrapServers: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  defaultDatabase?: string;
  /** @pattern ACTIVE|INACTIVE */
  status?: string;
  description?: string;
}

export interface FlinkRuntimeRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  clusterName: string;
  /** @pattern standalone|kubernetes */
  clusterType: string;
  /** @pattern session|application */
  deploymentMode?: string;
  /**
     * @minLength 0
     * @maxLength 256
     * @pattern https?://[^\s]+
     */
  address?: string;
  /**
     * @minLength 0
     * @maxLength 256
     * @pattern https?://[^\s]+
     */
  gatewayAddress?: string;
  /** @pattern RUNNING|STOPPED|UNREACHABLE */
  status?: string;
  /**
     * @minLength 0
     * @maxLength 32
     */
  flinkVersion?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  namespaceName?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  serviceAccount?: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  image?: string;
  /** @pattern IfNotPresent|Always|Never */
  imagePullPolicy?: string;
  /** @pattern CLUSTER_IP|NODE_PORT|LOAD_BALANCER|INGRESS */
  serviceExposureType?: string;
  kubeConfigRef?: string;
  podTemplate?: string;
  /**
     * @minimum 1
     * @maximum 1024
     */
  defaultParallelism?: number;
  /**
     * @minLength 0
     * @maxLength 512
     */
  checkpointDir?: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  savepointDir?: string;
  description?: string;
}

export interface FlinkJobRequest {
  /**
     * @minLength 0
     * @maxLength 256
     */
  jobName: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  jobGroup?: string;
  /** @pattern JAR|SQL */
  jobType?: string;
  /** @pattern BATCH|STREAMING */
  runtimeMode?: string;
  /** @pattern REST|SQL_GATEWAY|K8S_APPLICATION */
  submitType?: string;
  /** @pattern standalone|k8s-application */
  executionMode?: string;
  clusterId?: number;
  content?: string;
  mainClass?: string;
  args?: string;
  flinkConfig?: string;
  /**
     * @minimum 1
     * @maximum 1024
     */
  parallelism?: number;
  description?: string;
  /**
     * @minLength 0
     * @maxLength 1024
     */
  docUrl?: string;
  savepointPath?: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  applicationImage?: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  jarUri?: string;
  dependencyRefs?: string;
  alertChannelId?: number;
  alertRule?: string;
}

export interface FlinkJarResourceRequest {
  /**
     * @minLength 0
     * @maxLength 128
     */
  resourceName: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  resourceVersion?: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  compatibleFlinkVersion?: string;
  /**
     * @minLength 0
     * @maxLength 512
     */
  storageUri: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  checksum?: string;
  /** @pattern ACTIVE|INACTIVE */
  status?: string;
}

export interface UserCreateRequest {
  /**
     * @minLength 0
     * @maxLength 64
     */
  username: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  nickname?: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  email?: string;
  /** @pattern ADMIN|MEMBER */
  role?: string;
  status?: number;
}

export interface StarRocksSqlQueryRequest {
  /**
     * @minLength 0
     * @maxLength 20000
     */
  sql: string;
  /**
     * @minimum 1
     * @maximum 5000
     */
  limit?: number;
}

export interface StarRocksPreviewColumn {
  name?: string;
  type?: string;
}

export type StarRocksPreviewResponseDataItem = {[key: string]: { [key: string]: unknown }};

export interface StarRocksPreviewResponse {
  databaseName?: string;
  objectName?: string;
  columns?: StarRocksPreviewColumn[];
  data?: StarRocksPreviewResponseDataItem[];
  truncated?: boolean;
  message?: string;
}

export interface StarRocksDdlRequest {
  /**
     * @minLength 0
     * @maxLength 20000
     */
  sql: string;
}

export interface SchedulerValidationResponse {
  valid?: boolean;
  errors?: string[];
  warnings?: string[];
}

export interface SchedulerExecutionResponse {
  id?: number;
  workflowId?: number;
  versionId?: number;
  triggerType?: string;
  status?: string;
  message?: string;
  startedAt?: string;
  finishedAt?: string;
  createdAt?: string;
}

export interface SchedulerVersionRequest {
  remark?: string;
}

export interface SchedulerVersionResponse {
  id?: number;
  workflowId?: number;
  versionNo?: number;
  versionName?: string;
  remark?: string;
  createdAt?: string;
}

export interface FlinkSqlValidateRequest {
  clusterId: number;
  sql: string;
}

export interface FlinkSqlValidateResponse {
  valid?: boolean;
  message?: string;
  line?: number;
  column?: number;
  statementCount?: number;
}

export interface FlinkSqlPreviewRequest {
  clusterId: number;
  sql: string;
  jobName?: string;
  limit?: number;
}

export interface ColumnInfo {
  name?: string;
  type?: string;
}

export type FlinkSqlPreviewResponseDataItem = {[key: string]: { [key: string]: unknown }};

export interface FlinkSqlPreviewResponse {
  previewType?: string;
  columns?: ColumnInfo[];
  data?: FlinkSqlPreviewResponseDataItem[];
  truncated?: boolean;
  message?: string;
}

export interface FlinkRuntimeCheckResponse {
  clusterReachable?: boolean;
  clusterStatus?: string;
  gatewayStatus?: string;
  flinkVersion?: string;
}

export interface FlinkJobResponse {
  id?: number;
  jobName?: string;
  jobGroup?: string;
  jobType?: string;
  runtimeMode?: string;
  submitType?: string;
  executionMode?: string;
  clusterId?: number;
  currentExecutionId?: number;
  flinkJobId?: string;
  status?: string;
  publishStatus?: string;
  content?: string;
  mainClass?: string;
  args?: string;
  flinkConfig?: string;
  parallelism?: number;
  savepointPath?: string;
  applicationImage?: string;
  jarUri?: string;
  dependencyRefs?: string;
  description?: string;
  docUrl?: string;
  alertChannelId?: number;
  alertRule?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface SavepointRequest {
  targetDirectory?: string;
  cancelJob?: boolean;
}

export interface FlinkSavepointResponse {
  recordId?: number;
  requestId?: string;
  location?: string;
  status?: string;
  flinkJobId?: string;
  targetDirectory?: string;
  cancelJob?: boolean;
}

export interface FlinkJobVersionRequest {
  remark?: string;
}

export interface FlinkJobVersionResponse {
  id?: number;
  jobId?: number;
  versionNo?: number;
  versionName?: string;
  remark?: string;
  createdAt?: string;
}

export interface FlinkJarResourceResponse {
  id?: number;
  resourceName?: string;
  resourceVersion?: string;
  compatibleFlinkVersion?: string;
  storageUri?: string;
  checksum?: string;
  status?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface UserProfile {
  id?: number;
  username?: string;
  nickname?: string;
  email?: string;
  role?: string;
  status?: number;
  lastLoginAt?: string;
}

export interface LoginResponse {
  token?: string;
  tokenType?: string;
  expiresIn?: number;
  user?: UserProfile;
}

export interface Pagination {
  is_pager?: number;
  page?: number;
  size?: number;
  total?: number;
  pages?: number;
}

export interface PageResponseVariableResponse {
  list?: VariableResponse[];
  pagination?: Pagination;
}

export interface TenantUserResponse {
  id?: number;
  tenantId?: number;
  username?: string;
  nickname?: string;
  email?: string;
  role?: string;
  status?: number;
  lastLoginAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponseTenantUserResponse {
  list?: TenantUserResponse[];
  pagination?: Pagination;
}

export interface PageResponseTenantResponse {
  list?: TenantResponse[];
  pagination?: Pagination;
}

export interface StarRocksConnectionResponse {
  id?: number;
  connectionName?: string;
  feAddress?: string;
  queryPort?: number;
  username?: string;
  defaultDatabase?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponseStarRocksConnectionResponse {
  list?: StarRocksConnectionResponse[];
  pagination?: Pagination;
}

export interface StarRocksDatabaseResponse {
  databaseName?: string;
}

export interface StarRocksObjectResponse {
  databaseName?: string;
  objectName?: string;
  objectType?: string;
}

export interface StarRocksObjectSchemaColumn {
  name?: string;
  type?: string;
  nullable?: string;
  key?: string;
  defaultValue?: string;
  extra?: string;
}

export interface StarRocksObjectSchemaResponse {
  databaseName?: string;
  objectName?: string;
  columns?: StarRocksObjectSchemaColumn[];
}

export interface StarRocksObjectDefinitionResponse {
  databaseName?: string;
  objectName?: string;
  objectType?: string;
  createSql?: string;
}

export interface PageResponseSchedulerWorkflowResponse {
  list?: SchedulerWorkflowResponse[];
  pagination?: Pagination;
}

export interface PageResponseSchedulerExecutionResponse {
  list?: SchedulerExecutionResponse[];
  pagination?: Pagination;
}

export interface SchedulerNodeExecutionResponse {
  id?: number;
  executionId?: number;
  workflowId?: number;
  nodeKey?: string;
  flinkJobId?: number;
  flinkRuntimeJobId?: string;
  status?: string;
  retryIndex?: number;
  message?: string;
  startedAt?: string;
  finishedAt?: string;
  createdAt?: string;
}

export interface SchedulerExecutionLogResponse {
  id?: number;
  executionId?: number;
  workflowId?: number;
  nodeExecutionId?: number;
  nodeKey?: string;
  level?: string;
  eventType?: string;
  message?: string;
  createdAt?: string;
}

export interface PaimonCatalogResponse {
  id?: number;
  catalogName?: string;
  warehouse?: string;
  metastoreType?: string;
  options?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponsePaimonCatalogResponse {
  list?: PaimonCatalogResponse[];
  pagination?: Pagination;
}

export interface PaimonCatalogDetailResponse {
  id?: number;
  catalogName?: string;
  warehouse?: string;
  metastoreType?: string;
  options?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PaimonDatabaseResponse {
  databaseName?: string;
}

export interface PaimonTableResponse {
  databaseName?: string;
  tableName?: string;
}

export type PaimonTableSnapshotsResponseRowsItem = {[key: string]: { [key: string]: unknown }};

export interface PaimonTableSnapshotsResponse {
  databaseName?: string;
  tableName?: string;
  columns?: string[];
  rows?: PaimonTableSnapshotsResponseRowsItem[];
  message?: string;
}

export interface PaimonTableSchemaColumn {
  name?: string;
  type?: string;
  nullable?: string;
  key?: string;
  extras?: string;
  watermark?: string;
}

export interface PaimonTableSchemaResponse {
  databaseName?: string;
  tableName?: string;
  columns?: PaimonTableSchemaColumn[];
}

export interface PaimonTablePreviewColumn {
  name?: string;
  type?: string;
}

export type PaimonTablePreviewResponseDataItem = {[key: string]: { [key: string]: unknown }};

export interface PaimonTablePreviewResponse {
  databaseName?: string;
  tableName?: string;
  columns?: PaimonTablePreviewColumn[];
  data?: PaimonTablePreviewResponseDataItem[];
  truncated?: boolean;
}

export interface Entry {
  name?: string;
  path?: string;
  type?: string;
  size?: number;
  lastModified?: string;
}

export interface PaimonTableFilesResponse {
  databaseName?: string;
  tableName?: string;
  tablePath?: string;
  currentPath?: string;
  parentPath?: string;
  entries?: Entry[];
}

export type PaimonTableFileContentResponseRowsItem = {[key: string]: { [key: string]: unknown }};

export interface PaimonTableFileContentResponse {
  databaseName?: string;
  tableName?: string;
  tablePath?: string;
  path?: string;
  name?: string;
  contentType?: string;
  size?: number;
  truncated?: boolean;
  viewable?: boolean;
  content?: string;
  columns?: string[];
  rows?: PaimonTableFileContentResponseRowsItem[];
  message?: string;
}

export type PaimonTableDefinitionResponseOptions = {[key: string]: string};

export interface PaimonTableDefinitionResponse {
  databaseName?: string;
  tableName?: string;
  qualifiedName?: string;
  schemaId?: number;
  schemaVersion?: number;
  comment?: string;
  partitionKeys?: string[];
  primaryKeys?: string[];
  bucketKeys?: string[];
  numBuckets?: number;
  options?: PaimonTableDefinitionResponseOptions;
  createTableSql?: string;
}

export interface PageResponseNotificationChannelResponse {
  list?: NotificationChannelResponse[];
  pagination?: Pagination;
}

export interface HealthResponse {
  status?: string;
  app?: string;
  version?: string;
}

export interface FlussTopicResponse {
  id?: number;
  clusterId?: number;
  topicName?: string;
  namespaceName?: string;
  bucketCount?: number;
  replicationFactor?: number;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponseFlussTopicResponse {
  list?: FlussTopicResponse[];
  pagination?: Pagination;
}

export interface FlussClusterResponse {
  id?: number;
  clusterName?: string;
  bootstrapServers?: string;
  defaultDatabase?: string;
  status?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponseFlussClusterResponse {
  list?: FlussClusterResponse[];
  pagination?: Pagination;
}

export interface FlinkRuntimeResponse {
  id?: number;
  clusterName?: string;
  clusterType?: string;
  deploymentMode?: string;
  address?: string;
  status?: string;
  flinkVersion?: string;
  description?: string;
  gatewayAddress?: string;
  gatewayStatus?: string;
  namespaceName?: string;
  serviceAccount?: string;
  image?: string;
  imagePullPolicy?: string;
  serviceExposureType?: string;
  kubeConfigRef?: string;
  podTemplate?: string;
  defaultParallelism?: number;
  checkpointDir?: string;
  savepointDir?: string;
  clusterScope?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PageResponseFlinkRuntimeResponse {
  list?: FlinkRuntimeResponse[];
  pagination?: Pagination;
}

export interface PageResponseFlinkJobResponse {
  list?: FlinkJobResponse[];
  pagination?: Pagination;
}

export interface FlinkSavepointRecordResponse {
  id?: number;
  jobId?: number;
  jobName?: string;
  flinkJobId?: string;
  requestId?: string;
  location?: string;
  targetDirectory?: string;
  cancelJob?: boolean;
  status?: string;
  triggerMessage?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface FlinkJobExecutionResponse {
  id?: number;
  jobId?: number;
  versionId?: number;
  versionName?: string;
  flinkJobId?: string;
  status?: string;
  submitPayload?: string;
  errorLog?: string;
  startTime?: string;
  endTime?: string;
  duration?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type FlinkCheckpointResponseCounts = {[key: string]: { [key: string]: unknown }};

export type FlinkCheckpointResponseSummary = {[key: string]: { [key: string]: unknown }};

export type FlinkCheckpointResponseLatest = {[key: string]: { [key: string]: unknown }};

export type FlinkCheckpointResponseHistoryItem = {[key: string]: { [key: string]: unknown }};

export type FlinkCheckpointResponseRaw = {[key: string]: { [key: string]: unknown }};

export interface FlinkCheckpointResponse {
  flinkJobId?: string;
  counts?: FlinkCheckpointResponseCounts;
  summary?: FlinkCheckpointResponseSummary;
  latest?: FlinkCheckpointResponseLatest;
  history?: FlinkCheckpointResponseHistoryItem[];
  raw?: FlinkCheckpointResponseRaw;
}

export interface PageResponseFlinkJarResourceResponse {
  list?: FlinkJarResourceResponse[];
  pagination?: Pagination;
}

export type UpdateVariable400 = { [key: string]: unknown };

export type UpdateVariable500 = { [key: string]: unknown };

export type DeleteVariable200 = { [key: string]: unknown };

export type DeleteVariable400 = { [key: string]: unknown };

export type DeleteVariable500 = { [key: string]: unknown };

export type UpdateUser200 = { [key: string]: unknown };

export type UpdateUser400 = { [key: string]: unknown };

export type UpdateUser500 = { [key: string]: unknown };

export type DeleteUser200 = { [key: string]: unknown };

export type DeleteUser400 = { [key: string]: unknown };

export type DeleteUser500 = { [key: string]: unknown };

export type GetSystemDefaults400 = { [key: string]: unknown };

export type GetSystemDefaults500 = { [key: string]: unknown };

export type UpdateSystemDefaults400 = { [key: string]: unknown };

export type UpdateSystemDefaults500 = { [key: string]: unknown };

export type GetStarRocksConnection400 = { [key: string]: unknown };

export type GetStarRocksConnection500 = { [key: string]: unknown };

export type UpdateStarRocksConnection200 = { [key: string]: unknown };

export type UpdateStarRocksConnection400 = { [key: string]: unknown };

export type UpdateStarRocksConnection500 = { [key: string]: unknown };

export type DeleteStarRocksConnection200 = { [key: string]: unknown };

export type DeleteStarRocksConnection400 = { [key: string]: unknown };

export type DeleteStarRocksConnection500 = { [key: string]: unknown };

export type GetSchedulerWorkflow400 = { [key: string]: unknown };

export type GetSchedulerWorkflow500 = { [key: string]: unknown };

export type UpdateSchedulerWorkflow400 = { [key: string]: unknown };

export type UpdateSchedulerWorkflow500 = { [key: string]: unknown };

export type DeleteSchedulerWorkflow200 = { [key: string]: unknown };

export type DeleteSchedulerWorkflow400 = { [key: string]: unknown };

export type DeleteSchedulerWorkflow500 = { [key: string]: unknown };

export type GetSchedulerWorkflowDefinition400 = { [key: string]: unknown };

export type GetSchedulerWorkflowDefinition500 = { [key: string]: unknown };

export type UpdateSchedulerWorkflowDefinition400 = { [key: string]: unknown };

export type UpdateSchedulerWorkflowDefinition500 = { [key: string]: unknown };

export type UpdatePlatformTenant400 = { [key: string]: unknown };

export type UpdatePlatformTenant500 = { [key: string]: unknown };

export type DeletePlatformTenant200 = { [key: string]: unknown };

export type DeletePlatformTenant400 = { [key: string]: unknown };

export type DeletePlatformTenant500 = { [key: string]: unknown };

export type GetPaimonCatalog400 = { [key: string]: unknown };

export type GetPaimonCatalog500 = { [key: string]: unknown };

export type UpdatePaimonCatalog200 = { [key: string]: unknown };

export type UpdatePaimonCatalog400 = { [key: string]: unknown };

export type UpdatePaimonCatalog500 = { [key: string]: unknown };

export type DeletePaimonCatalog200 = { [key: string]: unknown };

export type DeletePaimonCatalog400 = { [key: string]: unknown };

export type DeletePaimonCatalog500 = { [key: string]: unknown };

export type UpdateNotificationChannel400 = { [key: string]: unknown };

export type UpdateNotificationChannel500 = { [key: string]: unknown };

export type DeleteNotificationChannel200 = { [key: string]: unknown };

export type DeleteNotificationChannel400 = { [key: string]: unknown };

export type DeleteNotificationChannel500 = { [key: string]: unknown };

export type GetModelProviderConfig400 = { [key: string]: unknown };

export type GetModelProviderConfig500 = { [key: string]: unknown };

export type UpdateModelProviderConfig400 = { [key: string]: unknown };

export type UpdateModelProviderConfig500 = { [key: string]: unknown };

export type GetFlussTopic400 = { [key: string]: unknown };

export type GetFlussTopic500 = { [key: string]: unknown };

export type UpdateFlussTopic200 = { [key: string]: unknown };

export type UpdateFlussTopic400 = { [key: string]: unknown };

export type UpdateFlussTopic500 = { [key: string]: unknown };

export type DeleteFlussTopic200 = { [key: string]: unknown };

export type DeleteFlussTopic400 = { [key: string]: unknown };

export type DeleteFlussTopic500 = { [key: string]: unknown };

export type GetFlussCluster400 = { [key: string]: unknown };

export type GetFlussCluster500 = { [key: string]: unknown };

export type UpdateFlussCluster200 = { [key: string]: unknown };

export type UpdateFlussCluster400 = { [key: string]: unknown };

export type UpdateFlussCluster500 = { [key: string]: unknown };

export type DeleteFlussCluster200 = { [key: string]: unknown };

export type DeleteFlussCluster400 = { [key: string]: unknown };

export type DeleteFlussCluster500 = { [key: string]: unknown };

export type GetFlinkRuntime400 = { [key: string]: unknown };

export type GetFlinkRuntime500 = { [key: string]: unknown };

export type UpdateFlinkRuntime200 = { [key: string]: unknown };

export type UpdateFlinkRuntime400 = { [key: string]: unknown };

export type UpdateFlinkRuntime500 = { [key: string]: unknown };

export type DeleteFlinkRuntime200 = { [key: string]: unknown };

export type DeleteFlinkRuntime400 = { [key: string]: unknown };

export type DeleteFlinkRuntime500 = { [key: string]: unknown };

export type GetFlinkJob400 = { [key: string]: unknown };

export type GetFlinkJob500 = { [key: string]: unknown };

export type UpdateFlinkJob200 = { [key: string]: unknown };

export type UpdateFlinkJob400 = { [key: string]: unknown };

export type UpdateFlinkJob500 = { [key: string]: unknown };

export type DeleteFlinkJob200 = { [key: string]: unknown };

export type DeleteFlinkJob400 = { [key: string]: unknown };

export type DeleteFlinkJob500 = { [key: string]: unknown };

export type GetFlinkJarResource400 = { [key: string]: unknown };

export type GetFlinkJarResource500 = { [key: string]: unknown };

export type UpdateFlinkJarResource200 = { [key: string]: unknown };

export type UpdateFlinkJarResource400 = { [key: string]: unknown };

export type UpdateFlinkJarResource500 = { [key: string]: unknown };

export type DeleteFlinkJarResource200 = { [key: string]: unknown };

export type DeleteFlinkJarResource400 = { [key: string]: unknown };

export type DeleteFlinkJarResource500 = { [key: string]: unknown };

export type ListVariablesParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListVariables400 = { [key: string]: unknown };

export type ListVariables500 = { [key: string]: unknown };

export type CreateVariable400 = { [key: string]: unknown };

export type CreateVariable500 = { [key: string]: unknown };

export type ListUsersParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
};

export type ListUsers400 = { [key: string]: unknown };

export type ListUsers500 = { [key: string]: unknown };

export type CreateUser200 = { [key: string]: unknown };

export type CreateUser400 = { [key: string]: unknown };

export type CreateUser500 = { [key: string]: unknown };

export type ListStarRocksConnectionsParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListStarRocksConnections400 = { [key: string]: unknown };

export type ListStarRocksConnections500 = { [key: string]: unknown };

export type CreateStarRocksConnection200 = { [key: string]: unknown };

export type CreateStarRocksConnection400 = { [key: string]: unknown };

export type CreateStarRocksConnection500 = { [key: string]: unknown };

export type CheckStarRocksConnection400 = { [key: string]: unknown };

export type CheckStarRocksConnection500 = { [key: string]: unknown };

export type ExecuteStarRocksQuery400 = { [key: string]: unknown };

export type ExecuteStarRocksQuery500 = { [key: string]: unknown };

export type ExecuteStarRocksDdl200 = { [key: string]: unknown };

export type ExecuteStarRocksDdl400 = { [key: string]: unknown };

export type ExecuteStarRocksDdl500 = { [key: string]: unknown };

export type ListSchedulerWorkflowsParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
status?: string;
};

export type ListSchedulerWorkflows400 = { [key: string]: unknown };

export type ListSchedulerWorkflows500 = { [key: string]: unknown };

export type CreateSchedulerWorkflow400 = { [key: string]: unknown };

export type CreateSchedulerWorkflow500 = { [key: string]: unknown };

export type ValidateSchedulerWorkflow400 = { [key: string]: unknown };

export type ValidateSchedulerWorkflow500 = { [key: string]: unknown };

export type RunSchedulerWorkflow400 = { [key: string]: unknown };

export type RunSchedulerWorkflow500 = { [key: string]: unknown };

export type PublishSchedulerWorkflow400 = { [key: string]: unknown };

export type PublishSchedulerWorkflow500 = { [key: string]: unknown };

export type CancelSchedulerExecution400 = { [key: string]: unknown };

export type CancelSchedulerExecution500 = { [key: string]: unknown };

export type ListPlatformTenantsParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
};

export type ListPlatformTenants400 = { [key: string]: unknown };

export type ListPlatformTenants500 = { [key: string]: unknown };

export type CreatePlatformTenant400 = { [key: string]: unknown };

export type CreatePlatformTenant500 = { [key: string]: unknown };

export type ListPaimonCatalogsParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListPaimonCatalogs400 = { [key: string]: unknown };

export type ListPaimonCatalogs500 = { [key: string]: unknown };

export type CreatePaimonCatalog200 = { [key: string]: unknown };

export type CreatePaimonCatalog400 = { [key: string]: unknown };

export type CreatePaimonCatalog500 = { [key: string]: unknown };

export type CheckPaimonCatalog400 = { [key: string]: unknown };

export type CheckPaimonCatalog500 = { [key: string]: unknown };

export type ListNotificationChannelsParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
};

export type ListNotificationChannels400 = { [key: string]: unknown };

export type ListNotificationChannels500 = { [key: string]: unknown };

export type CreateNotificationChannel400 = { [key: string]: unknown };

export type CreateNotificationChannel500 = { [key: string]: unknown };

export type TestNotificationChannel400 = { [key: string]: unknown };

export type TestNotificationChannel500 = { [key: string]: unknown };

export type TestModelProviderConfig400 = { [key: string]: unknown };

export type TestModelProviderConfig500 = { [key: string]: unknown };

export type ListFlussTopicsParams = {
cluster_id?: number;
is_pager?: number;
page?: number;
size?: number;
};

export type ListFlussTopics400 = { [key: string]: unknown };

export type ListFlussTopics500 = { [key: string]: unknown };

export type CreateFlussTopic200 = { [key: string]: unknown };

export type CreateFlussTopic400 = { [key: string]: unknown };

export type CreateFlussTopic500 = { [key: string]: unknown };

export type ListFlussClustersParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListFlussClusters400 = { [key: string]: unknown };

export type ListFlussClusters500 = { [key: string]: unknown };

export type CreateFlussCluster200 = { [key: string]: unknown };

export type CreateFlussCluster400 = { [key: string]: unknown };

export type CreateFlussCluster500 = { [key: string]: unknown };

export type CheckFlussCluster400 = { [key: string]: unknown };

export type CheckFlussCluster500 = { [key: string]: unknown };

export type ValidateFlinkSql400 = { [key: string]: unknown };

export type ValidateFlinkSql500 = { [key: string]: unknown };

export type ExecuteFlinkSqlPreview400 = { [key: string]: unknown };

export type ExecuteFlinkSqlPreview500 = { [key: string]: unknown };

export type ListFlinkRuntimesParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListFlinkRuntimes400 = { [key: string]: unknown };

export type ListFlinkRuntimes500 = { [key: string]: unknown };

export type CreateFlinkRuntime200 = { [key: string]: unknown };

export type CreateFlinkRuntime400 = { [key: string]: unknown };

export type CreateFlinkRuntime500 = { [key: string]: unknown };

export type CheckFlinkRuntime400 = { [key: string]: unknown };

export type CheckFlinkRuntime500 = { [key: string]: unknown };

export type ListFlinkJobsParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
status?: string;
job_type?: string;
};

export type ListFlinkJobs400 = { [key: string]: unknown };

export type ListFlinkJobs500 = { [key: string]: unknown };

export type CreateFlinkJob400 = { [key: string]: unknown };

export type CreateFlinkJob500 = { [key: string]: unknown };

export type TriggerFlinkSavepoint400 = { [key: string]: unknown };

export type TriggerFlinkSavepoint500 = { [key: string]: unknown };

export type StartFlinkJob400 = { [key: string]: unknown };

export type StartFlinkJob500 = { [key: string]: unknown };

export type PublishFlinkJob400 = { [key: string]: unknown };

export type PublishFlinkJob500 = { [key: string]: unknown };

export type DebugFlinkJob400 = { [key: string]: unknown };

export type DebugFlinkJob500 = { [key: string]: unknown };

export type CancelFlinkJob200 = { [key: string]: unknown };

export type CancelFlinkJob400 = { [key: string]: unknown };

export type CancelFlinkJob500 = { [key: string]: unknown };

export type ListFlinkJarResourcesParams = {
is_pager?: number;
page?: number;
size?: number;
};

export type ListFlinkJarResources400 = { [key: string]: unknown };

export type ListFlinkJarResources500 = { [key: string]: unknown };

export type CreateFlinkJarResource200 = { [key: string]: unknown };

export type CreateFlinkJarResource400 = { [key: string]: unknown };

export type CreateFlinkJarResource500 = { [key: string]: unknown };

export type UploadFlinkJarResourceParams = {
resourceName?: string;
resourceVersion?: string;
compatibleFlinkVersion?: string;
status?: string;
};

export type UploadFlinkJarResourceBody = {
  file: Blob;
};

export type UploadFlinkJarResource400 = { [key: string]: unknown };

export type UploadFlinkJarResource500 = { [key: string]: unknown };

export type Logout200 = { [key: string]: unknown };

export type Logout400 = { [key: string]: unknown };

export type Logout500 = { [key: string]: unknown };

export type Login400 = { [key: string]: unknown };

export type Login500 = { [key: string]: unknown };

export type ListMyTenantsParams = {
is_pager?: number;
page?: number;
size?: number;
keyword?: string;
};

export type ListMyTenants400 = { [key: string]: unknown };

export type ListMyTenants500 = { [key: string]: unknown };

export type ListStarRocksDatabasesParams = {
refresh?: boolean;
};

export type ListStarRocksDatabases400 = { [key: string]: unknown };

export type ListStarRocksDatabases500 = { [key: string]: unknown };

export type ListStarRocksObjectsParams = {
refresh?: boolean;
};

export type ListStarRocksObjects400 = { [key: string]: unknown };

export type ListStarRocksObjects500 = { [key: string]: unknown };

export type GetStarRocksObjectSchemaParams = {
refresh?: boolean;
};

export type GetStarRocksObjectSchema400 = { [key: string]: unknown };

export type GetStarRocksObjectSchema500 = { [key: string]: unknown };

export type PreviewStarRocksObjectParams = {
limit?: number;
};

export type PreviewStarRocksObject400 = { [key: string]: unknown };

export type PreviewStarRocksObject500 = { [key: string]: unknown };

export type ListStarRocksObjectPartitionsParams = {
refresh?: boolean;
};

export type ListStarRocksObjectPartitions400 = { [key: string]: unknown };

export type ListStarRocksObjectPartitions500 = { [key: string]: unknown };

export type GetStarRocksObjectDefinitionParams = {
refresh?: boolean;
};

export type GetStarRocksObjectDefinition400 = { [key: string]: unknown };

export type GetStarRocksObjectDefinition500 = { [key: string]: unknown };

export type ListSchedulerWorkflowVersions400 = { [key: string]: unknown };

export type ListSchedulerWorkflowVersions500 = { [key: string]: unknown };

export type ListSchedulerExecutionsParams = {
is_pager?: number;
page?: number;
size?: number;
workflowId?: number;
status?: string;
};

export type ListSchedulerExecutions400 = { [key: string]: unknown };

export type ListSchedulerExecutions500 = { [key: string]: unknown };

export type ListSchedulerNodeExecutions400 = { [key: string]: unknown };

export type ListSchedulerNodeExecutions500 = { [key: string]: unknown };

export type ListSchedulerExecutionLogs400 = { [key: string]: unknown };

export type ListSchedulerExecutionLogs500 = { [key: string]: unknown };

export type ListPaimonDatabasesParams = {
refresh?: boolean;
};

export type ListPaimonDatabases400 = { [key: string]: unknown };

export type ListPaimonDatabases500 = { [key: string]: unknown };

export type ListPaimonTablesParams = {
refresh?: boolean;
};

export type ListPaimonTables400 = { [key: string]: unknown };

export type ListPaimonTables500 = { [key: string]: unknown };

export type ListPaimonTableSnapshots400 = { [key: string]: unknown };

export type ListPaimonTableSnapshots500 = { [key: string]: unknown };

export type GetPaimonTableSchemaParams = {
refresh?: boolean;
};

export type GetPaimonTableSchema400 = { [key: string]: unknown };

export type GetPaimonTableSchema500 = { [key: string]: unknown };

export type PreviewPaimonTableParams = {
limit?: number;
};

export type PreviewPaimonTable400 = { [key: string]: unknown };

export type PreviewPaimonTable500 = { [key: string]: unknown };

export type ListPaimonTableFilesParams = {
path?: string;
refresh?: boolean;
};

export type ListPaimonTableFiles400 = { [key: string]: unknown };

export type ListPaimonTableFiles500 = { [key: string]: unknown };

export type GetPaimonTableFileContentParams = {
path: string;
};

export type GetPaimonTableFileContent400 = { [key: string]: unknown };

export type GetPaimonTableFileContent500 = { [key: string]: unknown };

export type GetPaimonTableDefinitionParams = {
refresh?: boolean;
};

export type GetPaimonTableDefinition400 = { [key: string]: unknown };

export type GetPaimonTableDefinition500 = { [key: string]: unknown };

export type GetHealth400 = { [key: string]: unknown };

export type GetHealth500 = { [key: string]: unknown };

export type ListFlinkJobVersions400 = { [key: string]: unknown };

export type ListFlinkJobVersions500 = { [key: string]: unknown };

export type ListFlinkSavepoints400 = { [key: string]: unknown };

export type ListFlinkSavepoints500 = { [key: string]: unknown };

export type ListFlinkJobExecutions400 = { [key: string]: unknown };

export type ListFlinkJobExecutions500 = { [key: string]: unknown };

export type GetFlinkCheckpoints400 = { [key: string]: unknown };

export type GetFlinkCheckpoints500 = { [key: string]: unknown };

export type GetCurrentUser400 = { [key: string]: unknown };

export type GetCurrentUser500 = { [key: string]: unknown };

