/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckStarRocksConnection400,
  CheckStarRocksConnection500,
  CreateStarRocksConnection200,
  CreateStarRocksConnection400,
  CreateStarRocksConnection500,
  DeleteStarRocksConnection200,
  DeleteStarRocksConnection400,
  DeleteStarRocksConnection500,
  ExecuteStarRocksDdl200,
  ExecuteStarRocksDdl400,
  ExecuteStarRocksDdl500,
  ExecuteStarRocksQuery400,
  ExecuteStarRocksQuery500,
  GetStarRocksConnection400,
  GetStarRocksConnection500,
  GetStarRocksObjectDefinition400,
  GetStarRocksObjectDefinition500,
  GetStarRocksObjectDefinitionParams,
  GetStarRocksObjectSchema400,
  GetStarRocksObjectSchema500,
  GetStarRocksObjectSchemaParams,
  ListStarRocksConnections400,
  ListStarRocksConnections500,
  ListStarRocksConnectionsParams,
  ListStarRocksDatabases400,
  ListStarRocksDatabases500,
  ListStarRocksDatabasesParams,
  ListStarRocksObjectPartitions400,
  ListStarRocksObjectPartitions500,
  ListStarRocksObjectPartitionsParams,
  ListStarRocksObjects400,
  ListStarRocksObjects500,
  ListStarRocksObjectsParams,
  PageResponseStarRocksConnectionResponse,
  PreviewStarRocksObject400,
  PreviewStarRocksObject500,
  PreviewStarRocksObjectParams,
  StarRocksConnectionRequest,
  StarRocksConnectionResponse,
  StarRocksDatabaseResponse,
  StarRocksDdlRequest,
  StarRocksObjectDefinitionResponse,
  StarRocksObjectResponse,
  StarRocksObjectSchemaResponse,
  StarRocksPreviewResponse,
  StarRocksSqlQueryRequest,
  UpdateStarRocksConnection200,
  UpdateStarRocksConnection400,
  UpdateStarRocksConnection500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetStarRocksConnectionUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}`
}

/**
 * @summary 获取 StarRocks 连接详情
 */
export const getStarRocksConnection = async (id: number, options?: RequestInit): Promise<StarRocksConnectionResponse> => {

  return customFetch<StarRocksConnectionResponse>(getGetStarRocksConnectionUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStarRocksConnectionQueryKey = (id: number,) => {
    return [
    `/api/starrocks/connections/${id}`
    ] as const;
    }


export const getGetStarRocksConnectionQueryOptions = <TData = Awaited<ReturnType<typeof getStarRocksConnection>>, TError = GetStarRocksConnection400 | GetStarRocksConnection500>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStarRocksConnectionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStarRocksConnection>>> = ({ signal }) => getStarRocksConnection(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStarRocksConnectionQueryResult = NonNullable<Awaited<ReturnType<typeof getStarRocksConnection>>>
export type GetStarRocksConnectionQueryError = GetStarRocksConnection400 | GetStarRocksConnection500


export function useGetStarRocksConnection<TData = Awaited<ReturnType<typeof getStarRocksConnection>>, TError = GetStarRocksConnection400 | GetStarRocksConnection500>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksConnection>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksConnection>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksConnection<TData = Awaited<ReturnType<typeof getStarRocksConnection>>, TError = GetStarRocksConnection400 | GetStarRocksConnection500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksConnection>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksConnection>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksConnection<TData = Awaited<ReturnType<typeof getStarRocksConnection>>, TError = GetStarRocksConnection400 | GetStarRocksConnection500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 StarRocks 连接详情
 */

export function useGetStarRocksConnection<TData = Awaited<ReturnType<typeof getStarRocksConnection>>, TError = GetStarRocksConnection400 | GetStarRocksConnection500>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksConnection>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStarRocksConnectionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateStarRocksConnectionUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}`
}

/**
 * @summary 更新 StarRocks 连接
 */
export const updateStarRocksConnection = async (id: number,
    starRocksConnectionRequest: StarRocksConnectionRequest, options?: RequestInit): Promise<UpdateStarRocksConnection200> => {

  return customFetch<UpdateStarRocksConnection200>(getUpdateStarRocksConnectionUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(starRocksConnectionRequest)
  }
);}





export const getUpdateStarRocksConnectionMutationOptions = <TError = UpdateStarRocksConnection400 | UpdateStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStarRocksConnection>>, TError,{id: number;data: StarRocksConnectionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateStarRocksConnection>>, TError,{id: number;data: StarRocksConnectionRequest}, TContext> => {

const mutationKey = ['updateStarRocksConnection'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStarRocksConnection>>, {id: number;data: StarRocksConnectionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateStarRocksConnection(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStarRocksConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateStarRocksConnection>>>
    export type UpdateStarRocksConnectionMutationBody = StarRocksConnectionRequest
    export type UpdateStarRocksConnectionMutationError = UpdateStarRocksConnection400 | UpdateStarRocksConnection500

    /**
 * @summary 更新 StarRocks 连接
 */
export const useUpdateStarRocksConnection = <TError = UpdateStarRocksConnection400 | UpdateStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStarRocksConnection>>, TError,{id: number;data: StarRocksConnectionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStarRocksConnection>>,
        TError,
        {id: number;data: StarRocksConnectionRequest},
        TContext
      > => {
      return useMutation(getUpdateStarRocksConnectionMutationOptions(options), queryClient);
    }
    export const getDeleteStarRocksConnectionUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}`
}

/**
 * @summary 删除 StarRocks 连接
 */
export const deleteStarRocksConnection = async (id: number, options?: RequestInit): Promise<DeleteStarRocksConnection200> => {

  return customFetch<DeleteStarRocksConnection200>(getDeleteStarRocksConnectionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteStarRocksConnectionMutationOptions = <TError = DeleteStarRocksConnection400 | DeleteStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStarRocksConnection>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteStarRocksConnection>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteStarRocksConnection'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStarRocksConnection>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteStarRocksConnection(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteStarRocksConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStarRocksConnection>>>

    export type DeleteStarRocksConnectionMutationError = DeleteStarRocksConnection400 | DeleteStarRocksConnection500

    /**
 * @summary 删除 StarRocks 连接
 */
export const useDeleteStarRocksConnection = <TError = DeleteStarRocksConnection400 | DeleteStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStarRocksConnection>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStarRocksConnection>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteStarRocksConnectionMutationOptions(options), queryClient);
    }
    export const getListStarRocksConnectionsUrl = (params?: ListStarRocksConnectionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections?${stringifiedParams}` : `/api/starrocks/connections`
}

/**
 * @summary 获取 StarRocks 连接列表
 */
export const listStarRocksConnections = async (params?: ListStarRocksConnectionsParams, options?: RequestInit): Promise<PageResponseStarRocksConnectionResponse> => {

  return customFetch<PageResponseStarRocksConnectionResponse>(getListStarRocksConnectionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStarRocksConnectionsQueryKey = (params?: ListStarRocksConnectionsParams,) => {
    return [
    `/api/starrocks/connections`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStarRocksConnectionsQueryOptions = <TData = Awaited<ReturnType<typeof listStarRocksConnections>>, TError = ListStarRocksConnections400 | ListStarRocksConnections500>(params?: ListStarRocksConnectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStarRocksConnectionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStarRocksConnections>>> = ({ signal }) => listStarRocksConnections(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStarRocksConnectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listStarRocksConnections>>>
export type ListStarRocksConnectionsQueryError = ListStarRocksConnections400 | ListStarRocksConnections500


export function useListStarRocksConnections<TData = Awaited<ReturnType<typeof listStarRocksConnections>>, TError = ListStarRocksConnections400 | ListStarRocksConnections500>(
 params: undefined |  ListStarRocksConnectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksConnections>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksConnections<TData = Awaited<ReturnType<typeof listStarRocksConnections>>, TError = ListStarRocksConnections400 | ListStarRocksConnections500>(
 params?: ListStarRocksConnectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksConnections>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksConnections<TData = Awaited<ReturnType<typeof listStarRocksConnections>>, TError = ListStarRocksConnections400 | ListStarRocksConnections500>(
 params?: ListStarRocksConnectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 StarRocks 连接列表
 */

export function useListStarRocksConnections<TData = Awaited<ReturnType<typeof listStarRocksConnections>>, TError = ListStarRocksConnections400 | ListStarRocksConnections500>(
 params?: ListStarRocksConnectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStarRocksConnectionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateStarRocksConnectionUrl = () => {




  return `/api/starrocks/connections`
}

/**
 * @summary 创建 StarRocks 连接
 */
export const createStarRocksConnection = async (starRocksConnectionRequest: StarRocksConnectionRequest, options?: RequestInit): Promise<CreateStarRocksConnection200> => {

  return customFetch<CreateStarRocksConnection200>(getCreateStarRocksConnectionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(starRocksConnectionRequest)
  }
);}





export const getCreateStarRocksConnectionMutationOptions = <TError = CreateStarRocksConnection400 | CreateStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStarRocksConnection>>, TError,{data: StarRocksConnectionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createStarRocksConnection>>, TError,{data: StarRocksConnectionRequest}, TContext> => {

const mutationKey = ['createStarRocksConnection'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStarRocksConnection>>, {data: StarRocksConnectionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createStarRocksConnection(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateStarRocksConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof createStarRocksConnection>>>
    export type CreateStarRocksConnectionMutationBody = StarRocksConnectionRequest
    export type CreateStarRocksConnectionMutationError = CreateStarRocksConnection400 | CreateStarRocksConnection500

    /**
 * @summary 创建 StarRocks 连接
 */
export const useCreateStarRocksConnection = <TError = CreateStarRocksConnection400 | CreateStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStarRocksConnection>>, TError,{data: StarRocksConnectionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStarRocksConnection>>,
        TError,
        {data: StarRocksConnectionRequest},
        TContext
      > => {
      return useMutation(getCreateStarRocksConnectionMutationOptions(options), queryClient);
    }
    export const getCheckStarRocksConnectionUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}:check`
}

/**
 * @summary 检查 StarRocks 连接
 */
export const checkStarRocksConnection = async (id: number, options?: RequestInit): Promise<boolean> => {

  return customFetch<boolean>(getCheckStarRocksConnectionUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCheckStarRocksConnectionMutationOptions = <TError = CheckStarRocksConnection400 | CheckStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkStarRocksConnection>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkStarRocksConnection>>, TError,{id: number}, TContext> => {

const mutationKey = ['checkStarRocksConnection'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkStarRocksConnection>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  checkStarRocksConnection(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckStarRocksConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof checkStarRocksConnection>>>

    export type CheckStarRocksConnectionMutationError = CheckStarRocksConnection400 | CheckStarRocksConnection500

    /**
 * @summary 检查 StarRocks 连接
 */
export const useCheckStarRocksConnection = <TError = CheckStarRocksConnection400 | CheckStarRocksConnection500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkStarRocksConnection>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkStarRocksConnection>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCheckStarRocksConnectionMutationOptions(options), queryClient);
    }
    export const getExecuteStarRocksQueryUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}/query`
}

/**
 * @summary 执行 StarRocks SQL 命令
 */
export const executeStarRocksQuery = async (id: number,
    starRocksSqlQueryRequest: StarRocksSqlQueryRequest, options?: RequestInit): Promise<StarRocksPreviewResponse> => {

  return customFetch<StarRocksPreviewResponse>(getExecuteStarRocksQueryUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(starRocksSqlQueryRequest)
  }
);}





export const getExecuteStarRocksQueryMutationOptions = <TError = ExecuteStarRocksQuery400 | ExecuteStarRocksQuery500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksQuery>>, TError,{id: number;data: StarRocksSqlQueryRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksQuery>>, TError,{id: number;data: StarRocksSqlQueryRequest}, TContext> => {

const mutationKey = ['executeStarRocksQuery'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeStarRocksQuery>>, {id: number;data: StarRocksSqlQueryRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  executeStarRocksQuery(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteStarRocksQueryMutationResult = NonNullable<Awaited<ReturnType<typeof executeStarRocksQuery>>>
    export type ExecuteStarRocksQueryMutationBody = StarRocksSqlQueryRequest
    export type ExecuteStarRocksQueryMutationError = ExecuteStarRocksQuery400 | ExecuteStarRocksQuery500

    /**
 * @summary 执行 StarRocks SQL 命令
 */
export const useExecuteStarRocksQuery = <TError = ExecuteStarRocksQuery400 | ExecuteStarRocksQuery500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksQuery>>, TError,{id: number;data: StarRocksSqlQueryRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeStarRocksQuery>>,
        TError,
        {id: number;data: StarRocksSqlQueryRequest},
        TContext
      > => {
      return useMutation(getExecuteStarRocksQueryMutationOptions(options), queryClient);
    }
    export const getExecuteStarRocksDdlUrl = (id: number,) => {




  return `/api/starrocks/connections/${id}/ddl`
}

/**
 * @summary 执行 StarRocks 建表或物化视图 DDL
 */
export const executeStarRocksDdl = async (id: number,
    starRocksDdlRequest: StarRocksDdlRequest, options?: RequestInit): Promise<ExecuteStarRocksDdl200> => {

  return customFetch<ExecuteStarRocksDdl200>(getExecuteStarRocksDdlUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(starRocksDdlRequest)
  }
);}





export const getExecuteStarRocksDdlMutationOptions = <TError = ExecuteStarRocksDdl400 | ExecuteStarRocksDdl500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksDdl>>, TError,{id: number;data: StarRocksDdlRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksDdl>>, TError,{id: number;data: StarRocksDdlRequest}, TContext> => {

const mutationKey = ['executeStarRocksDdl'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeStarRocksDdl>>, {id: number;data: StarRocksDdlRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  executeStarRocksDdl(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteStarRocksDdlMutationResult = NonNullable<Awaited<ReturnType<typeof executeStarRocksDdl>>>
    export type ExecuteStarRocksDdlMutationBody = StarRocksDdlRequest
    export type ExecuteStarRocksDdlMutationError = ExecuteStarRocksDdl400 | ExecuteStarRocksDdl500

    /**
 * @summary 执行 StarRocks 建表或物化视图 DDL
 */
export const useExecuteStarRocksDdl = <TError = ExecuteStarRocksDdl400 | ExecuteStarRocksDdl500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeStarRocksDdl>>, TError,{id: number;data: StarRocksDdlRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeStarRocksDdl>>,
        TError,
        {id: number;data: StarRocksDdlRequest},
        TContext
      > => {
      return useMutation(getExecuteStarRocksDdlMutationOptions(options), queryClient);
    }
    export const getListStarRocksDatabasesUrl = (id: number,
    params?: ListStarRocksDatabasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases`
}

/**
 * @summary 浏览 StarRocks Database 列表
 */
export const listStarRocksDatabases = async (id: number,
    params?: ListStarRocksDatabasesParams, options?: RequestInit): Promise<StarRocksDatabaseResponse[]> => {

  return customFetch<StarRocksDatabaseResponse[]>(getListStarRocksDatabasesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStarRocksDatabasesQueryKey = (id: number,
    params?: ListStarRocksDatabasesParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStarRocksDatabasesQueryOptions = <TData = Awaited<ReturnType<typeof listStarRocksDatabases>>, TError = ListStarRocksDatabases400 | ListStarRocksDatabases500>(id: number,
    params?: ListStarRocksDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStarRocksDatabasesQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStarRocksDatabases>>> = ({ signal }) => listStarRocksDatabases(id,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStarRocksDatabasesQueryResult = NonNullable<Awaited<ReturnType<typeof listStarRocksDatabases>>>
export type ListStarRocksDatabasesQueryError = ListStarRocksDatabases400 | ListStarRocksDatabases500


export function useListStarRocksDatabases<TData = Awaited<ReturnType<typeof listStarRocksDatabases>>, TError = ListStarRocksDatabases400 | ListStarRocksDatabases500>(
 id: number,
    params: undefined |  ListStarRocksDatabasesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksDatabases>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksDatabases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksDatabases<TData = Awaited<ReturnType<typeof listStarRocksDatabases>>, TError = ListStarRocksDatabases400 | ListStarRocksDatabases500>(
 id: number,
    params?: ListStarRocksDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksDatabases>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksDatabases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksDatabases<TData = Awaited<ReturnType<typeof listStarRocksDatabases>>, TError = ListStarRocksDatabases400 | ListStarRocksDatabases500>(
 id: number,
    params?: ListStarRocksDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 StarRocks Database 列表
 */

export function useListStarRocksDatabases<TData = Awaited<ReturnType<typeof listStarRocksDatabases>>, TError = ListStarRocksDatabases400 | ListStarRocksDatabases500>(
 id: number,
    params?: ListStarRocksDatabasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksDatabases>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStarRocksDatabasesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListStarRocksObjectsUrl = (id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases/${databaseName}/objects?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases/${databaseName}/objects`
}

/**
 * @summary 浏览 StarRocks 对象列表
 */
export const listStarRocksObjects = async (id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams, options?: RequestInit): Promise<StarRocksObjectResponse[]> => {

  return customFetch<StarRocksObjectResponse[]>(getListStarRocksObjectsUrl(id,databaseName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStarRocksObjectsQueryKey = (id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases/${databaseName}/objects`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStarRocksObjectsQueryOptions = <TData = Awaited<ReturnType<typeof listStarRocksObjects>>, TError = ListStarRocksObjects400 | ListStarRocksObjects500>(id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStarRocksObjectsQueryKey(id,databaseName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStarRocksObjects>>> = ({ signal }) => listStarRocksObjects(id,databaseName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStarRocksObjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listStarRocksObjects>>>
export type ListStarRocksObjectsQueryError = ListStarRocksObjects400 | ListStarRocksObjects500


export function useListStarRocksObjects<TData = Awaited<ReturnType<typeof listStarRocksObjects>>, TError = ListStarRocksObjects400 | ListStarRocksObjects500>(
 id: number,
    databaseName: string,
    params: undefined |  ListStarRocksObjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksObjects>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksObjects>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksObjects<TData = Awaited<ReturnType<typeof listStarRocksObjects>>, TError = ListStarRocksObjects400 | ListStarRocksObjects500>(
 id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksObjects>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksObjects>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksObjects<TData = Awaited<ReturnType<typeof listStarRocksObjects>>, TError = ListStarRocksObjects400 | ListStarRocksObjects500>(
 id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 StarRocks 对象列表
 */

export function useListStarRocksObjects<TData = Awaited<ReturnType<typeof listStarRocksObjects>>, TError = ListStarRocksObjects400 | ListStarRocksObjects500>(
 id: number,
    databaseName: string,
    params?: ListStarRocksObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjects>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStarRocksObjectsQueryOptions(id,databaseName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetStarRocksObjectSchemaUrl = (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/schema?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/schema`
}

/**
 * @summary 浏览 StarRocks 对象 Schema
 */
export const getStarRocksObjectSchema = async (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams, options?: RequestInit): Promise<StarRocksObjectSchemaResponse> => {

  return customFetch<StarRocksObjectSchemaResponse>(getGetStarRocksObjectSchemaUrl(id,databaseName,objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStarRocksObjectSchemaQueryKey = (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/schema`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetStarRocksObjectSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500>(id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStarRocksObjectSchemaQueryKey(id,databaseName,objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStarRocksObjectSchema>>> = ({ signal }) => getStarRocksObjectSchema(id,databaseName,objectName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStarRocksObjectSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getStarRocksObjectSchema>>>
export type GetStarRocksObjectSchemaQueryError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500


export function useGetStarRocksObjectSchema<TData = Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500>(
 id: number,
    databaseName: string,
    objectName: string,
    params: undefined |  GetStarRocksObjectSchemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksObjectSchema>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksObjectSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksObjectSchema<TData = Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksObjectSchema>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksObjectSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksObjectSchema<TData = Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 StarRocks 对象 Schema
 */

export function useGetStarRocksObjectSchema<TData = Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError = GetStarRocksObjectSchema400 | GetStarRocksObjectSchema500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStarRocksObjectSchemaQueryOptions(id,databaseName,objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPreviewStarRocksObjectUrl = (id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/preview?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/preview`
}

/**
 * @summary 预览 StarRocks 对象数据
 */
export const previewStarRocksObject = async (id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams, options?: RequestInit): Promise<StarRocksPreviewResponse> => {

  return customFetch<StarRocksPreviewResponse>(getPreviewStarRocksObjectUrl(id,databaseName,objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPreviewStarRocksObjectQueryKey = (id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getPreviewStarRocksObjectQueryOptions = <TData = Awaited<ReturnType<typeof previewStarRocksObject>>, TError = PreviewStarRocksObject400 | PreviewStarRocksObject500>(id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewStarRocksObjectQueryKey(id,databaseName,objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewStarRocksObject>>> = ({ signal }) => previewStarRocksObject(id,databaseName,objectName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewStarRocksObjectQueryResult = NonNullable<Awaited<ReturnType<typeof previewStarRocksObject>>>
export type PreviewStarRocksObjectQueryError = PreviewStarRocksObject400 | PreviewStarRocksObject500


export function usePreviewStarRocksObject<TData = Awaited<ReturnType<typeof previewStarRocksObject>>, TError = PreviewStarRocksObject400 | PreviewStarRocksObject500>(
 id: number,
    databaseName: string,
    objectName: string,
    params: undefined |  PreviewStarRocksObjectParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewStarRocksObject>>,
          TError,
          Awaited<ReturnType<typeof previewStarRocksObject>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewStarRocksObject<TData = Awaited<ReturnType<typeof previewStarRocksObject>>, TError = PreviewStarRocksObject400 | PreviewStarRocksObject500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewStarRocksObject>>,
          TError,
          Awaited<ReturnType<typeof previewStarRocksObject>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewStarRocksObject<TData = Awaited<ReturnType<typeof previewStarRocksObject>>, TError = PreviewStarRocksObject400 | PreviewStarRocksObject500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 预览 StarRocks 对象数据
 */

export function usePreviewStarRocksObject<TData = Awaited<ReturnType<typeof previewStarRocksObject>>, TError = PreviewStarRocksObject400 | PreviewStarRocksObject500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: PreviewStarRocksObjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewStarRocksObject>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewStarRocksObjectQueryOptions(id,databaseName,objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListStarRocksObjectPartitionsUrl = (id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/partitions?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/partitions`
}

/**
 * @summary 浏览 StarRocks 对象分区
 */
export const listStarRocksObjectPartitions = async (id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams, options?: RequestInit): Promise<StarRocksPreviewResponse> => {

  return customFetch<StarRocksPreviewResponse>(getListStarRocksObjectPartitionsUrl(id,databaseName,objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStarRocksObjectPartitionsQueryKey = (id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/partitions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStarRocksObjectPartitionsQueryOptions = <TData = Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500>(id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStarRocksObjectPartitionsQueryKey(id,databaseName,objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>> = ({ signal }) => listStarRocksObjectPartitions(id,databaseName,objectName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStarRocksObjectPartitionsQueryResult = NonNullable<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>>
export type ListStarRocksObjectPartitionsQueryError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500


export function useListStarRocksObjectPartitions<TData = Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500>(
 id: number,
    databaseName: string,
    objectName: string,
    params: undefined |  ListStarRocksObjectPartitionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksObjectPartitions>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksObjectPartitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksObjectPartitions<TData = Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStarRocksObjectPartitions>>,
          TError,
          Awaited<ReturnType<typeof listStarRocksObjectPartitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStarRocksObjectPartitions<TData = Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 StarRocks 对象分区
 */

export function useListStarRocksObjectPartitions<TData = Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError = ListStarRocksObjectPartitions400 | ListStarRocksObjectPartitions500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: ListStarRocksObjectPartitionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStarRocksObjectPartitions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStarRocksObjectPartitionsQueryOptions(id,databaseName,objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetStarRocksObjectDefinitionUrl = (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/definition?${stringifiedParams}` : `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/definition`
}

/**
 * @summary 浏览 StarRocks 对象定义
 */
export const getStarRocksObjectDefinition = async (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams, options?: RequestInit): Promise<StarRocksObjectDefinitionResponse> => {

  return customFetch<StarRocksObjectDefinitionResponse>(getGetStarRocksObjectDefinitionUrl(id,databaseName,objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStarRocksObjectDefinitionQueryKey = (id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams,) => {
    return [
    `/api/starrocks/connections/${id}/databases/${databaseName}/objects/${objectName}/definition`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetStarRocksObjectDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500>(id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStarRocksObjectDefinitionQueryKey(id,databaseName,objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>> = ({ signal }) => getStarRocksObjectDefinition(id,databaseName,objectName,params, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && databaseName !== null && databaseName !== undefined && objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStarRocksObjectDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>>
export type GetStarRocksObjectDefinitionQueryError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500


export function useGetStarRocksObjectDefinition<TData = Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500>(
 id: number,
    databaseName: string,
    objectName: string,
    params: undefined |  GetStarRocksObjectDefinitionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksObjectDefinition>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksObjectDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksObjectDefinition<TData = Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStarRocksObjectDefinition>>,
          TError,
          Awaited<ReturnType<typeof getStarRocksObjectDefinition>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStarRocksObjectDefinition<TData = Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 浏览 StarRocks 对象定义
 */

export function useGetStarRocksObjectDefinition<TData = Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError = GetStarRocksObjectDefinition400 | GetStarRocksObjectDefinition500>(
 id: number,
    databaseName: string,
    objectName: string,
    params?: GetStarRocksObjectDefinitionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStarRocksObjectDefinition>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStarRocksObjectDefinitionQueryOptions(id,databaseName,objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






