/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHealth400,
  GetHealth500,
  GetSystemDefaults400,
  GetSystemDefaults500,
  HealthResponse,
  SystemDefaultsRequest,
  SystemDefaultsResponse,
  UpdateSystemDefaults400,
  UpdateSystemDefaults500
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetSystemDefaultsUrl = () => {




  return `/api/system/defaults`
}

/**
 * @summary 获取系统默认设置
 */
export const getSystemDefaults = async ( options?: RequestInit): Promise<SystemDefaultsResponse> => {

  return customFetch<SystemDefaultsResponse>(getGetSystemDefaultsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSystemDefaultsQueryKey = () => {
    return [
    `/api/system/defaults`
    ] as const;
    }


export const getGetSystemDefaultsQueryOptions = <TData = Awaited<ReturnType<typeof getSystemDefaults>>, TError = GetSystemDefaults400 | GetSystemDefaults500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemDefaultsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemDefaults>>> = ({ signal }) => getSystemDefaults({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemDefaultsQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemDefaults>>>
export type GetSystemDefaultsQueryError = GetSystemDefaults400 | GetSystemDefaults500


export function useGetSystemDefaults<TData = Awaited<ReturnType<typeof getSystemDefaults>>, TError = GetSystemDefaults400 | GetSystemDefaults500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemDefaults>>,
          TError,
          Awaited<ReturnType<typeof getSystemDefaults>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemDefaults<TData = Awaited<ReturnType<typeof getSystemDefaults>>, TError = GetSystemDefaults400 | GetSystemDefaults500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemDefaults>>,
          TError,
          Awaited<ReturnType<typeof getSystemDefaults>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemDefaults<TData = Awaited<ReturnType<typeof getSystemDefaults>>, TError = GetSystemDefaults400 | GetSystemDefaults500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取系统默认设置
 */

export function useGetSystemDefaults<TData = Awaited<ReturnType<typeof getSystemDefaults>>, TError = GetSystemDefaults400 | GetSystemDefaults500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemDefaults>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemDefaultsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUpdateSystemDefaultsUrl = () => {




  return `/api/system/defaults`
}

/**
 * @summary 更新系统默认设置
 */
export const updateSystemDefaults = async (systemDefaultsRequest: SystemDefaultsRequest, options?: RequestInit): Promise<SystemDefaultsResponse> => {

  return customFetch<SystemDefaultsResponse>(getUpdateSystemDefaultsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(systemDefaultsRequest)
  }
);}





export const getUpdateSystemDefaultsMutationOptions = <TError = UpdateSystemDefaults400 | UpdateSystemDefaults500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemDefaults>>, TError,{data: SystemDefaultsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSystemDefaults>>, TError,{data: SystemDefaultsRequest}, TContext> => {

const mutationKey = ['updateSystemDefaults'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSystemDefaults>>, {data: SystemDefaultsRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateSystemDefaults(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSystemDefaultsMutationResult = NonNullable<Awaited<ReturnType<typeof updateSystemDefaults>>>
    export type UpdateSystemDefaultsMutationBody = SystemDefaultsRequest
    export type UpdateSystemDefaultsMutationError = UpdateSystemDefaults400 | UpdateSystemDefaults500

    /**
 * @summary 更新系统默认设置
 */
export const useUpdateSystemDefaults = <TError = UpdateSystemDefaults400 | UpdateSystemDefaults500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSystemDefaults>>, TError,{data: SystemDefaultsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSystemDefaults>>,
        TError,
        {data: SystemDefaultsRequest},
        TContext
      > => {
      return useMutation(getUpdateSystemDefaultsMutationOptions(options), queryClient);
    }
    export const getGetHealthUrl = () => {




  return `/api/health`
}

/**
 * @summary 健康检查
 */
export const getHealth = async ( options?: RequestInit): Promise<HealthResponse> => {

  return customFetch<HealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth400 | GetHealth500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = GetHealth400 | GetHealth500


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth400 | GetHealth500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth400 | GetHealth500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth400 | GetHealth500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 健康检查
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth400 | GetHealth500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






