/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListMyTenants400,
  ListMyTenants500,
  ListMyTenantsParams,
  PageResponseTenantResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListMyTenantsUrl = (params?: ListMyTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/tenants/my?${stringifiedParams}` : `/api/tenants/my`
}

/**
 * @summary 获取当前用户的组织列表
 */
export const listMyTenants = async (params?: ListMyTenantsParams, options?: RequestInit): Promise<PageResponseTenantResponse> => {

  return customFetch<PageResponseTenantResponse>(getListMyTenantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMyTenantsQueryKey = (params?: ListMyTenantsParams,) => {
    return [
    `/api/tenants/my`, ...(params ? [params] : [])
    ] as const;
    }


export const getListMyTenantsQueryOptions = <TData = Awaited<ReturnType<typeof listMyTenants>>, TError = ListMyTenants400 | ListMyTenants500>(params?: ListMyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyTenantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyTenants>>> = ({ signal }) => listMyTenants(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyTenants>>>
export type ListMyTenantsQueryError = ListMyTenants400 | ListMyTenants500


export function useListMyTenants<TData = Awaited<ReturnType<typeof listMyTenants>>, TError = ListMyTenants400 | ListMyTenants500>(
 params: undefined |  ListMyTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyTenants>>,
          TError,
          Awaited<ReturnType<typeof listMyTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyTenants<TData = Awaited<ReturnType<typeof listMyTenants>>, TError = ListMyTenants400 | ListMyTenants500>(
 params?: ListMyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyTenants>>,
          TError,
          Awaited<ReturnType<typeof listMyTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyTenants<TData = Awaited<ReturnType<typeof listMyTenants>>, TError = ListMyTenants400 | ListMyTenants500>(
 params?: ListMyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前用户的组织列表
 */

export function useListMyTenants<TData = Awaited<ReturnType<typeof listMyTenants>>, TError = ListMyTenants400 | ListMyTenants500>(
 params?: ListMyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






