/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RayFlow API
 * 🐟 RayFlow - Flink/Fluss/Paimon 任务发布管理平台 API 文档
 * OpenAPI spec version: 0.0.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateVariable400,
  CreateVariable500,
  DeleteVariable200,
  DeleteVariable400,
  DeleteVariable500,
  ListVariables400,
  ListVariables500,
  ListVariablesParams,
  PageResponseVariableResponse,
  UpdateVariable400,
  UpdateVariable500,
  VariableRequest,
  VariableResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getUpdateVariableUrl = (id: number,) => {




  return `/api/variables/${id}`
}

/**
 * @summary 更新变量
 */
export const updateVariable = async (id: number,
    variableRequest: VariableRequest, options?: RequestInit): Promise<VariableResponse> => {

  return customFetch<VariableResponse>(getUpdateVariableUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(variableRequest)
  }
);}





export const getUpdateVariableMutationOptions = <TError = UpdateVariable400 | UpdateVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariable>>, TError,{id: number;data: VariableRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateVariable>>, TError,{id: number;data: VariableRequest}, TContext> => {

const mutationKey = ['updateVariable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVariable>>, {id: number;data: VariableRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateVariable(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateVariableMutationResult = NonNullable<Awaited<ReturnType<typeof updateVariable>>>
    export type UpdateVariableMutationBody = VariableRequest
    export type UpdateVariableMutationError = UpdateVariable400 | UpdateVariable500

    /**
 * @summary 更新变量
 */
export const useUpdateVariable = <TError = UpdateVariable400 | UpdateVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVariable>>, TError,{id: number;data: VariableRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVariable>>,
        TError,
        {id: number;data: VariableRequest},
        TContext
      > => {
      return useMutation(getUpdateVariableMutationOptions(options), queryClient);
    }
    export const getDeleteVariableUrl = (id: number,) => {




  return `/api/variables/${id}`
}

/**
 * @summary 删除变量
 */
export const deleteVariable = async (id: number, options?: RequestInit): Promise<DeleteVariable200> => {

  return customFetch<DeleteVariable200>(getDeleteVariableUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteVariableMutationOptions = <TError = DeleteVariable400 | DeleteVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariable>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVariable>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteVariable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVariable>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteVariable(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteVariableMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVariable>>>

    export type DeleteVariableMutationError = DeleteVariable400 | DeleteVariable500

    /**
 * @summary 删除变量
 */
export const useDeleteVariable = <TError = DeleteVariable400 | DeleteVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVariable>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVariable>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteVariableMutationOptions(options), queryClient);
    }
    export const getListVariablesUrl = (params?: ListVariablesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/variables?${stringifiedParams}` : `/api/variables`
}

/**
 * @summary 获取当前组织变量列表
 */
export const listVariables = async (params?: ListVariablesParams, options?: RequestInit): Promise<PageResponseVariableResponse> => {

  return customFetch<PageResponseVariableResponse>(getListVariablesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVariablesQueryKey = (params?: ListVariablesParams,) => {
    return [
    `/api/variables`, ...(params ? [params] : [])
    ] as const;
    }


export const getListVariablesQueryOptions = <TData = Awaited<ReturnType<typeof listVariables>>, TError = ListVariables400 | ListVariables500>(params?: ListVariablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVariablesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVariables>>> = ({ signal }) => listVariables(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVariablesQueryResult = NonNullable<Awaited<ReturnType<typeof listVariables>>>
export type ListVariablesQueryError = ListVariables400 | ListVariables500


export function useListVariables<TData = Awaited<ReturnType<typeof listVariables>>, TError = ListVariables400 | ListVariables500>(
 params: undefined |  ListVariablesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariables>>,
          TError,
          Awaited<ReturnType<typeof listVariables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariables<TData = Awaited<ReturnType<typeof listVariables>>, TError = ListVariables400 | ListVariables500>(
 params?: ListVariablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariables>>,
          TError,
          Awaited<ReturnType<typeof listVariables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariables<TData = Awaited<ReturnType<typeof listVariables>>, TError = ListVariables400 | ListVariables500>(
 params?: ListVariablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前组织变量列表
 */

export function useListVariables<TData = Awaited<ReturnType<typeof listVariables>>, TError = ListVariables400 | ListVariables500>(
 params?: ListVariablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariables>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVariablesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateVariableUrl = () => {




  return `/api/variables`
}

/**
 * @summary 创建变量
 */
export const createVariable = async (variableRequest: VariableRequest, options?: RequestInit): Promise<VariableResponse> => {

  return customFetch<VariableResponse>(getCreateVariableUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(variableRequest)
  }
);}





export const getCreateVariableMutationOptions = <TError = CreateVariable400 | CreateVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariable>>, TError,{data: VariableRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createVariable>>, TError,{data: VariableRequest}, TContext> => {

const mutationKey = ['createVariable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVariable>>, {data: VariableRequest}> = (props) => {
          const {data} = props ?? {};

          return  createVariable(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateVariableMutationResult = NonNullable<Awaited<ReturnType<typeof createVariable>>>
    export type CreateVariableMutationBody = VariableRequest
    export type CreateVariableMutationError = CreateVariable400 | CreateVariable500

    /**
 * @summary 创建变量
 */
export const useCreateVariable = <TError = CreateVariable400 | CreateVariable500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVariable>>, TError,{data: VariableRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVariable>>,
        TError,
        {data: VariableRequest},
        TContext
      > => {
      return useMutation(getCreateVariableMutationOptions(options), queryClient);
    }
