#!/usr/bin/env python3
"""Generate RayFlow Admin SDK from Springdoc OpenAPI.

This follows OwlApi's SDK workflow:
1. fetch OpenAPI JSON from the running backend
2. unwrap RayFlow's {code,msg,data} response envelope at type level
3. run Orval in frontend/admin
4. write an SDK barrel export
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
ADMIN_ROOT = REPO_ROOT / "frontend" / "admin"
SPEC_OUT = ADMIN_ROOT / "openapi.json"
SDK_DIR = ADMIN_ROOT / "src" / "lib" / "sdk"


def fetch_openapi() -> dict[str, Any]:
    url = os.environ.get("OPENAPI_URL", "http://localhost:3000/v3/api-docs")
    print(f"  🔄 拉取 OpenAPI: {url}")
    try:
        with urllib.request.urlopen(url, timeout=20) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception as exc:  # noqa: BLE001 - CLI should show the exact failure
        print(f"  ❌ OpenAPI 拉取失败: {exc}")
        print("     请先启动后端: make dev-up 或 docker compose -f docker-compose.dev.yml up backend")
        sys.exit(1)


def unwrap_envelopes(spec: dict[str, Any]) -> None:
    schemas = spec.get("components", {}).get("schemas", {})
    envelope_to_data: dict[str, Any] = {}

    for name, schema in list(schemas.items()):
        props = schema.get("properties") or {}
        if {"code", "msg", "data"}.issubset(props):
            envelope_to_data[name] = props.get("data") or {"type": "object"}

    def maybe_unwrap_schema(schema: Any) -> Any:
        if not isinstance(schema, dict):
            return schema

        ref = schema.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            name = ref.rsplit("/", 1)[-1]
            if name in envelope_to_data:
                return json.loads(json.dumps(envelope_to_data[name]))

        props = schema.get("properties") or {}
        if {"code", "msg", "data"}.issubset(props):
            return json.loads(json.dumps(props.get("data") or {"type": "object"}))

        for key, value in list(schema.items()):
            if isinstance(value, dict):
                schema[key] = maybe_unwrap_schema(value)
            elif isinstance(value, list):
                schema[key] = [maybe_unwrap_schema(item) for item in value]
        return schema

    for path_item in (spec.get("paths") or {}).values():
        for operation in path_item.values():
            if not isinstance(operation, dict):
                continue
            responses = operation.get("responses") or {}
            for response in responses.values():
                content = (response or {}).get("content") or {}
                for media in content.values():
                    if "schema" in media:
                        media["schema"] = maybe_unwrap_schema(media["schema"])

    for name in envelope_to_data:
        schemas.pop(name, None)

    if envelope_to_data:
        print(f"  ✅ RayFlow R envelope 展平完成 ({len(envelope_to_data)} 个)")


def fix_duplicate_operation_ids(spec: dict[str, Any]) -> None:
    seen: set[str] = set()
    fixed = 0
    for path, path_item in (spec.get("paths") or {}).items():
        for method, operation in path_item.items():
            if not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                continue
            if operation_id in seen:
                suffix = "".join(part.capitalize() for part in path.strip("/").split("/")[-2:])
                operation["operationId"] = f"{operation_id}{method.capitalize()}{suffix}"
                fixed += 1
            seen.add(operation["operationId"])
    if fixed:
        print(f"  ✅ 重复 operationId 修复完成 ({fixed} 个)")


def write_openapi(spec: dict[str, Any]) -> None:
    SPEC_OUT.write_text(json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  ✅ OpenAPI → {SPEC_OUT}")


def run_orval() -> None:
    print("  📦 生成 Admin SDK")
    result = subprocess.run(
        ["pnpm", "orval", "--config", "orval.config.ts"],
        cwd=ADMIN_ROOT,
        check=False,
    )
    if result.returncode != 0:
        print("  ❌ Orval SDK 生成失败")
        sys.exit(result.returncode)
    print("  ✅ Orval SDK 生成成功")


def write_barrel() -> None:
    tag_files = sorted(
        file.stem
        for file in SDK_DIR.glob("*.ts")
        if file.stem not in {"index", "sdk.schemas"}
    )
    lines = [
        "// SDK barrel - generated by scripts/generate_sdk.py",
        "export * from './sdk.schemas';",
    ]
    lines.extend(f"export * from './{name}';" for name in tag_files)
    (SDK_DIR / "index.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  ✅ SDK barrel → {SDK_DIR / 'index.ts'}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--openapi-only", action="store_true")
    args = parser.parse_args()

    spec = fetch_openapi()
    unwrap_envelopes(spec)
    fix_duplicate_operation_ids(spec)
    write_openapi(spec)
    if args.openapi_only:
        return
    run_orval()
    write_barrel()


if __name__ == "__main__":
    main()
